### ISSUE TITLE
Bulk Upload Template Download link broken

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/u-bahn-app#10]
**Steps to reproduce**
1. Navigate to Bulk Upload page.
2. Click `Download Import Template (.XLS)`

**Expected Result**
Template xls files download begins.

**Actual result**
XML error:
![image](https://user-images.githubusercontent.com/6014049/84282499-d2eba200-ab07-11ea-9b8a-8c56536d3ff3.png)

**Comment by callmekatootie** [comment]
Will be able to verify this once the Auth0 token issue is resolved - (See slack)

**Comment by callmekatootie** [comment]
@cwdcwd I see that the database continues to return the record for the template, but accessing the file indicates that it does not exist anymore in the S3 bucket. Were the files in the bucket erased?

**Comment by callmekatootie** [comment]
This is now resolved.
