### ISSUE TITLE
User details in home page does not have Location information but in sort option Location is present

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#100]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Sort by
3) Observe "Location" is present as an option.

Current Result :
In Home page user details does not have Location details but sort by option has Location as an option.

Expected result:
In Home page user details should have location

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![7](https://user-images.githubusercontent.com/51490878/87247802-abc02180-c473-11ea-8cd9-d9d5570ce2b0.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87247805-aebb1200-c473-11ea-9123-fab8ef3f3015.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87247809-b11d6c00-c473-11ea-87b7-6648b4ca8d7f.png)

**Comment by callmekatootie** [comment]
not a valid bug. The location is visible when you edit the user profile.
