### ISSUE TITLE
Disabled pagination controls should not have 'pointer' mouse hover cursor 

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#104]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on second tab
5. Select a group which has less members (less than 10)
6. Scroll down to pagination control
7. Mouse hover over the 'prev page' and 'next page' arrow
8. Notice the hover

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 7 12 56 PM" src="https://user-images.githubusercontent.com/5712602/87247818-baa6d400-c473-11ea-8c5e-58e26d45503b.png">

### Current Results
Disabled pagination controls have 'pointer' mouse hover cursor 

### Expected Results
Disabled pagination controls should not have 'pointer' mouse hover cursor 

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
not a valid bug. the buttons are still disabled.

**Comment by rprakash20** [comment]
@callmekatootie Since the buttons are disabled, mouse hover should be default I think.

**Comment by callmekatootie** [comment]
I am afraid my decision stands
