### ISSUE TITLE
Logout Should Not Show After Clicking Outside. It Should Hide

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#108]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder 

3. Click Near TonyJ (Topcoder) Then Try To Click Outside & Observe

4. See Screencast:-
[5.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908594/5.mp4.zip)

5. Current Result:- Logout Is Showing Even After Clicking Outside

6. Expected Result:- Logout Should Not Show After Clicking Outside. It Should Hide

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #73
