### ISSUE TITLE
"Add to Group" popup does not say for which user this operation.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#109]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on "+" sign in in any userr.
3) "Add to Group" popup opened.
4) 

Current Result :
"Add to Group" popup does not say for which user this operation.
User does not remember for which user he/she has clicked "+" sign.

Expected result:
Popup should display User Name.

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![8](https://user-images.githubusercontent.com/51490878/87247924-4fa9cd00-c474-11ea-86d2-dfe87050d035.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87247942-5afcf880-c474-11ea-9425-51e6263ed563.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87247945-5d5f5280-c474-11ea-81a8-5618f499db73.png)

**Comment by callmekatootie** [comment]
@wdprice Should we take this as a bug? Seems like it could be handy

**Comment by callmekatootie** [comment]
Checked with PM - this would be a feature request and not a bug.
