### ISSUE TITLE
[$10] Search box accepts blank spaces.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#110]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Enter blank spaces in the search box and hit enter.
3. Observe.

Actual results:
Application searches for profiles.

Expected results:
Blank spaces only should not be accepted as input by the application

Browser version: Chrome: Version 83.0.4103.116

OS version : 

Screen shots:
![5](https://user-images.githubusercontent.com/57211549/87247909-4d487280-c476-11ea-94a4-5b76e680c66b.png)

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Expected - Trim the search input in the header before triggering the search. If after trim, there is no text to search, don't search

**Comment by callmekatootie** [comment]
Resolved
