### ISSUE TITLE
Pagination should change > Showing 1-1 of 1 profiles

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#111]
![image](https://user-images.githubusercontent.com/42398485/87247943-59074b00-c41c-11ea-8c68-de8abda567a5.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Groups)
3. Select a group with 1 profile
4. Observe the pagination > Showing 1-1 of 1 profiles

**Actual Result:** Showing 1-1 of 1 profiles

**Expected Result:** Showing 1-1 of 1 profile

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
profiles = profile

will take it as a valid bug

**Comment by callmekatootie** [comment]
Resolved
