### ISSUE TITLE
Allows assigning non boolean value to isAvailable

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#112]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Select some filter and get results
    3. Click on edit button for some user
    4. Try changing value of "isAvailable" to anything ("f" for example)

## Screenshots/Video
![Screenshot from 2020-07-12 19-17-42](https://user-images.githubusercontent.com/32861951/87247946-605a4300-c474-11ea-818e-0a24f4edf226.png)

##  Actual Result(s)

It is updated to "f"

##  Expected Result(s)

Should allow only boolean ("true"/"false") values

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
duplicate #85

**Comment by g1tman** [comment]
This is different issue than the mentioned one. Moreover, I think isAvailable is a custom attribute and is not linked with the available toggle.

**Comment by g1tman** [comment]
@callmekatootie This is different issue than the mentioned one. Moreover, I think isAvailable is a custom attribute and is not linked with the available toggle.

**Comment by callmekatootie** [comment]
Gotcha. Even in that case it is not a valid issue. There is no validation for the custom attribute fields for now - user can enter anything
