### ISSUE TITLE
System Doesn save excel after uploaded

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#113]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. go to Drag Profile Data Tab

## Expected Result
System will save the excel data after file uploaded

## Actual Result
System not saving the excel data after file uploaded

## Screenshot
![](https://www.dropbox.com/s/58q2ljn6eez61qx/upload.png?raw=1)

## Video
https://www.dropbox.com/s/x184wd4xzhhd8b1/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2016-44-17.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
Not sure what you mean by "save excel" here. Marking as invalid

**Comment by Citra-citoru** [comment]
Sorry typo in the title. But in the actual result i mentioned **System not saving the excel data after file uploaded**

**Comment by callmekatootie** [comment]
Ok - but I still did not get it. What do you mean by "no saving the excel data"? Do you mean you had new users in that excel or new values for existing users in that excel and they did not show up when you checked the search results?

**Comment by callmekatootie** [comment]
If yes, please share the excel file that you worked with

**Comment by Citra-citoru** [comment]
Yes, thats what i mean https://www.dropbox.com/scl/fi/rp6eerwtftpcfw37v8qvn/BULK_UPLOAD_TEMPLATE_07_04.xlsx?dl=0&rlkey=9qll1x5d5ofifb7a23mfqf68a

**Comment by callmekatootie** [comment]
In the excel, the countryName that you provided in invalid. I think (because I am not sure either about the right value) it needs to be United Kingdom and not UK. There's a set of allowed values for the country field during user creation and in this case it failed.
