### ISSUE TITLE
input validation missing no of char ,special char 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/u-bahn-app#114]
Steps to reproduce
• 1. Go to application-https://crm-benefits-prototype.herokuapp.com/pharmacy
• 2. select user click edit
3.enter user name as <html>@$$@@

4, observe

Current results
special character and html code 

 accepted as input 

Expected results
should not accept as input 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Windows 10
Screen shots
![bandicam 2020-07-12 19-17-40-709](https://user-images.githubusercontent.com/3225433/87247947-618b7000-c474-11ea-9ca4-0a50fc46adab.jpg)

**Comment by callmekatootie** [comment]
@karthikbecse is it possible for you to share the excel file that you uploaded
