### ISSUE TITLE
"Esc" key does not dismiss Sort by popup

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#115]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Sort by drop down
3) popup opened.
4) Press Esc key
Observe

Current Result :
"Esc" key does not dismiss Sort by popup

Expected result:
"Esc" key should dismiss Sort by popup

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![9](https://user-images.githubusercontent.com/51490878/87248001-aca58300-c474-11ea-848b-9db05d39b45b.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87248004-af07dd00-c474-11ea-9dbf-2c60ed5c2103.png)

![Uploading Windows10_version.png…]()

**Comment by callmekatootie** [comment]
not a valid bug. it's a feature more like...
