### ISSUE TITLE
"Sort by" dropdown should close when click outside

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#117]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on "Sort by" dropdown
3. Click outside "Sort by" dropdown then observe

**Screenshot/screencast:**

https://drive.google.com/drive/folders/1nFgxARF2LUoloNeRQlp1IOvk-rf5HueI

**Actual Result:** "Sort by" dropdown doesn't close when click outside

**Expected Result:** "Sort by" dropdown should close when click outside

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
Duplicate #102
