### ISSUE TITLE
UI issue on the Profile view on other groups

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#119]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 02
Click click on Test Group 
Observe

**Actual Result:** Text  and tags overlaps 

**Expected Result:** Should display the layout properly

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116

**Comment by bhattashubham** [comment]
![bug1](https://user-images.githubusercontent.com/48902251/87248013-d1025f00-c476-11ea-871e-dced911bd434.png)

![Device_info](https://user-images.githubusercontent.com/48902251/87248022-dcee2100-c476-11ea-920b-4c0513732983.png)

**Comment by callmekatootie** [comment]
duplicate #91
