### ISSUE TITLE
IsAvailable attribute is not changing when status is change to unavailable

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#120]
**Describe the bug**
IsAvailable attribute is not changing when status is change to unavailable

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now change the user status to available to unavailable
3. now click on edit and check the isAvailable text field it is showing as true

**Actual Behavior**
By changing using toggle button the option is not getting in refelected in isAvailability field

**Expected behavior**
Option must refelect in text field also

**Screenshots**
[2020-07-12 18-48-57.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908597/2020-07-12.18-48-57.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
duplicate #85
