### ISSUE TITLE
No able to do cancel or done when open the add filter popup

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#121]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on add filter so popup open 
3. We can not do any cancel or done because popup UI not with in the page 

**Actual Result:** 
We can not do any cancel or done because popup UI not with in the page 

**Expected Result:** 
Popup should be visible with in the page and user accessible 

**Screenshot**
[Bug3.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908598/Bug3.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0| Chrome 83.0.4103.106 | Edge 83.0.478.54 | Firefox 78.0.2

**Comment by callmekatootie** [comment]
duplicate #17
