### ISSUE TITLE
[Bug Hunt] Add to Groups doesn't search the added group name

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#122]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Navigate to the second tab.
3. Go to the + icon under Group 
4. Add the Group name by clicking the +Create button. 
5. After creating , try to search with the same name. 

Actual results:
After typing the Added Group Name it doesn't display in the list.

Expected results:
The added group should be listed when searched with the same name. 

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
<img width="811" alt="6" src="https://user-images.githubusercontent.com/57211549/87248059-132ba080-c477-11ea-860a-41187f399297.png">

**Comment by callmekatootie** [comment]
cannot reproduce
