### ISSUE TITLE
"Skills" filter not working

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#124]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Wait sometime to load user details.
3) scroll down to Skills filter and type "Angular" and enter
4) wait and observe

Current Result :
"Skills" filter not working

Expected result:
"Skills" filter should work.

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![10](https://user-images.githubusercontent.com/51490878/87248129-5a189680-c475-11ea-952a-aa3a40d64df2.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87248130-5c7af080-c475-11ea-9e39-5035021367d8.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87248132-5edd4a80-c475-11ea-9e4f-8b792a0a7590.png)

**Comment by coderkid19** [comment]
Applying Skills filter has no change in retrieved result

**Comment by callmekatootie** [comment]
You need to select a value from the dropdown suggestion. I am able to see it in firefox.
