### ISSUE TITLE
[Bug Hunt] UI breaks when user enters too long company name.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#125]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
2. Click on edit icon of the profile.
3. Enter very long text in "Company" section and observe.

Actual results:
UI is broken and text is displayed over the other options.

Expected results:
UI should not be broken.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![6](https://user-images.githubusercontent.com/57211549/87248095-32c2c900-c477-11ea-8018-d0cb0439b860.png)

**Comment by callmekatootie** [comment]
duplicate #91
