### ISSUE TITLE
style of "Logout" should be changed

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#126]
### Reproduction Steps ###

1. login to the app

2. click on the down arrow on top right

3. observe

### Expected Result ###
The style of "Logout" should be changed.

### Actual Result ###
See screenshot, there are too much space on the left side.

### Screenshot and/or screencast ###

![s](https://user-images.githubusercontent.com/4590317/87248122-3449bc80-c48a-11ea-812f-385420f3cc09.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
not a valid bug. The width is equal to the length of the parent
