### ISSUE TITLE
User is also able scroll horizontally when there is no data available horizontally in IE

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#127]
**Describe the bug**
User is also able scroll horizontally when there is no data available horizontally in IE

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now observe the user is able to scroll horizontally and there is no data

**Actual Behavior**
observe the user is able to scroll horizontally and there is no data

**Expected behavior**
There should not be any scroll bar if there is no data horzontally

**Screenshots**
[2020-07-12 18-48-57.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908604/2020-07-12.18-48-57.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment]
duplicate #62
