### ISSUE TITLE
Showing 1-1 of 1 profiles should be Profile

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#129]
screenshots
![Screenshot (348)](https://user-images.githubusercontent.com/29044523/87248131-5dac1d80-c475-11ea-9bac-4a8f471c4127.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Filter Data that there is only one data available and Observe

Actual Result: Showing 1-1 of 1 profiles 

Expected Result: Showing 1-1 of 1 profile

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment]
duplicate #111
