### ISSUE TITLE
[Bug Hunt] User name displayed outside the designated box.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#130]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on edit icon of the profile.
3. Enter very long text in "Last Name" section and observe.

Actual results:
The name is displayed outside the designated box.

Expected results:
User information should not be displayed outside the box.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![7](https://user-images.githubusercontent.com/57211549/87248145-86351700-c477-11ea-9890-3c697a555515.png)

**Comment by callmekatootie** [comment]
duplicate #91
