### ISSUE TITLE
clicking on back button on browser doesnt close down the previous screen

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#131]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. clickon edit button then, clicking on back button on browser doesnt close down the previous screen

Current results
clicking on back button on browser doesnt close down the previous screen
Expected results
clicking on back buton should close down the edit screen as it changes the page in the backend.

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
[Screen Recording 2020-07-12 at 7.23.43 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908606/Screen.Recording.2020-07-12.at.7.23.43.PM.mov.zip)
![Screen Shot 2020-07-12 at 7 23 58 PM](https://user-images.githubusercontent.com/57220292/87248147-73214780-c475-11ea-9cf1-1c5c576bbb97.png)

**Comment by callmekatootie** [comment]
it's a modal not a new page. no expectation that it should close on clicking back button
