### ISSUE TITLE
Sort By Options Having Alignment Issue

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#132]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click Near Sort By Dropdown Then Observe

4. See Screenshot:-
![6](https://user-images.githubusercontent.com/42583358/87248141-68ff4900-c475-11ea-9654-feb87b4cb0f0.png)

5. Current Result:- Sort By Options Having Alignment Issue

6. Expected Result:- Sort By Options Should Not Having Alignment Issue

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
intentionally right aligned
