### ISSUE TITLE
Minimise button doesnt work for skill search

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#133]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. In left sidebar see "Skills" search panel
    3. Click on "v" button to minimize the box

## Screenshots/Video

![Screenshot from 2020-07-12 19-23-30](https://user-images.githubusercontent.com/32861951/87248177-9e0b9b80-c475-11ea-8dd1-47793d9e69cd.png)

##  Actual Result(s)

Doesnt minimise

##  Expected Result(s)

should minimise the box

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
cannot reproduce
