### ISSUE TITLE
"Add filter" popup should close when click outside

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#134]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on any ""Add filter"" button -> show ""Add filter"" popup
3. Click outside ""Add filter"" popup then observe

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1Ew16LWAbJ6H4kth4EJwR8DdyzP_gJx9c

**Actual Result:** ""Add filter"" popup doesn't close when click outside

**Expected Result:** ""Add filter"" popup should close when click outside

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
This is intentional - in some scenarios, we don't want the member to accidentally click outside and lose their changes
