### ISSUE TITLE
"Add Filters" popup show transparent background 

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#135]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab and click on "Add Filter" button 
3. Observe popup 

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1P-p9sxJel5-VTmrQ87zZi7PVEUUz66QM?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** "Add Filters" popup show transparent background. It make difficult to seeing. 

**Expected Result:**  "Add Filters" popup should not show transparent background. 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
duplicate #39
