### ISSUE TITLE
[$20] Filter: Availability is not reset when the user click on the reset button

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#136]
![image](https://user-images.githubusercontent.com/42398485/87248186-acc66400-c41d-11ea-97df-572755b3aa2b.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Select some filters including Availability
4. Click Reset and observe

**Actual Result:** Filter: Availability is not reset when user click on the reset button

**Expected Result:** Should reset the Availability also

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Expected: On clicking RESET, it should go back to how the filters were during page load - both available and not available are active, but they do not have the green dot indicator on them

**Comment by callmekatootie** [comment]
Resolved
