### ISSUE TITLE
[$10] "X" button should be disabled if the field is empty

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#138]
### Reproduction Steps ###

1. login to the app

2. observe the "X" button on the top

### Expected Result ###
"X" button should be disabled if the field is empty

### Actual Result ###
See screenshot

### Screenshot and/or screencast ###
![close](https://user-images.githubusercontent.com/4590317/87248200-ba660300-c48a-11ea-8709-6b28c0485911.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Expected: In the header, if there is no search text, then do not show the "X" that clears the input

**Comment by callmekatootie** [comment]
Resolved
