### ISSUE TITLE
Background is visible through "Add Filters" popup.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#139]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on "Add filters" from left side buttom
3) popup opened.
4) Scroll up and down
Observe

Current Result :
Background is visible through "Add Filters" popup.

Expected result:
Background should not be visible through "Add Filters" popup.

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![11](https://user-images.githubusercontent.com/51490878/87248244-18d4b680-c476-11ea-9064-c66067d8ca76.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87248250-1c683d80-c476-11ea-8c72-e7ba0327f4c5.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87248258-268a3c00-c476-11ea-964d-af599e755f10.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87248260-2853ff80-c476-11ea-9447-934e807ba8b7.png)

**Comment by callmekatootie** [comment]
duplicate #39
