### ISSUE TITLE
Success notifications should be an modal popup not an alert

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#140]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Go to Group Tabs
4. type javascript and then click create button

## Expected Result
Notification after creating new group should be a modal popup not an alert

## Actual Result
Alert shown after successfully creating a new group.

## Screenshot
![](https://www.dropbox.com/s/qasb02178soqe7v/alert.png?raw=1)

## Video
https://www.dropbox.com/s/59lyk6bzomq9jtt/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2016-52-58.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
not a valid bug - we do not have a notification system. We are using browser's alert for now.
