### ISSUE TITLE
App stuck when user tries to create a group with spaces

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#142]
https://take.ms/MPGdf

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Group Tab
3. Enter spaces for Group Name > Create

In other browsers, app is not stuck

**Actual Result:** App stuck when a user tries to create a group with spaces

**Expected Result:** Should validate it, the app should not get stuck

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
duplicate #34
