### ISSUE TITLE
More locations in left sidebar reset on minimising,maximising

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#143]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Click on "More.." button in "Location" in left sidebar
    3. Click "v" button of "Location" to minimise it
    4. Click "v" button again to maximize it
    5. Observe

## Screenshots/Video
[sc13.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908611/sc13.zip)

##  Actual Result(s)

"more.." button appears again. And the extra options are hidden again.

##  Expected Result(s)

Should keep config as is on maximising back. If More.. was clicked earlier, it should show all.

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
not a valid bug. Collapse basically erases the section from memory and thus on expand, user has to click on More again...
