### ISSUE TITLE
for 1 profile should say 1 of 1 profile

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#145]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. for 1 profile should say 1 of 1 profile

Current results
for 1 profile should say 1 of 1 profile - currently it says 1 of 1 profiles
Expected results
for 1 profile should say 1 of 1 profile

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 7 30 37 PM](https://user-images.githubusercontent.com/57220292/87248273-46b9fb00-c476-11ea-9132-9bebc01966ae.png)

**Comment by callmekatootie** [comment]
duplicate #111
