### ISSUE TITLE
View is not proper in IE in 100% viewport

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#146]
Screenshots

![Screenshot (349)](https://user-images.githubusercontent.com/29044523/87248307-66e9ba00-c476-11ea-921a-7e8c5d986ef6.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Observe the webapp by scrolling to the right

Actual Result: the page is not shown properly

Expected Result: the page should be viewed properly

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11

**Comment by callmekatootie** [comment]
duplicate #62
