### ISSUE TITLE
[Common] Some texts are hidden in Filters

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#147]
![image](https://user-images.githubusercontent.com/42398485/87248324-763d1900-c41e-11ea-9ce3-cfa51235ff50.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Expand the Location Filters
4. Check North Abagailport

**Actual Result:** Some texts are hidden in Filters

**Expected Result:** Should display all the texts properly

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:**  IE11

**Comment by callmekatootie** [comment]
Not a bug - the tooltip needs to be shown which it does not and that is being handled in #128
