### ISSUE TITLE
groups should be sorted or should show with the group names at the top first which are active

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#154]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. groups should be sorted or should show with the group names at the top first which are active

Current results
groups should be sorted or should show with the group names at the top first which are active
Expected results
groups should be sorted or should show with the group names at the top first which are active

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots

![Screen Shot 2020-07-12 at 7 35 40 PM](https://user-images.githubusercontent.com/57220292/87248406-fabb8600-c476-11ea-8808-05a5764c512e.png)
![Screen Shot 2020-07-12 at 7 35 35 PM](https://user-images.githubusercontent.com/57220292/87248412-fe4f0d00-c476-11ea-909b-e610b371d118.png)

**Comment by callmekatootie** [comment]
not a valid bug

**Comment by akultalwar89** [comment]
@callmekatootie  -Hi, it was a usability issue - Like user was viewing the inactive group like Avenger first , then scrolled down to see which groups are active for them.

**Comment by callmekatootie** [comment]
Gotcha. I would take it more as a feature request than as a bug.

**Comment by akultalwar89** [comment]
@callmekatootie  - is usability issues not accepted in this bug hunt :)

**Comment by callmekatootie** [comment]
I am afraid this is more of a feature request than a bug
