### ISSUE TITLE
[Bug Hunt] User is Unable to add a new skill.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#156]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on edit icon of the profile.
3. Enter a skill and hit enter.
4. Observe.

Actual results:
No response is shown by the application.

Expected results:
New skill should be added to the respective user.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![10](https://user-images.githubusercontent.com/57211549/87248407-13c53680-c479-11ea-8da4-921010b5fe75.png)

**Comment by callmekatootie** [comment]
cannot reproduce
