### ISSUE TITLE
Allows selection of all file formats in dialog

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#157]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Click on Upload tab button
    3. Click on browse
    4. Dialog to select file appears

## Screenshots/Video
![Screenshot from 2020-07-12 19-36-26](https://user-images.githubusercontent.com/32861951/87248440-0c9d2900-c477-11ea-91da-61a514bf0f0e.png)

##  Actual Result(s)

Allows selecting any file format in dialog (Then later shows error)

##  Expected Result(s)

Should be configured to only allow selection of appropriate files (csv , xls)

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
After discussion on Slack - Will not be fixed. Closing
