### ISSUE TITLE
[Common] First and Last Name field is accepting spaces

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#158]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. CLick  Edit from a profile
4. Enter spaces for First and Last Name field 
5. Click Save

**Actual Result:** First and Last Name field are accepting spaces

**Expected Result:** Should validate it

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/87248471-362a6600-c41f-11ea-9bfb-19899c462a4f.png)

**Comment by callmekatootie** [comment]
valid bug. good catch.

**Comment by callmekatootie** [comment]
duplicate #148
