### ISSUE TITLE
If user has been deactivated than there is no option to reactivate

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#159]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Edit icon on any profile
3) Deactivate profile
4) Now shown "This user has been deactivated"
Try to reactivate

Current Result :
If user has been deactivated than there is no option to reactivate

Expected result:
If user has been deactivated than there should be option to reactivate

Latest Firefox/Chrome
Windows 10

**Comment by coderkid19** [comment]
![13](https://user-images.githubusercontent.com/51490878/87248463-2c345180-c477-11ea-884e-c2200097cf6d.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87248464-2f2f4200-c477-11ea-9e54-edbe197e3056.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87248467-30f90580-c477-11ea-9594-751747bd92db.png)

**Comment by callmekatootie** [comment]
not a valid issue
