### ISSUE TITLE
group shows 3 but shows 4 profiles

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#162]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. groups shows 3 but shows 4 profiles

Current results
groups shows 3 but shows 4 profiles
Expected results
groups should show 4 if 4 profiles are present or viceversa

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 7 37 18 PM](https://user-images.githubusercontent.com/57220292/87248468-33f3f600-c477-11ea-8d5d-8eefaa85a645.png)

**Comment by callmekatootie** [comment]
both the apis are external - the group count and the users in the group. App not at fault.
