### ISSUE TITLE
Filter section in GROUP tab is not updated if we delete a group from a USER

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#164]
Screenshots

![Screenshot (350)](https://user-images.githubusercontent.com/29044523/87248477-41a97b80-c477-11ea-92a7-57ca4423e3a8.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to Second Tab
Click on Any Group and get the user
Now delete that group from one user and Observe the count of the group is not changed in the left side nav

Actual Result: Count is not updated when group is deleted from user

Expected Result: Group Count should be updated

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment]
the group count is not dynamic. it is static. not a valid issue.

**Comment by Vips19** [comment]
@callmekatootie  the group count gets updated if we go to next tab or refresh the page

**Comment by callmekatootie** [comment]
Yep - that is what I mean by static. If you visit the page again, the group count is fetched again but it is not updated due to actions on the UI which should cause its count to reduce dynamically
