### ISSUE TITLE
filter search only works when more than 2 characters are typed in the filter text boxes

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#166]
### Steps to Reproduce
Open https://skill-search.topcoder-dev.com/ web app
Login with tonyj /appirio123
Select topcoder as organization
Type "LO" in the lcoation filter textbox
Notice the search results

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 7 38 07 PM" src="https://user-images.githubusercontent.com/5712602/87248502-61d93a80-c477-11ea-843e-53851d52f9c8.png">

### Current Results
filter search only works when more than 2 characters are typed in the filter text boxes

### Expected Results
Filter should work when only one or two characters are typed in.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
intentional. not a bug.

**Comment by rprakash20** [comment]
@callmekatootie This should be a bug, since group search works with less than 3 characters on Groups tab and all other filters on the search tab also works with less than 3 characters.

**Comment by callmekatootie** [comment]
I am afraid my decision stands - I checked the code and it explicitly starts searching only after user has entered more characters.
