### ISSUE TITLE
Create Button Is Highlighting But Not Accessing

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#170]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Icon Next To Filter Then Try To Click On Create Then Observe.

4. See Screencast:-
[7.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908625/7.mp4.zip)

5. Current Result:- Create Button Is Highlighting But Not Accessing

6. Expected Result:- Create Button Should Be Accessing

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #60
