### ISSUE TITLE
[Bug Hunt] Displayed group profiles is being searched again and again.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#171]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Go to the second tab.
3. Search "o" on search box and click on the first option seen.
4. Now click on the first option again and again and observe.

Actual results:
The displayed group is being reloaded again and again.

Expected results:
User should not be allowed to click on the displayed group name second time.
OR
Application should not respond to the second click.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![11](https://user-images.githubusercontent.com/57211549/87248593-fb095080-c479-11ea-8dfd-37a5feb1e948.png)

**Comment by callmekatootie** [comment]
duplicate #165
