### ISSUE TITLE
Failed to Save new group That contain only 2 characters.

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#172]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Click middle tab (create new group)
4. In the search box type **ja**

## Expected Result
We can save the new group even it only contains two letters.

## Actual Result
System error when creating group if  the group only contains two letters.

## Screenshot
![](https://www.dropbox.com/s/urfroczr6kjrctk/2_char.png?raw=1)

## Video
https://www.dropbox.com/s/kd7yx7rxdfyj281/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2017-08-23.mp4?dl=0
## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
duplicate #116
