### ISSUE TITLE
If User is removed than also user is present in Group search result from Group tab

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#174]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Middle Tab
3) Search by Group opened
4) Click on one group Say "Avengers"
5) wait some time to retrieve data
6) It shows retrieve profiles after some time.
7) Now, Click on cross sign in same group for a member. This is to remove that user from that group.
8) Observe, Even after group deleted user remains in search result.

Current Result :
If User is removed than also user is present in Group search result from Group tab

Expected result:
Search result to refresh as that user is no more part of that group.

Latest Firefox
Windows 10

Video attached.

**Comment by coderkid19** [comment]
[14.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908627/14.zip)

**Comment by coderkid19** [comment]
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87248653-4a4e8180-c478-11ea-8be6-6c0786215b53.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87248656-4e7a9f00-c478-11ea-95b4-1dbd13183d19.png)

**Comment by callmekatootie** [comment]
the deletion is not dynamic - if a group is removed from a user, the user will still be shown until the user refreshes. not a valid issue.
