### ISSUE TITLE
big group name overlaps button

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#175]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. big group name overlaps button

Current results
big group name overlaps button
Expected results
ibig group name overlaps button - shouldnt overlap button

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 7 45 09 PM](https://user-images.githubusercontent.com/57220292/87248651-491d5480-c478-11ea-84e4-03496a492303.png)

**Comment by callmekatootie** [comment]
duplicate #27
