### ISSUE TITLE
[Bug Hunt] Buttons get hidden on clicking edit profile

### ISSUE THREAD

**Issue by HardikJ7321** [topcoder-platform/u-bahn-app#176]
Reproduction Steps:
-Open the Application https://skill-search.topcoder-dev.com/
-Take any user profile and cick edit button
-On clicking edit profile option from user profiles, the upper two buttons get hidden and only a fractional part of buttons can be viewed.
Actual Result: Button gets hidden and only a fraction of them is visible.

Expected Result: Should display the buttons properly.

Device/OS: Laptop | Windows 10 (64bit)

Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11
![hiddenbutton](https://user-images.githubusercontent.com/44543811/87248655-4d497200-c478-11ea-8108-9cd7919cbf33.png)

**Comment by callmekatootie** [comment]
duplicate #17
