### ISSUE TITLE
Group Number counts are not getting updated when we remove group from any user profile

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#177]
**Describe the bug**
Group Number counts are not getting updated when we remove group from any user profile
**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now go to groups and click on any group
3. Now remove the selected group from the profile and observe
4. the count is not decreased of removed group

**Actual Behavior**
The count is not getting decreased when user removed the group from profile

**Expected behavior**
the count must decrease when user remove the groups

**Screenshots**

[2020-07-12 19-41-38.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908631/2020-07-12.19-41-38.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
not a valid issue - group counts are static once fetched
