### ISSUE TITLE
"1 filters applied" should be change

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#178]
![image](https://user-images.githubusercontent.com/42398485/87248668-5b6ba400-c420-11ea-8e33-4c194ce13873.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Set Location=West Reneefort
4. Observe

**Actual Result:** 1 filters applied

**Expected Result:** 1 filter applied

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Resolved
