### ISSUE TITLE
[Achievements] Only refresh content in search box but can not refresh to all items when click on arrow icon

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#179]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, enter invalid in search Achievements box -> Observe the result
3. Continue to click on "Arrow" icon and observe the search box as well as items in Achievements 

**Screenshot/screencast:**
https://drive.google.com/drive/folders/11Hs97h_fs0bSsMFK69hURrv_C7sgdH8E?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Still notification messages although search box is refreshed to empty

**Expected Result:** List item also should be refreshed to ALL items after clicking on arrow icon. 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
identical to the one with locations but will take it as a valid bug since this one is under achievements

**Comment by callmekatootie** [comment]
Will be taken up in #163

**Comment by callmekatootie** [comment]
This is now resolved through #163
