### ISSUE TITLE
Doesn't toggle on/off when click on the label of the "switch" button

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#180]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Try to click on the label of the "switch" button
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1jwwGdK-pAGZYVMhZH6zoMMV3m60kd20R

**Actual Result:**  Doesn't toggle on/off when click on the label of the "switch" button

**Expected Result:** Should toggle on/off when click on the label of the "switch" button

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
not a valid bug. the label is just that - a label. not meant to toggle.
