### ISSUE TITLE
"No skills found" message is not displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#181]
![image](https://user-images.githubusercontent.com/42398485/87248703-8d7d0600-c420-11ea-8de6-8ea432a52fdc.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Set Skills=asdasdsaddasd
4. Observe

**Actual Result:** "No skills found" message is not displayed

**Expected Result:** Should display "No skills found" message

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #123
