### ISSUE TITLE
[Bug Hunt] Location Search is not fully functional

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#182]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Go to the Location search box.
3. Enter 2 letters to search
4. Now observe.

Actual results:
While entering 2 alphabets  the search doesn't list the location that it present in the list.

Expected results:
The search word should list all the location that matches the search result. 

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
<img width="685" alt="newissue" src="https://user-images.githubusercontent.com/57211549/87248727-d2ce2180-c47a-11ea-9ee1-b57f6283779f.png">

**Comment by callmekatootie** [comment]
it needs 3 or more characters to search. intentional.
