### ISSUE TITLE
Edit Profile: X filcker when edit first name last name or other column

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#183]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap edit icon from profile
3. Try to edit fields and observe 

**Actual Result:** 
X button flicker when edit profile column 

**Expected Result:** 

X button flicker when edit profile column 

**Screenshot**
[Bug1.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908635/Bug1.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0

**Comment by callmekatootie** [comment]
Did not find any flicker when editing fields in IE11. Video shared in unrelated to issue reported. Not a bug
