### ISSUE TITLE
downloaded template file is not in "XLS" format

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#184]
### Reproduction Steps ###

1. login to the app

2. click on the "Upload" tab

3. click to download the import template, observe

### Expected Result ###

The template file should be in "XLS" format.

### Actual Result ###
See screenshot, it's "XLSX" format

### Screenshot and/or screencast ###
![xl](https://user-images.githubusercontent.com/4590317/87248750-e5058b00-c48d-11ea-8af4-b14afedf1adb.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
good catch. valid bug.

**Comment by callmekatootie** [comment]
Resolved
