### ISSUE TITLE
Custom attributes doesn't have proper validations

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#185]
### Steps to Reproduce
Open https://skill-search.topcoder-dev.com/ web app
Login with tonyj /appirio123
Select topcoder as organization
Click on Edit icon on any of the listed users
Scroll down to Custom attributes section
Type in "sdksdjsk" in "isAvailable" field
Click on Save.
Notice the result.
Now Open edit profile again and type in "ksdjksjdksjks" in Gender field or in "Experience in Months" field
Click on Save.
Notice the result.

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 7 46 47 PM" src="https://user-images.githubusercontent.com/5712602/87248710-9f8a9300-c478-11ea-8e25-ed890f9474f4.png">
<img width="1440" alt="Screenshot 2020-07-12 at 7 47 56 PM" src="https://user-images.githubusercontent.com/5712602/87248715-a6b1a100-c478-11ea-9fc0-b1122acb29a9.png">

### Current Results
Custom attributes doesn't have proper validations. User is able to save anything in the fields.

### Expected Results
- isAvailable should be a radio button 
- "Experience in Months" should have number validation
- "Gender" can be an options dropdown

These fields should be validated.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
not a valid bug. the fields are free form text. no validation for now
