### ISSUE TITLE
Profiles uploaded successfully even though empty xls file uploaded

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#186]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on last tab.
3) Uplaod an empty text.xls file
Observe

Current Result :
Profiles uploaded successfully even though empty xls file uploaded

Expected result:
Should report error that empty file

Latest Firefox/Chrome
Windows 10

**Comment by coderkid19** [comment]
![15](https://user-images.githubusercontent.com/51490878/87248784-29d2f700-c479-11ea-91e6-5a2f511eef82.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87248787-2f304180-c479-11ea-905a-b5060b993ed4.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87248789-36efe600-c479-11ea-99bf-f95de9baebad.png)

**Comment by callmekatootie** [comment]
not a valid bug.

right now, we have a bare bones upload feature so I would say more like this is not in scope at the moment
