### ISSUE TITLE
Group Created from the Tab 01 is not displayed on the Groups Tab

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#187]
https://take.ms/toRoN

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Click 'Add Group' and create a group
4. Go to groups tab
5. Check the group name

**Actual Result:** Group Created from the Tab 01 is not displayed on the Groups Tab

**Expected Result:** Should display on the groups tab with the correct count

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
duplicate of #155 actually
