### ISSUE TITLE
[$10] Should highlight "Add filter" button when hover on it

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#188]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Try to scroll down page then hover on "Add filter" button
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1NNoVmk5PEPTZscgBCYEcUhdHgArV1q3-

**Actual Result:**  Doesn't highlight "Add filter" button when hover on it

**Expected Result:** Should highlight "Add filter" button when hover on it

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Expected: Provide hover effect when mouse is over the ADD FILTER button. You can use the same hover effect as seen for when mouse is over RESET (filter) button

**Comment by callmekatootie** [comment]
Resolved
