### ISSUE TITLE
[Bug Hunt] Add skills neither showing search results nor adding skills upon pressing ENTER 

### ISSUE THREAD

**Issue by HardikJ7321** [topcoder-platform/u-bahn-app#189]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon for any user 
3) Type any letter or skill
Observe

Current Result :
No search results and unable to add Skills from Edit Profile page

Expected result:
Should be able to show search results and add Skills from Edit Profile page

Latest Chrome
Windows 10

![skill](https://user-images.githubusercontent.com/44543811/87248807-538c1e00-c479-11ea-8861-70b8abbe6560.png)

**Comment by callmekatootie** [comment]
cannot reproduce
