### ISSUE TITLE
Console error when creating a group with a single char

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#190]
https://take.ms/8CTao

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Click 'Add Group' and create a group with the name "C"
4. Check the console

```
groups.js:196 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at groups.js:196
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as throw] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:29)
```

**Actual Result:** Console error when creating a group with a single char

**Expected Result:** Should not display an error

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #116
