### ISSUE TITLE
[Bug Hunt] User is stuck in a loop creating a new group/

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#191]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Go to the second tab.
3. Type in "New Group" and click on +Create button and observe.

Actual results:
"Creating" is displayed but new group is not created.

Expected results:
User should be allowed to create a new group successfully.

Browser version: Chrome: Version 83.0.4103.116

OS version : 

Screen shots:
[12.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908640/12.zip)

**Comment by callmekatootie** [comment]
duplicate #93
