### ISSUE TITLE
Highlighting All Location options

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#192]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Try To Select All Location One By One & Observe.

4. See Screencast & Screenshot:-
[8.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908638/8.mp4.zip)
![8](https://user-images.githubusercontent.com/42583358/87248872-8209f900-c479-11ea-8675-de3eb58e0160.png)

5. Current Result:- Highlighting All Location options

6. Expected Result:- Should Highlight Only One Location Which I Am Selecting

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
it's a multi select. not a valid issue
