### ISSUE TITLE
Some group names applied to profile cards are not displayed on the Group popup box or groups tab

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#193]
https://take.ms/PNEXD

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Click 'Add Group' and check the group names

**Actual Result:** Some group names applied to profile cards are not displayed on the Group popup box or groups tab

**Expected Result:** Should display all the available groups on the popup box

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #187
