### ISSUE TITLE
Edit Profile: No limit of characters in amy fields of edit profile

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#194]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap edit icon from profile
3. Try to enter any number of char or number in any fields 

**Actual Result:** 
We can able to enter any number of char in any fields of edit profile

**Expected Result:** 

Should be limited char accepted in all the fields 

**Screenshot**
[Bug7.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908644/Bug7.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0

**Comment by callmekatootie** [comment]
Will take this as duplicate of #187 - need to see why all group names are not showing up.
