### ISSUE TITLE
Profile upload shows success with negative userid

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#195]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on last tab.
3) Download Import template
4) Update that xls file with userId=-1 e
5) Import that xls file 
Observe

Current Result :
Profiles uploaded successfully with negative userid

Expected result:
Should report error when negative useId passed in import

Latest Firefox
Windows 10

**Comment by callmekatootie** [comment]
right now, we have a bare bones upload feature. no validation performed.

not a bug, for now.
