### ISSUE TITLE
[Bug Hunt] "Create Group" functionality not working

### ISSUE THREAD

**Issue by HardikJ7321** [topcoder-platform/u-bahn-app#197]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon for any user 
3) Try to press "create+" button for creating group

Current Result :
Nothing happens

Expected result:
Should show some action

Latest Chrome
Windows 10

**Comment by callmekatootie** [comment]
cannot reproduce
