### ISSUE TITLE
[Bug Hunt] Newly created group disappears on changing tabs.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#198]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Go to the second tab.
3. Give some input in the search box and click on "+create" button.
4. Scroll down to observe the group.
5. Change tabs and come back to second tab.
6. Observe.

Actual results:
The group is no longer seen.

Expected results:
The group should not be  deleted on changing tabs.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
[13.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908652/13.zip)

**Comment by callmekatootie** [comment]
duplicate #187
