### ISSUE TITLE
Group names are flicking when user select the toggle button

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#199]
https://take.ms/fnlmS

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Click 'Add Group' from a Profile Card
4. Go to OTHER GROUPS
5. Scroll the list and select deselect the toggle

**Actual Result:** Some group names applied to profile cards are not displayed on the Group popup box or groups tab

**Expected Result:** Should display on the popup box

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116

**Comment by callmekatootie** [comment]
too minor to consider a bug. I am able to reproduce but I find the glitch to be too small
