### ISSUE TITLE
Not able to search any things

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#20]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Type any things in search box but that does not have any action

**Actual Result:** 
No search action when type some char in search box

**Expected Result:** 
Should be able to do some action when try to search

**Screenshot**
[Bug1.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908531/Bug1.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0| Chrome 83.0.4103.106 | Edge 83.0.478.54 | Firefox 78.0.2

**Comment by callmekatootie** [comment]
Not a valid issue. The error message says `no org found for your user` - you were expected to login as instructed but it appears that you faced issues with it or did not follow instructions.
