### ISSUE TITLE
Number as initials for the Name is allowed

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/u-bahn-app#201]
Screenshots

![Screenshot (351)](https://user-images.githubusercontent.com/29044523/87249007-3dcb2880-c47a-11ea-814b-51318e8d33e4.png)

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to first tab
Observe the name and Initails  circle icon

Actual Result: Number is allowed

Expected Result: Numbers should not be allowed as special characters are not allowed for Initial circle value

Device/OS: Laptop | Windows 8.1 (64bit)

Browser Information: IE11,Chrome,Firefox

**Comment by callmekatootie** [comment]
not a bug. it's a free form text
