### ISSUE TITLE
Unable to add Skills from Edit Profile page

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#202]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Edit icon for any user say "Chadrick Shields"
3) Try to add skill.
4) Type "Angular" in Skill edit box. and enter
Observe

Current Result :
Unable to add Skills from Edit Profile page

Expected result:
Should be able add Skills from Edit Profile page

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![16](https://user-images.githubusercontent.com/51490878/87249084-b6ca8000-c47a-11ea-951c-7ed901531a85.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87249088-b9c57080-c47a-11ea-9e9a-725d8a98a9d0.png)

**Comment by callmekatootie** [comment]
cannot reproduce
