### ISSUE TITLE
User profile is showing in the a group (ex. Test Group), but group is not tagged to that profile

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#203]
**Describe the bug**
User profile is showing in the a group (ex. Test Group), but group is not tagged to that profile

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now go to test group and observe the first profile
3. there is no test group tagged to that profile

**Actual Behavior**
User profile is showing in a group, in which it is not tagged

**Expected behavior**
The profile must show only the group in which is tagged

**Screenshots**
[2020-07-12 19-41-38 (2).zip](https://github.com/topcoder-platform/u-bahn-app/files/4908660/2020-07-12.19-41-38.2.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment]
we use external api for this and display only what the api gives us. Not the app's issue basically.
