### ISSUE TITLE
Ok Message Should Not Be In Left Of Screen

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#204]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Logout Near TonyJ (Topcoder)

4. Then See Message OK & Observe.

5. See Screenshot:-
![9](https://user-images.githubusercontent.com/42583358/87249062-871b7800-c47a-11ea-9df5-dc2222f0f165.png)

6. Current Result:- Ok Message In Left Of Screen.

7. Expected Result:- Ok Message Should Not Be In Left Of Screen. It Should Be In Middle Of Screen.

8. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

9. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #63
