### ISSUE TITLE
[Common] Reset button won't clear the textbox values

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#205]
https://take.ms/hGjoC

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 
3. Add some filters and enter invalid text to the search fields
4. Click Reset

**Actual Result:** Reset button won't clear the textbox values

**Expected Result:** Should clear the textbox values also

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
textbox values are meant to select filters. Reset will only clear the filters set - it does not deal with the search text.
