### ISSUE TITLE
[common] should set max allowed chars for search box

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#206]
### Reproduction Steps ###

1. login to the app

2. try to enter long string in the search box

3. observe

### Expected Result ###

Should set max allowed chars for search box.

### Actual Result ###
See screenshot, not set

### Screenshot and/or screencast ###

![sc](https://user-images.githubusercontent.com/4590317/87249083-a8d32a00-c48f-11ea-8998-3add3fd8e0f0.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
no such expectation for now. not a valid issue
