### ISSUE TITLE
Newly created groups can't be searched in the "Add to Group" modal dialog

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#207]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on "+" icon in GROUPS of a User Card
5. Search for a group called "ABCDE"
6. if no group exists with the same name click on Create.
7. Group created successfully will be shown in alert
8. Now Click on "+" icon again, and search for same group name
9. Notice the search results

### Screenshots or Screen Capture
[search_group.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908656/search_group.mov.zip)

<img width="1440" alt="Screenshot 2020-07-12 at 8 02 34 PM" src="https://user-images.githubusercontent.com/5712602/87249072-a4e8dd00-c47a-11ea-938b-6ce91db167b5.png">

### Current Results
Newly created groups can't be searched in the "Add to Group" modal dialog

### Expected Results
Search results should show newly created groups.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
cannot reproduce

**Comment by rprakash20** [comment]
@callmekatootie I can still reproduce this issue, please check the video.
[group_issue.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4929869/group_issue.mov.zip)

**Comment by rprakash20** [comment]
@callmekatootie please check this. thanks.

**Comment by callmekatootie** [comment]
Gotcha. Duplicate of #155
