### ISSUE TITLE
Reset button should remain in disabled state while 0 filters applied 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#208]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Click on reset button and again click on reset button 
Observe

**Actual Result:**  Once cleared filters reset button is still enable and message "Loading users. This can take some time. Please wait..." is seen

**Expected Result:**  When filters are cleared reset button should remain in disabled state 

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 
**Bug video** https://drive.google.com/file/d/1qUcM3PU_m17FSPNeylHSNKp-GpjRTQew/view?usp=sharing

**Comment by bhattashubham** [comment]
![Device_info](https://user-images.githubusercontent.com/48902251/87249107-e084a680-c47c-11ea-9951-04243cd3c2ce.png)

**Comment by callmekatootie** [comment]
will take it as a valid bug. if no filters are applied, then RESET should be disabled

**Comment by wdprice** [comment]
Agree this is a bug, but it's so minor that I don't want to give it any priority right now.

**Comment by callmekatootie** [comment]
After discussion on Slack - Will not be fixed. Closing
