### ISSUE TITLE
Can't focus on all items by using tab key

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#209]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Try to focus on all items by using tab key
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1-pgxCPduzdbxdX8agaKc_x2HG_5IPmlg

**Actual Result:**  Can't focus on all items by using tab key

**Expected Result:** Should focus on all items by using tab key

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
@wdprice Should we support accessibility?

**Comment by callmekatootie** [comment]
Checked with PM - this would be a feature request for now and not a bug.
