### ISSUE TITLE
[$10] Nothing happens on clickingon + sign to create group

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#21]
Steps to reproduce
• 1. Go to application-https://crm-benefits-prototype.herokuapp.com/pharmacy
• 2. to create group nother happens 

Current results
-to create group nother happens if user clicks on + sign

Expected results

user should be able to create new group

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots

![Screen Shot 2020-07-12 at 6 38 03 PM](https://user-images.githubusercontent.com/57220292/87247072-1a4eb080-c46f-11ea-8c7c-fb95b3f7cc43.png)

**Comment by akultalwar89** [comment]
please update 1st step website to https://skill-search.topcoder-dev.com/

**Comment by callmekatootie** [comment]
you need to enter name of group before you click on create. but will take it as a bug - we can show an alert box here

**Comment by callmekatootie** [comment]
Expected: Use browser's `alert()` feature to alert the user to enter a group name

**Comment by callmekatootie** [comment]
Resolved
