### ISSUE TITLE
Network request when same group selected again

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#210]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Click on Groups tab button
    3. Let it load
    4. Click on "Avengers" group button
    5. let it load
    6. Click again on "Avengers" button

## Screenshots/Video
![Screenshot from 2020-07-12 20-05-02](https://user-images.githubusercontent.com/32861951/87249146-fdb87580-c47a-11ea-9e49-e68f45bd5122.png)

##  Actual Result(s)

Reloads again, even though same group was already selected

##  Expected Result(s)

Should not reload if same selected

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
duplicate #165
