### ISSUE TITLE
says loading users but after loading message display profiles

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#211]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. clicking on any filter says loading users but after loading message display profiles

Current results
•clicking on any filter says loading users but after loading message display profiles

Expected results
It should be either Loading profiles ,or user profiles. - inconsistancy currently

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
[Screen Recording 2020-07-12 at 8.04.41 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908665/Screen.Recording.2020-07-12.at.8.04.41.PM.mov.zip)

**Comment by callmekatootie** [comment]
will take it as a bug. need to update the loading text during search

**Comment by wdprice** [comment]
Lets have the text during search say: "Updating profile list."

**Comment by callmekatootie** [comment]
Resolved
