### ISSUE TITLE
No templates for CSV File

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#212]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Go to Drag Profile Data Tab

## Expected Result
There is a template for csv files

## Actual Result
No template for csv files

## Screenshot
![](https://www.dropbox.com/s/bb7vb1ng8ffo2mi/csv.png?raw=1)

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
there's no indicate that there is a template for CSV - the drop area / upload supports csv files is all that it says

**Comment by Citra-citoru** [comment]
Hi, 
it said **Supports XLS or CSV file**. If the user wants to upload the csv file, how can she/he do it? edit the xls template one by one to csv format? isn't it better if the system provide template for csv file?

**Comment by callmekatootie** [comment]
You are probably right. However, it would be more of a feature and not a bug.
