### ISSUE TITLE
Creating a group with existing name freezes the UI, 409 status code is seen in the console logs

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#213]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on "+" icon in GROUPS of a User Card
5. Search for a group called "ABCDE"
6. if no group exists with the same name click on Create
7. Group created successfully will be shown in alert
8. Now Click on "+" icon again, and search for same group name
9. Enable browser inspector
10. Click Create 
11. Notice the result and check the logs in console tab of inspector

### Screenshots or Screen Capture

<img width="1440" alt="Screenshot 2020-07-12 at 7 55 21 PM" src="https://user-images.githubusercontent.com/5712602/87249183-26d90600-c47b-11ea-84d8-84bf0e833dcf.png">

<img width="1440" alt="Screenshot 2020-07-12 at 7 57 08 PM" src="https://user-images.githubusercontent.com/5712602/87249190-2fc9d780-c47b-11ea-8ab2-a757415ab234.png">

[create_duplicate_group.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908666/create_duplicate_group.mov.zip)

### Current Results
Creating a group with existing name freezes the UI, 409 status code is seen in the console logs

### Expected Results
UI should throw an error saying a group with the same name already exists.

### Console Logs
```
xhr.js:178 POST https://api.topcoder-dev.com/v5/groups 409
(anonymous) @ 2.f0003de4.chunk.js:2
e.exports @ 2.f0003de4.chunk.js:2
e.exports @ 2.f0003de4.chunk.js:2
Promise.then (async)
c.request @ 2.f0003de4.chunk.js:2
r.forEach.c.<computed> @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ main.36d99be9.chunk.js:1
c @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
forEach.e.<computed> @ 2.f0003de4.chunk.js:2
r @ 2.f0003de4.chunk.js:2
a @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
b @ main.36d99be9.chunk.js:1
(anonymous) @ main.36d99be9.chunk.js:1
c @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
forEach.e.<computed> @ 2.f0003de4.chunk.js:2
r @ 2.f0003de4.chunk.js:2
a @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ main.36d99be9.chunk.js:1
a @ 2.f0003de4.chunk.js:2
d @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
y @ 2.f0003de4.chunk.js:2
ut @ 2.f0003de4.chunk.js:2
ot @ 2.f0003de4.chunk.js:2
at @ 2.f0003de4.chunk.js:2
dt @ 2.f0003de4.chunk.js:2
U @ 2.f0003de4.chunk.js:2
W @ 2.f0003de4.chunk.js:2
$t @ 2.f0003de4.chunk.js:2
Jt @ 2.f0003de4.chunk.js:2
t.unstable_runWithPriority @ 2.f0003de4.chunk.js:2
Vo @ 2.f0003de4.chunk.js:2
L @ 2.f0003de4.chunk.js:2
Ht @ 2.f0003de4.chunk.js:2
Show 10 more frames
groups.js:192 Error: Request failed with status code 409
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)
groups.js:196 Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at groups.js:196
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as throw] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:29)
```
### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #116
