### ISSUE TITLE
If we remove any group tagging from any profile but when we come back, so it is again available there

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#214]
**Describe the bug**
If we remove any group tagging from any profile but when we come back, so it is again available there

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now go to groups
3.Click on test side bar group
4. Now removing the test side bar tagging from the profiles
4. Go back another tab like home and come back
5. observe the tagging is back in test side bar group

**Actual Behavior**
After removing the group tagging but Group tagging are coming back when we are switching the tabs

**Expected behavior**
Group tags must not come back when we switch tabs

**Screenshots**
[2020-07-12 19-41-38.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908669/2020-07-12.19-41-38.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment]
cannot reproduce
