### ISSUE TITLE
[Common] Removing the current selected group won't remove the profile card from the list

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#215]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Select a group 'Reading Club', Count 3
4. Select a profile card and remove the "Reading Club" group from it
5. Observe
6. Click on the "Reading Club" group name again and check the count still 3

**Actual Result:** Removing the current selected group won't remove the profile card from the list

**Expected Result:** Should remove the profile card

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/ppFbY

**Comment by callmekatootie** [comment]
the profiles are static and thus when you remove a group from a profile, it does not disappear immediately.
