### ISSUE TITLE
When off toggles for unavailable and applied filter for available so member profile still showing

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#216]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and apply filter for available
3. Now try to off toggle to switch to unavailable
4. Still can member profile showing

**Actual Result:** 
When off toggles for unavailable and applied filter for available so member profile still showing

**Expected Result:** 
When off toggles for unavailable and applied filter for available so member profile show updated/hide

**Screenshot**
[Bug8.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908675/Bug8.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** Chrome 83.0.4103.106

**Comment by callmekatootie** [comment]
you need to wait for the available / unavailable text to be displayed properly, which confirms that the toggle was saved. there's a slight color change indicating the changes are being saved.

most likely in your case the changes were not saved and thus the user showed up. cannot reproduce right now.
