### ISSUE TITLE
Missing "Skills" list

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#217]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, Observe "Skills" option

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1YqL2LeablLZcwzZ4Vuxc4t7gSP514lOj?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Missing "Skills" list in order to recommend for searching 

**Expected Result:** Should show "Skills" list in order to recommend for searching 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
cannot reproduce

**Comment by HongHT** [comment]
Hi @callmekatootie - I can still reproduce it.
https://drive.google.com/drive/folders/1RN-CMMxamg93354J4Y42lB-_f45trlb1
Please consider again! Thank you.

**Comment by callmekatootie** [comment]
You need to type in the filter to view the suggestions. See attached video:

[217.zip](https://github.com/topcoder-platform/u-bahn-app/files/4939404/217.zip)

The filters for Skills are not static but dynamic - like the ones for custom attributes. Only difference is that we use a third party api here to give suggestions for the skills, whereas for custom attributes, we use our own api (which will return values that currently exist on any of the users)
