### ISSUE TITLE
[Bug Hunt] Newly created group is not seen on edit profile pop up.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#218]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Go to the second tab.
3. Give some input in the search box and click on "+create" button.
4. Scroll down to observe the newly created group.
5. Now click on any of the previously available groups.
6. Click on edit icon of the first profile.
7. CLick on + icon on groups section and observe.

Actual results:
The group is no longer seen.

Expected results:
The group should be displayed and selected successfully.

Browser version: Chrome: Version 83.0.4103.116

[14.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908678/14.zip)

Screen shots:

**Comment by callmekatootie** [comment]
it is an auto suggest feature - you need to type and select skills to filter from
