### ISSUE TITLE
[Bug Hunt] Newly created group is not seen on second tab of the application.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#219]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on + icon under the groups section.
3. Enter some input and click on +create option.
4. Scroll down to the group and toggle on and click on Done.
5. Now navigate to second tab and search same input in step 3 and observe.

Actual results:
No result is shown by the application.

Expected results:
Newly added group should be shown.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
[15.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908679/15.zip)

**Comment by callmekatootie** [comment]
duplicate #187
