### ISSUE TITLE
"OTHER GROUPS" title is not aligned properly

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#22]
![image](https://user-images.githubusercontent.com/42398485/87247074-2018a780-c417-11ea-82f8-7bc93d4adb3c.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the first tab
3. Click 'Add to Group'
4. Check the title "OTHER GROUPS"

**Actual Result:** "OTHER GROUPS" title is not aligned properly

**Expected Result:** Should center aligned

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a valid bug. it is left aligned - just like MY GROUPS above

**Comment by codejamtc** [comment]
@callmekatootie here I meant Vertically center aligned with in the gray container

**Comment by callmekatootie** [comment]
Gotcha... It is not meant to be vertically centered based on what I see.
