### ISSUE TITLE
[Bug Hunt] Save button enabled without making any changes.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#220]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on edit icon on the profile.
3. Click on blue "Save" button an observe.

Actual results:
Save button is enabled and clickable.

Expected results:
User should not be allowed to click on "Save" button without making any changes.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![16](https://user-images.githubusercontent.com/57211549/87249345-4faeca80-c47e-11ea-8a10-78b1ba8a8027.png)

**Comment by callmekatootie** [comment]
Not a bug. It's just another way to close the modal without any changes made.
