### ISSUE TITLE
[Common] Group created removes when user switches to another tab and come back to Group

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#221]
https://take.ms/dzF0pO

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Create a group
4. Go to Tab 01
5. Come back to Group Tab and observe

**Actual Result:** Group created removes when user switches to another tab and come back to Group

**Expected Result:** Should display the created group

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #187
