### ISSUE TITLE
Searching for a asterick "*" works in the "Search Talent or keywords" search box and returns all the results

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#222]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Type "*" in the "Search Talent or keywords" search box 
5. Press Enter
6. Notice the search results

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 8 12 17 PM" src="https://user-images.githubusercontent.com/5712602/87249348-3b69ce00-c47c-11ea-9ae1-fcfb135e8358.png">

[asterick_search.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908683/asterick_search.mov.zip)

### Current Results
Searching for a asterick "*" works in the "Search Talent or keywords" search box and returns all the results

### Expected Results
Search results should work with proper characters only.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
Not a bug. It's a free form text search.
