### ISSUE TITLE
[Bug Hunt] Availability filter shown green even after reset.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#223]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.

login credential:
tonyj / appirio123 
2. Click on "Unavailable" and click on "Reset" button on top/
3. Observe.

Actual results:
0 filters applied is shown but unavailable is still ticked green.

Expected results:
The green button should be removed too.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![17](https://user-images.githubusercontent.com/57211549/87249392-94d2fc80-c47e-11ea-9a2d-75c78ef4ce5b.png)

**Comment by callmekatootie** [comment]
duplicate #136
