### ISSUE TITLE
"v" minimise button on left, click doesnot work

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#224]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Try clicking just above "v" button (Cursor becomes pointer/hand here)

## Screenshots/Video
![Screenshot from 2020-07-12 20-15-34](https://user-images.githubusercontent.com/32861951/87249387-77049800-c47c-11ea-827b-327718cae516.png)

Div class "collapsible_collapsibleChevronContainer___GCJD" has cursor type as pointer

![Screenshot from 2020-07-12 20-16-03](https://user-images.githubusercontent.com/32861951/87249402-871c7780-c47c-11ea-9b80-6fcbb299e6fd.png)

But on click event is in the div (class "icons_chevronDownG__27K1A") inside it

##  Actual Result(s)

Click doesnt work

##  Expected Result(s)

Click should work

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
duplicate #151
