### ISSUE TITLE
When user select a group from the bottom, user needs to scroll the page up always

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#225]
https://take.ms/fr4kP

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Scroll down and select a group

**Actual Result:** When user select a group from the bottom, user needs to scroll the page up always

**Expected Result:** Should focus the page on the top content when user selects a group

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #75
