### ISSUE TITLE
"Search talent or keywords" placeholder should be visible completely in the search box

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#226]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Notice the search box available at the top of the page
5. Notice it's placeholder

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 8 16 21 PM" src="https://user-images.githubusercontent.com/5712602/87249447-c34fd800-c47c-11ea-9f6c-241d88b5ee22.png">

### Current Results
Placeholder text is not visible completely

### Expected Results
Placeholder text should be visible completely, otherwise it beats the purpose of a placeholder itself.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #24
