### ISSUE TITLE
[Bug Hunt] Reset button enabled without applying any filters.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#227]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on "Reset" button without applying any filters.
3. Observe.

Actual results:
Reset button is enabled and clickable.

Expected results:
Reset button should be disabled since no filters is applied.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![18](https://user-images.githubusercontent.com/57211549/87249467-00b56500-c47f-11ea-8e6a-572b4a471687.png)

**Comment by callmekatootie** [comment]
duplicate #208
