### ISSUE TITLE
Initials in user avatar not in center

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#228]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Let user list load
    3. See the logo/avatar near any user (Initials inside the circle)

## Screenshots/Video
![Screenshot from 2020-07-12 20-20-39](https://user-images.githubusercontent.com/32861951/87249525-2b062300-c47d-11ea-917f-43b787b7d253.png)

##  Actual Result(s)

Text inside circle not in center

##  Expected Result(s)

Text inside circle should be in center

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
cannot reproduce

**Comment by g1tman** [comment]
@callmekatootie opened the website again, still looks same for firefox.

PS: On chrome, it is in the center.

**Comment by callmekatootie** [comment]
Yep. I verified on firefox too:

![image](https://user-images.githubusercontent.com/2317133/87563701-293a9a80-c6dd-11ea-8f91-54cf4a7047ef.png)

**Comment by g1tman** [comment]
@callmekatootie 

Browser: "Firefox 78.0.1 (64-bit)" Incognito Window, with all extensions disabled, firefox tracking protections disabled.

![Screenshot from 2020-07-15 21-32-25](https://user-images.githubusercontent.com/32861951/87568229-f398b000-c6e2-11ea-8fe5-d60fea0c22ff.png)


Layout of Initials text

![Screenshot from 2020-07-15 21-43-10](https://user-images.githubusercontent.com/32861951/87569233-6e15ff80-c6e4-11ea-8eac-c1f9e6f406a9.png)


Computed properties of Initials text (class "profileCard_avatarText__*") 
```

border-bottom-color: rgb(255, 255, 255);
border-bottom-style: none;
border-bottom-width: 0px;
border-image-outset: 0;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(255, 255, 255);
border-left-style: none;
border-left-width: 0px;
border-right-color: rgb(255, 255, 255);
border-right-style: none;
border-right-width: 0px;
border-top-color: rgb(255, 255, 255);
border-top-style: none;
border-top-width: 0px;
color: rgb(255, 255, 255);
font-family: Helvetica;
font-feature-settings: normal;
font-kerning: auto;
font-language-override: normal;
font-optical-sizing: auto;
font-size: 20px;

main.e6949c66.chunk.css:1
.profileCard_avatarText__1BerS
20px

main.e6949c66.chunk.css:1
body
inherit

main.e6949c66.chunk.css:1
div
inherit

main.e6949c66.chunk.css:1
html
inherit
font-size-adjust: none;
font-stretch: 100%;
font-style: normal;
font-variant: normal;
font-variant-alternates: normal;
font-variant-caps: normal;
font-variant-east-asian: normal;
font-variant-ligatures: normal;
font-variant-numeric: normal;
font-variant-position: normal;
font-variation-settings: normal;
font-weight: 400;
line-height: 20px;
margin-bottom: 0px;
margin-left: 0px;
margin-right: 0px;
margin-top: 0px;
padding-bottom: 0px;
padding-left: 0px;
padding-right: 0px;
padding-top: 0px;
vertical-align: baseline;

```

**Comment by callmekatootie** [comment]
I am afraid my decision stands

**Comment by g1tman** [comment]
@callmekatootie I did some digging on the issue. It turns out that it is an issue of the font that is being used.

**"Helvetica" font doesnt render properly (renders differently than Chrome) on Linux Firefox**
Here - https://stackoverflow.com/questions/45985699/how-to-fix-mis-aligned-characters-in-linux-osx-firefox-when-using-helvetica you can find the reason why this font causes issues.


> 
> Never use Helvetica in CSS if you want to have Linux users.
> 
> On Windows and OSX Helvetica maps to modern font files (under proprietary licensing, so they are banned from Linux systems unless you buy them separately and install them yourself. No one bothers.)
> 
> On Linux Helvetica maps to very old font files which are only kept around because Helvetica is one of the original built-in Postscript font, so its presence is required to print some documents (print ie render on a 300dpi+ medium, rendering on a 96dpi screen is something else entirely those fonts were never designed for).
> 
> Also the encoding coverage expected from Postscript fonts is quite small, if you force a Linux system to render modern non ASCII-only text using Helvetica it will have to take the missing glyphs from some over font, and those glyphs won't match perfectly the proportions and placement of the rest of the text.
> 
> Linux systems have many nice modern fonts with large coverage, Helvetica is just not part of them.
>

**Comment by callmekatootie** [comment]
Thank you for going through the details. But that does not change the decision here.
