### ISSUE TITLE
search on skill doesnt work

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#23]
Steps to reproduce
• 1. Go to application-https://crm-benefits-prototype.herokuapp.com/pharmacy
• 2. search doesnt work on edit and find a skill

Current results
search doesnt work on edit and find a skill

Expected results

It should search for a skill

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 6 41 26 PM](https://user-images.githubusercontent.com/57220292/87247108-597d0180-c46f-11ea-8992-11164158e1ed.png)

**Comment by akultalwar89** [comment]
please update 1st step website link to - https://skill-search.topcoder-dev.com/

**Comment by callmekatootie** [comment]
cannot reproduce

![image](https://user-images.githubusercontent.com/2317133/87507866-c8cf3d00-c68b-11ea-806d-f82342fcc675.png)
