### ISSUE TITLE
Error occurred when switched to Org as Cool Party 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#230]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 
2) Select Org as Cool Party
Observe

Current Result :
Error occurred when switched to Org as Cool Party 

Expected result:
Error should not appear when switched to Org as Cool Party 

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![17](https://user-images.githubusercontent.com/51490878/87249580-905a1400-c47d-11ea-9bf7-1d175bd1a921.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87249582-93550480-c47d-11ea-8bc3-b345540dd6d1.png)

**Comment by callmekatootie** [comment]
not a bug. you were instructed to use Topcoder as org
