### ISSUE TITLE
Can not add "Skills" in "Edit Profile"

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#231]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, Click on "Edit" icon inside any profiles 
3. Try to enter some skills inside "Enter skill to add" box 
4. Click on "Enter" key as well as Click on "Save" button 
5. Click on "Edit" icon again then observe the result.

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1sYL9KLjoVQNWnP6oCp8duwOJlWYEM_Uo?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Can not add "Skills" in "Edit Profile"

**Expected Result:** Should add skill when "enter skill to add" box 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
cannot reproduce

**Comment by HongHT** [comment]
Hi @callmekatootie , This has a problem. I am confused about https://github.com/topcoder-platform/u-bahn-app/issues/243 because your comment: "need to update hint text to search skill to add" then we don't where to create skills.  If it is search function, when we enter some characters, it should show "no skills found" at here. But currently,  no any changes when enter some characters in here.

**Comment by callmekatootie** [comment]
See attached video - for the search text that you provided, you should have got results as seen in the video

[231.zip](https://github.com/topcoder-platform/u-bahn-app/files/4939384/231.zip)

If there are not results, then yes, it should say no results found - intend to take that up in #123 

In your video, you did not get any value for Java but you should - which is what I cannot reproduce - I get values for Java
