### ISSUE TITLE
Search: Double x appear when try to search content

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#232]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and type some content on search box
3. Observe double X appear 

**Actual Result:** 
Double X button in search box

**Expected Result:** 
Should not more than one X button in search box

**Screenshot**
![image](https://user-images.githubusercontent.com/23450398/87249577-8c2df680-c47d-11ea-9d9b-968edbf09b3b.png)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0

**Comment by callmekatootie** [comment]
duplicate #173
