### ISSUE TITLE
clicking on Group multiple times shows loading - nothing happens

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#233]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. clicking on Group multiple times shows loading - nothing happens

Current results
clicking on Group multiple times shows loading - nothing happens

Expected results
it should not show loading - should load the users ,

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots - 
[Screen Recording 2020-07-12 at 8.22.29 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908696/Screen.Recording.2020-07-12.at.8.22.29.PM.mov.zip)
![Screen Shot 2020-07-12 at 8 23 43 PM](https://user-images.githubusercontent.com/57220292/87249587-9b14a900-c47d-11ea-8e35-d21fdf469d7c.png)

**Comment by callmekatootie** [comment]
cannot reproduce

**Comment by akultalwar89** [comment]
@callmekatootie  - I can still reproduce it - If you click on the group 3 times then the profile will say loading and doesnt load

**Comment by akultalwar89** [comment]
@callmekatootie - attaching video
[Screen Recording 2020-07-15 at 8.54.58 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4926200/Screen.Recording.2020-07-15.at.8.54.58.PM.mov.zip)

**Comment by akultalwar89** [comment]
@callmekatootie  - Just wanted to check on this :) 
attached video for reference

**Comment by callmekatootie** [comment]
Thank you. Was able to reproduce.

**Comment by callmekatootie** [comment]
Clicking the active group multiple times is now disabled. This issue thus cannot be reproduced anymore and is thus being closed.
