### ISSUE TITLE
Total Numbers Of Profile Is Mismatching

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#234]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click Below Availability & Select Available Its Showing 4 Profiles Now Uncheck Available.

4. Now Select Availability As Unavailable Its Showing 6 Profiles. Now Check Both Available & Unavailable Its Showing 11 Profiles. But If We Add Both Available & Unavailable It Will Be Only 10 Profiles.

5. See Screencast & Screenshot:-
[10.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908688/10.mp4.zip)
![9A](https://user-images.githubusercontent.com/42583358/87249558-69034700-c47d-11ea-97cd-48dadaf9d089.png)
![9U](https://user-images.githubusercontent.com/42583358/87249563-715b8200-c47d-11ea-824b-02a8c7076be0.png)
![10](https://user-images.githubusercontent.com/42583358/87249566-79b3bd00-c47d-11ea-8574-b4b424dbd4aa.png)

6. Current Result:- Total Numbers Of Profile Is Mismatching

7. Expected Result:- Total Number Of Profile Should Match After Adding Available & Unavailable.

8. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

9. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
cannot reproduce
