### ISSUE TITLE
able to scroll the main page when 'Add Filters' modal is open, though the same doesn't happen when other dialog 'Add to Group' is open

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#236]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on "Add Filter" button 
5. When the modal is open, scroll the main page
6. Notice the result

### Screenshots or Screen Capture

[scroll_issue.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908700/scroll_issue.mov.zip)

### Current Results
able to scroll the main page when 'Add Filters' modal is open, though the same doesn't happen when other dialogs like 'Edit Profile' or 'Add to Group' are open

### Expected Results
Behavior should be consistent and when 'Add Filters' modal is open, main page content should not be scrollable

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #144
