### ISSUE TITLE
Error for user search

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#237]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. In search field on top enter `Jonathan\"'   `
    3. See network response

## Screenshots/Video
![Screenshot from 2020-07-12 20-24-55](https://user-images.githubusercontent.com/32861951/87249677-02325d80-c47e-11ea-8583-d86c18c9fa2a.png)

##  Actual Result(s)

Response message

`
[query_shard_exception] Failed to parse query [\*Jonathan"'   \*], with { index_uuid="PckDhAVXQAehEf07e41Rtg" & index="skill" }
`

##  Expected Result(s)

No error

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
Got empty array. No error. Tested in Firefox.

**Comment by g1tman** [comment]
@callmekatootie I am not sure why that string is no longer working. But slightly modifying the string to
`Jonathan\""`
gives the same error now.

![Screenshot from 2020-07-18 00-15-41](https://user-images.githubusercontent.com/32861951/87820517-d81cd900-c88b-11ea-9e2b-37a20199587e.png)

**Comment by callmekatootie** [comment]
Thank you - am able to reproduce now. Will take it as a bug

**Comment by callmekatootie** [comment]
PAID - http://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30134624
