### ISSUE TITLE
UI should be proper on group button on the bottom of group selection

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#239]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. user can click on the button while cant see the group name on the bottom of group selection

Current results
user can click on the button while cant see the group name- 

Expected results
UI should be proper - button shouldnt be visible or clickable and should only see 3 options in a screen while at the top of the page or scrolling to bottom. 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
![Screen Shot 2020-07-12 at 8 26 28 PM](https://user-images.githubusercontent.com/57220292/87249696-33129280-c47e-11ea-9f90-33813e888bc2.png)

**Comment by callmekatootie** [comment]
not a valid bug

**Comment by akultalwar89** [comment]
@callmekatootie  - can it be considered as UI issue as it doesnt fall under the frame of 3 options. user can select the 4th option without seeing it.

**Comment by callmekatootie** [comment]
I am afraid my decision stands
