### ISSUE TITLE
Able to add unlimited numbers in "Experience (in months)" in "Edit Profile"

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#241]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on Edit icon of user "Tony a"
3) In CUSTOM ATTRIBUTES -> Experience (in months) try to add unlimited numbers.
4) Click on Save
Observe

Current Result :
Able to add unlimited numbers in "Experience (in months)" in "Edit Profile"

Expected result:
There should be limit in numbers in "Experience (in months)" in "Edit Profile"

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![18](https://user-images.githubusercontent.com/51490878/87249725-71a84d00-c47e-11ea-9fad-d2e5a1cc0c3a.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87249728-73721080-c47e-11ea-8827-4709c4f7dab5.png)

**Comment by callmekatootie** [comment]
not a valid bug. no validation carried out - it is a free form text.
