### ISSUE TITLE
[Bug Hunt] Alignment of Logout button is not proper

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#242]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Click on profile icon
![image](https://user-images.githubusercontent.com/68163678/87249688-19714b00-c47e-11ea-958e-22ed055bc529.png)
3. Verify alignment of Logout button.
**Actual result:**
Alignment for Logout button is not proper
**Expected result:**
Alignment for Logout button should be proper
**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment]
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
not a valid bug. intentionally right alighed
