### ISSUE TITLE
Icon show incorrectly with content "Enter skill to add"

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#243]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, Click on "Edit" icon inside any profiles 
3. Observe icon inside "Enter skill to add" box

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1EE2Sucp9WJ7ltizOR03tn2EhHUlh459X?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Icon is search icon although textbox is "Enter skill to add" 

**Expected Result:** Should show properly icon for "Enter skill to add" box instead of Search icon 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
will take as a bug - need to update hint text to `search skill to add`

**Comment by wdprice** [comment]
I like your solution @callmekatootie

**Comment by callmekatootie** [comment]
Resolved
