### ISSUE TITLE
Switching over the tabs is resetting the collapsed drop-down 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#244]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Click  on collapse drop down Location and Availability 
Observe

**Actual Result:**  Switching over the tabs is resetting dropdown to expand 

**Expected Result:** Application should not reset the dropdown while switched tabs 

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 

Bug video: https://drive.google.com/file/d/1llG1KCC2Z-n67ZXe7O3JBHK7iJfVSj0u/view?usp=sharing

**Comment by bhattashubham** [comment]
![Device_info](https://user-images.githubusercontent.com/48902251/87249788-e3819600-c480-11ea-9eeb-d0957d59ab7a.png)

**Comment by callmekatootie** [comment]
not a bug
