### ISSUE TITLE
Edit Profile -> CUSTOM ATTRIBUTES -> "Experience (in months)" field accepts character

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#246]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon of user "Tony a"
3) In CUSTOM ATTRIBUTES -> Experience (in months) try to add character
4) Click on Save
Observe

Current Result :
Edit Profile -> CUSTOM ATTRIBUTES -> "Experience (in months)" field accepts character

Expected result:
Edit Profile -> CUSTOM ATTRIBUTES -> "Experience (in months)" field should not accept character

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![19](https://user-images.githubusercontent.com/51490878/87249811-ee3b2b80-c47e-11ea-8f12-9b43483f6beb.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87249818-f1361c00-c47e-11ea-9444-b2ce7a633629.png)

**Comment by callmekatootie** [comment]
not a valid bug. custom attributes are free form fields
