### ISSUE TITLE
[Bug Hunt] Add filters done button enabled without making any changes.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#248]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123 
2. Click on "Add FIlter" button.
3. Click on "Done" without making any changes and observe.

Actual results:
Done button is enabled and clickable.

Expected results:
Done button should be disabled.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![19](https://user-images.githubusercontent.com/57211549/87249799-fbf1b080-c480-11ea-80b1-8f70723c7ce5.png)

**Comment by callmekatootie** [comment]
not a bug. DONE here is also used to close the modal, along with CANCEL
