### ISSUE TITLE
Gender: Two 'Male" options displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#249]
![image](https://user-images.githubusercontent.com/42398485/87249822-fff0e480-c426-11ea-9bfa-ba1c2ddc22c6.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Click "Add Filters" and Turn ON all the filters
4. Click on Gender dropdown and type 'a'

**Actual Result:** Two 'Male" options displayed

**Expected Result:** Should display only one

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
Other filters too

![image](https://user-images.githubusercontent.com/42398485/87253806-96cb9a00-c443-11ea-9fbd-aa57a15e41e8.png)

**Comment by callmekatootie** [comment]
cannot reproduce

![image](https://user-images.githubusercontent.com/2317133/87558401-b0d0db00-c6d6-11ea-9545-94ebe0094a5b.png)
