### ISSUE TITLE
[Bug Hunt] User navigated to first tab on clicking the "x" icon on top search bar.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#250]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
login credential:
tonyj / appirio123
2. Navigate to the second tab and then to the third tab.
3. CLick on the "x" icon on the top search bar and observe.

Actual results:
User is navigated back to the first tab.

Expected results:
User should stay on the current page, only the written text on the search bar should be removed.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
[20.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908710/20.zip)

**Comment by callmekatootie** [comment]
the search bar is for the first tab and thus, on clearing the search, it takes you to the first tab to show the search results after clearing
