### ISSUE TITLE
Bigger group name coming out of box in edit screen

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#251]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. click on edit button - Bigger group name coming out of box in edit screen

Current results
Bigger group name coming out of box in edit screen

Expected results
bigger group name shouldnt come out of the box.

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
![Screen Shot 2020-07-12 at 8 33 10 PM](https://user-images.githubusercontent.com/57220292/87249825-07dc7300-c47f-11ea-87a8-1d9bb043dee8.png)

**Comment by callmekatootie** [comment]
duplicate #46
