### ISSUE TITLE
[Bug Hunt]Alignment for Sort By fields is not proper

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#252]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/
2.Click on Sort By and verify 3 fields by which you can sort
![image](https://user-images.githubusercontent.com/68163678/87249821-fe530b00-c47e-11ea-9b90-f7941094ecd0.png)

3. Verify alignment for these felds is not proper
Actual result:
Alignment for Sort By field is not proper
Expected result:
Alignment for Sort By field should be proper
Device/Browser/OS:
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment]
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
intentionally right aligned
