### ISSUE TITLE
Adding a new CUSTOM ATTRIBUTES won't display on the filters

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#253]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01
3. Click "Add Filters" and Turn ON all the filters
4. Click EDIT from a profile and add new entries to the CUSTOM ATTRIBUTES
5. Click Save
6. Expand the Filters and check Like company, location, title etc

**Actual Result:** Adding a new CUSTOM ATTRIBUTES won't display on the filters #253

**Expected Result:** Should display newly added CUSTOM ATTRIBUTES

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
did not understand the instructions
