### ISSUE TITLE
Able to add Junk character in Edit Profile -> CUSTOM ATTRIBUTES -> Gender field

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#254]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon of user "Tony a"
3) In Edit Profile -> CUSTOM ATTRIBUTES ->Gender try to add characters
4) Click on Save
Observe

Current Result :
Able to add Junk character in Edit Profile -> CUSTOM ATTRIBUTES -> Gender field

Expected result:
Should not be able add Junk character in Edit Profile -> CUSTOM ATTRIBUTES -> Gender field

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![20](https://user-images.githubusercontent.com/51490878/87249886-6275cf00-c47f-11ea-9c5b-db4dbc9c1c38.png)


![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87249913-7de0da00-c47f-11ea-9504-83b8c0015af1.png)

**Comment by callmekatootie** [comment]
not a valid bug. custom attributes allow any data. no validation is carried out.
