### ISSUE TITLE
A Warning popup Didn't show up After We created Same Group name

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#255]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Click middle tab

## Expected Result
A warning popup will show if we tried to create the same name for the group.

## Actual Result
Warning popup not shown if we tried to create the same name for the group.

## Screenshot
![](https://www.dropbox.com/s/ps1uwlm9scx2jcc/same_group.png?raw=1)

## Video
https://www.dropbox.com/s/vh379euxd1dbwog/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2018-00-05.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
duplicate #116
