### ISSUE TITLE
The UI for success message should match with app UI

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#256]
**Reproduction Steps:**
1. Open the application
2. Click on any "+" button -> show "Add to group" popup
3. Click on "Search or create popup" textbox -> enter new name group, ex: "888"
4. Click on "Create" button -> show browser alert for success message 
5. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1rvBcTyt4ErPJrVNJAiQoUkTfnXdz_qLp

**Actual Result:**  Should not show browser alert for success message

**Expected Result:** The UI for success message should match with app UI

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
we do not have custom notification - we are using browser's alert for now. not a valid bug
