### ISSUE TITLE
There is too much blank space in the employees profile

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#26]
**Describe the bug**
There is too much blank space in the employees profile
**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Scroll down and observe there is too much blank space between the employees details

**Actual Behavior**
observe there is too much blank space between the employees details cards

**Expected behavior**
There should not be too much blank space

**Screenshots**

![Snapshot 2020-07-12 18 35 36](https://user-images.githubusercontent.com/42939505/87247117-639f0000-c46f-11ea-993d-21c048f85c08.png)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
not a valid issue - One employee card is larger due to the # of groups in them and we are showing the cards in a grid
