### ISSUE TITLE
Able to add Junk character in Edit Profile -> CUSTOM ATTRIBUTES -> isAvailable field

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#260]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon of user "Tony a"
3) In CUSTOM ATTRIBUTES -> isAvailable try to add characters
4) Click on Save
Observe

Current Result :
Able to add Junk character in Edit Profile -> CUSTOM ATTRIBUTES -> isAvailable field

Expected result:
Should not be able to add Junk character in Edit Profile -> CUSTOM ATTRIBUTES -> isAvailable field

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![21](https://user-images.githubusercontent.com/51490878/87249954-b84a7700-c47f-11ea-8254-3396d5439370.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87249958-ba143a80-c47f-11ea-8233-c596f816f4f3.png)

**Comment by callmekatootie** [comment]
not a bug. custom attributes are free form text - user can enter anything. no validation is performed for now
