### ISSUE TITLE
Profile is not getting added to the group when the group toggle is on from the profile page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#261]
**Describe the bug**
The profile is not getting added to the group when the group toggle is on from the profile page

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now go to group
3. now click on  any group
4. and on the toggle of group from any profile

**Actual Behavior**
observe the toggled group, profile is not added in that group

**Expected behavior**
Profile must be added to that group when group toggle is on

**Screenshots**
[2020-07-12 19-41-38.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908725/2020-07-12.19-41-38.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment]
not a bug - we are using an external api for the group count - so it is a bug, but not with this app, but with the external api
