### ISSUE TITLE
Flickering observed when click on "+" sign Edit page to add Group and click on Done from "Add to Group" popup

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#263]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon of user "Tony a"
3) In Edit profile page click on "+" sign to add to group.
4) In "Add to Group" popup click on done.
5) Repeat step 3 and 4 few times.
Observe

Current Result :
Flickering observed when click on "+" sign Edit page to add Group and click on Done from "Add to Group" popup

Expected result:
Flickering should not be observed when click on "+" sign Edit page to add Group and click on Done from "Add to Group" popup

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
[22.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908733/22.zip)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250119-969dbf80-c480-11ea-864c-ca76a5e7dfb7.png)

**Comment by coderkid19** [comment]
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250133-a7e6cc00-c480-11ea-83b2-607f0ce3123b.png)

**Comment by callmekatootie** [comment]
cannot reproduce
