### ISSUE TITLE
Adding groups increase the width of  information box 

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#265]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. adding group names increase the width of box instead it should give an option to click more to see other groups

Current results
adding group names increase the width of box instead it should give an option to click more to see other groups

Expected results
adding group names increase the width of box instead it should give an option to click more to see other groups

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
![Screen Shot 2020-07-12 at 8 43 03 PM](https://user-images.githubusercontent.com/57220292/87250093-7a018780-c480-11ea-8afc-28d3393ba8ef.png)

**Comment by callmekatootie** [comment]
not a bug. that is expected.
