### ISSUE TITLE
Group name is broken when it is long name

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#268]
**Reproduction Steps:**
1. Open the application
2. Click on any "+" button -> show "Add to group" popup
3. Click on "Search or create popup" textbox 
4. Enter new name group, ex: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
5. Click on "Create" button -> show browser alert for success message -> Click on"OK"
6. Observe result

**Screenshot/screencast:**

![Screenshot_1](https://user-images.githubusercontent.com/26895101/87250095-0f0a7d80-c48d-11ea-895c-81c79cefe8fa.png)

**Actual Result:**  Group name is broken when it is long name

**Expected Result:** Group name should not overlap with toggle icon

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
duplicate #27
