### ISSUE TITLE
Other groups should be sorted either by name or count of users in it decreasing order

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#273]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. click on group page button -Other groups should be sorted either by name or count of users in it decreasing order

Current results
Other groups should be sorted either by name or count of users in it decreasing order

Expected results
Other groups should be sorted either by name or count of users in it decreasing order

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
![Screen Shot 2020-07-12 at 8 47 02 PM](https://user-images.githubusercontent.com/57220292/87250208-f6946600-c480-11ea-99a8-9d36d2a37ebf.png)

**Comment by callmekatootie** [comment]
not a bug, more like a feature

**Comment by akultalwar89** [comment]
@callmekatootie  - i am giving more of feature request, should participate in solution activities :)
