### ISSUE TITLE
the "Deactivate this user" button should not be visible/clickable when there is another modal on the current modal

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#274]
### Reproduction Steps ###

1. login to the app

2. click on Edit button for a profile

3. click "+" to add to group

4. observe the "Deactivate this user" button

### Expected Result ###

The "Deactivate this user" button should not be visible/clickable when there is another modal on the current modal

### Actual Result ###
See screenshot, it is clickable.

### Screenshot and/or screencast ###
![add](https://user-images.githubusercontent.com/4590317/87250267-43366c00-c496-11ea-8859-6951dbb06ecb.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
duplicate of #200
