### ISSUE TITLE
UI issue when enter Location/ Company with many characters 

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#278]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, click on "Edit" icon then enter many characters in Location/ Company 
3. Click on "Save" button
4. Observe the result 

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1_BulxYoE-lTVIjtmf2xIqs5N7zc5Wt93?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** UI issue when enter Location/ Company with many characters 

**Expected Result:** It should limit characters for Location/ Company field 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
No validation performed at the moment for the fields so not a bug for now
