### ISSUE TITLE
the page should not be scrollable when there is a modal displayed on it

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#279]
### Reproduction Steps ###

1. login to the app

2. click on Edit button for a profile

3. scroll the page, observe

### Expected Result ###

The page should not be scrollable when there is a modal displayed on it.

### Actual Result ###
See screenshot, it is scrollable.

### Screenshot and/or screencast ###
![scroll](https://user-images.githubusercontent.com/4590317/87250301-7ed13600-c496-11ea-9dc8-982c96cea5ec.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
cannot reproduce in firefox
