### ISSUE TITLE
Image moves on switching tabs

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#28]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Switch between the first two tabs 

## Screenshots/Video
[sc11.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908538/sc11.zip)

##  Actual Result(s)

Image moves on tab switch (See video)

##  Expected Result(s)

Image stays as is when switch tab

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
a scrollbar appears due to the large sidebar filter, which causes the image to shift a bit. not a valid bug.
