### ISSUE TITLE
Edit page can be saved without "First name".

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#280]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Click on Edit icon of user "Tony a"
3) In Edit page, delete any content from"First name" 
4) Click on Save
Observe

Current Result :
Edit page can be saved without "First name".

Expected result:
Edit page should not be able to save without "First name".
First Name should be mandatory. without first name details should not be allowed to save. 

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![24](https://user-images.githubusercontent.com/51490878/87250333-b71a4980-c481-11ea-96c6-23d194683f3d.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250334-ba153a00-c481-11ea-9d43-5d7aa5100e26.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87250339-bbdefd80-c481-11ea-8079-9ecbae52bca0.png)

**Comment by callmekatootie** [comment]
No validation performed currently and the input is free form at the moment
