### ISSUE TITLE
the confirmation modal should have proper style to be consistent with the current app

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#282]
### Reproduction Steps ###

1. login to the app

2. click on Edit button for a profile

3. click "Deactivate this user", observe

### Expected Result ###

The confirmation modal should have proper style to be consistent with the current app

### Actual Result ###
See screenshot.

### Screenshot and/or screencast ###
![de](https://user-images.githubusercontent.com/4590317/87250360-d40d4780-c496-11ea-9b8a-d0447bae824d.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
we do not have a design for this yet and we are using the browser's alert and confirm feature for now. not a bug
