### ISSUE TITLE
[Bug Hunt]Alignment issue on Profile tab

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#283]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Navigate to Groups tab
![image](https://user-images.githubusercontent.com/68163678/87250390-0b252e00-c482-11ea-8ffc-3c421208475e.png)

3.Scroll down
![image](https://user-images.githubusercontent.com/68163678/87250335-ba153a00-c481-11ea-9a8b-dd56bd59fc66.png)

4.Verify alignment issue when one profile have more number of groups.
![image](https://user-images.githubusercontent.com/68163678/87250326-af5aa500-c481-11ea-9826-cf857c77c5c8.png)

**Actual result:**
Alignment issue
**Expected result:**
Alignment should be proper
**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment]
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
not a bug - the grid ensures that new rows start at the same line...
