### ISSUE TITLE
clicking on x button on search refreshes the page bottom when nothing is typed in

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#286]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2.  refresh the page now click on search button cancel or X button - is refreshing the list of profiles while user has not searched for anything.
Similar thing is happing on Group page and it removed all the members selected in  a group

Current results
click on search button cancel or X button - is refreshing the list of profiles while user has not searched for anything.

Expected results
It should not refresh the profiles as user has not searched for any keyword.

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
![Screen Shot 2020-07-12 at 8 56 47 PM](https://user-images.githubusercontent.com/57220292/87250457-7bcc4a80-c482-11ea-9bac-90b649f39b76.png)
[Screen Recording 2020-07-12 at 8.56.11 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908760/Screen.Recording.2020-07-12.at.8.56.11.PM.mov.zip)

**Comment by callmekatootie** [comment]
Will be taken up in #138

**Comment by callmekatootie** [comment]
Resolved
