### ISSUE TITLE
Able To Create Group With White Space

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#288]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder 

3. Select Icon Next To Filter

4. Click On Search Or Create Group Then Put Blank Space & Click Create.

5. Click On OK & Scroll Down Mouse Below Then Observe.

6. see Screencast & Screenshot:-
[14.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908759/14.mp4.zip)
![14](https://user-images.githubusercontent.com/42583358/87250466-8ab2fd00-c482-11ea-9bfa-d6a6b73c148f.png)

7. Current Result:- Able To Create Group With White Space

8. Expected Result:- Should Not Be Able To Create Group With White Space

9. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

10. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #34
