### ISSUE TITLE
Down arrow should be changed up arrow in left side filter "Location" when details are minimized 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#291]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) From lest side click on "Location" to minimize details.
Observe down arrow

Current Result :
When filter details are minimized arrow remains downward

Expected result:
Down arrow should be changed up arrow in left side filter "Location" when details are minimized 

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![26](https://user-images.githubusercontent.com/51490878/87250576-5d1a8380-c483-11ea-9c54-8503da23bc7e.png)

**Comment by coderkid19** [comment]
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250596-79b6bb80-c483-11ea-8eb3-b3c1895c5286.png)

**Comment by callmekatootie** [comment]
duplicate #88
