### ISSUE TITLE
"No location found" and "No achievement found" messages not aligned properly

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#293]
https://take.ms/4IrrF

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enter invalid date to Locations and achievement
4. Observe the error message

**Actual Result:** "No location found" and "No achievement found" messages not aligned properly

**Expected Result:** Should center align if not left align

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
will accept it a a valid bug

**Comment by callmekatootie** [comment]
Not applicable anymore since we updated both fields to use auto suggest instead
