### ISSUE TITLE
[$20] When experience in filter is selected too long it's going outside the box see in image

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#294]
**Describe the bug**
When experience in filter is selected too long it's going outside the box see in image

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now select the experience in filter box which is very long
3. observe it is going outside the box

**Actual Behavior**
If experience is too large it is going outside the box

**Expected behavior**
If the number is too large it must be aligned properly

**Screenshots**

![Snapshot 2020-07-12 18 35 36](https://user-images.githubusercontent.com/42939505/87250597-81766000-c483-11ea-9b20-0ec51cb48fcd.png)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: IE 11
 - Version:  11.900

**Comment by callmekatootie** [comment]
valid bug - the value does not have a space in it

**Comment by callmekatootie** [comment]
Expected:

The filter values are basically going to be the values that will be present in any of the user's profiles.

When the filter is selected, in the pill, ensure that long values are displayed properly. You have two options here - either provide `...` ellipsis indicator and on hover show tooltip with full value, or do a word wrap (and for a really long word, break word) and in the case of the latter, provide proper padding

You need to do this for ALL pills in all the filter sections in the left sidebar

**Comment by callmekatootie** [comment]
This is now resolved along with the group pills issue.

![image](https://user-images.githubusercontent.com/2317133/88463330-81d51900-cecf-11ea-9ea3-318ed65d99fa.png)
