### ISSUE TITLE
Background color should be changed when user hover mouse on Add filter

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#296]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Hover mouse on top of "Add filter" in left side.
Observe

Current Result :
Background color is not changing when hover mouse on Add filter

Expected result:
Background color should be changed when user hover mouse on Add filter

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![27](https://user-images.githubusercontent.com/51490878/87250641-e5992400-c483-11ea-85e0-e83479419c4b.png)

**Comment by coderkid19** [comment]
![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250670-2002c100-c484-11ea-8483-e699d2fcc349.png)

**Comment by callmekatootie** [comment]
duplicate #188
