### ISSUE TITLE
The UI for Confirm message should match with app UI

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#297]
**Reproduction Steps:**
1. Open the application
2. Click on "Edit Profile" icon -> show "Edit Profile" popup
3. Click on "Deactivate this user" button -> show browser alert for Confirm message 

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1M8R5HSJqxWVVOS0P5BMALwmtqG_GtUkT

**Actual Result:**  Should not show browser alert for Confirm message

**Expected Result:** The UI for Confirm message should match with app UI

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
we don't have a design currently and we are using the browser's confirmation window for this
