### ISSUE TITLE
[Bug hunt] Available tag should be displayed in green color

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#298]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Scroll down and verify Availability accordion.
![image](https://user-images.githubusercontent.com/68163678/87250614-a9fe5a00-c483-11ea-9acc-3a6fe37cce5c.png)

3Available field should be displayed with green color.

![image](https://user-images.githubusercontent.com/68163678/87250632-d1552700-c483-11ea-9447-ee03c96ddf65.png)

**Actual result:**
Available field is displayed with grey color
**Expected result:**
Available field is displayed with green color

**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment]
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
not a bug for reasons mentioned here - https://github.com/topcoder-platform/u-bahn-app/issues/84#issuecomment-658611940
