### ISSUE TITLE
able to "Download Import Template (.XLS)" without authentication

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#299]
### Steps to Reproduce
Open https://skill-search.topcoder-dev.com web app
Login with tonyj /appirio123
Select topcoder as organization
Navigate to third tab
Enable browser inspector and navigate to Network tab of inspector
Click on "Download Import Template (.XLS)" and notice the URL in network tab of inspector
Copy the URL and try doing a `wget URL` from your system
Notice the results.

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 9 07 08 PM" src="https://user-images.githubusercontent.com/5712602/87250646-eb8f0500-c483-11ea-9c5f-89757a328608.png">

<img width="1440" alt="Screenshot 2020-07-12 at 9 09 15 PM" src="https://user-images.githubusercontent.com/5712602/87250652-f8abf400-c483-11ea-8555-b5bff209039b.png">

### Current Results
able to "Download Import Template (.XLS)" without authentication.

### Expected Results
Should be able to download from a valid session only. 

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
Yep. It is a signed S3 url - meant for limited time use. You are actually passing the auth fields in the url if you observe closely and these expire after a short time
