### ISSUE TITLE
[Firefox]"Logout" is not centrally aligned

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#30]
Steps :

1. Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123
2. Selected Org as topcoder
3. Observe Logout button

Current result:
"Logout" is not centrally aligned

Expected Result
"Logout" should be  centrally aligned

**Comment by coderkid19** [comment]
![2](https://user-images.githubusercontent.com/51490878/87247159-b678b780-c46f-11ea-81ca-2fe2255b9b5e.png)

**Comment by coderkid19** [comment]
![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87247169-c1334c80-c46f-11ea-8ba6-6c0c1b044f9e.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87247172-c5f80080-c46f-11ea-912c-176437cc6699.png)

**Comment by callmekatootie** [comment]
intentional. css explicitly sets it to right align
