### ISSUE TITLE
Filter dropdown width is depending on the current searched text

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#300]
https://take.ms/fHtgA

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Add all the 'COMPANY ATTRIBUTES' from Add Filters
4. Type some text on those and check the dropdown

**Actual Result:** Filter dropdown width is depending on the current searched text

**Expected Result:** Should have min fixed width. Equal to the dropdown field width 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Will take this as a valid bug

**Comment by callmekatootie** [comment]
After discussion on Slack - Will not be fixed. Closing
