### ISSUE TITLE
Gender Is accepting Numerical Value

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#301]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Add Filter > Select Gender > Try To Fill Numerical Value Then Observe

4. see Screencast & Screenshot:-
[15.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908773/15.mp4.zip)
![15](https://user-images.githubusercontent.com/42583358/87250679-2ee97380-c484-11ea-8a5e-3c6cc637b989.png)

5. Current Result:- Gender Is accepting Numerical Value

6. Expected Result:- Gender Should Not Accept Numerical Value

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
gender is a custom attribute and we do not perform validations here - it is free text input
