### ISSUE TITLE
Background color should be changed when user hover mouse on Edit icon in user profile

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#302]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123 ( selected Org topcoder)
2) Hover mouse on top of Edit icon in user profile
Observe

Current Result :
Background color is not changing when hover mouse on top of Edit icon in user profile

Expected result:
Background color should be changed when user hover mouse on top of Edit icon in user profile

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![28](https://user-images.githubusercontent.com/51490878/87250730-9b647280-c484-11ea-84bf-7db4bfe2b2a7.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87250742-afa86f80-c484-11ea-9a50-3a13d5bfe90a.png)

**Comment by callmekatootie** [comment]
not a valid bug. no such expectation in the design
