### ISSUE TITLE
IsAvailable Should be Have radio button attribute not search

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#303]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Click filter button
4. Activate isAvailable attribute, click done
5. Observe the isAvailable filter card.

## Expected Result
IsAvailable Should be Have radio button attribute not search.

## Actual Result
IsAvailable shown filter input instead of radio button.

## Screenshot
![](https://www.dropbox.com/s/hbui189avyc3auy/isAvailable.png?raw=1)

## Video
https://www.dropbox.com/s/6094pbwk7dk6yz0/U-Bahn%20employee%20skills%20search%20portal%20-%20Personal%20-%20Microsoft%E2%80%8B%20Edge%202020-07-12%2018-38-39.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser:Microsoft Edge Version 83.0.478.61 (Official build) (64-bit)

**Comment by callmekatootie** [comment]
duplicate #85
