### ISSUE TITLE
Company filter is not working properly

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#307]
**Describe the bug**
Company filter is not working properly

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/ 
2. Now type any company name which is available
3. observe the user profile is not coming

**Actual Behavior**
Company filter is not working when searched by company

**Expected behavior**
Filter must work properly

**Screenshots**
[2020-07-12 19-41-38.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908781/2020-07-12.19-41-38.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
Cannot reproduce
