### ISSUE TITLE
Experience (in months) Accepting Alphabets

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#310]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Add Filter > Select Experience (in months) > Try To Fill Alphabets Then Observe.

4. See Screencast & Screenshot:-
[16.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908784/16.mp4.zip)
![16](https://user-images.githubusercontent.com/42583358/87250849-5db41980-c485-11ea-959b-7863360022cf.png)

5. Current Result:- Experience (in months) Accepting Alphabets

6. Expected Result:- Experience (in months) Should Not Accept Alphabets

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
custom attributes are free text - no validation performed.
