### ISSUE TITLE
[Bug Hunt]:When user clicks on Add filter button then there is no option for closing the opened tab

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#311]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Scroll down and click on Add filter button.
![image](https://user-images.githubusercontent.com/68163678/87250897-b2579480-c485-11ea-988a-addbe7b8a2db.png)

3.Verify there is no option to close the tab once it is opened.
![image](https://user-images.githubusercontent.com/68163678/87250919-d3b88080-c485-11ea-916a-e1abe4ae68e6.png)

**Actual result:**
There is no option to close the tab
**Expected result:**
There should be an option to close the tab

**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment]
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
duplicate #17
