### ISSUE TITLE
Gender field have filter option as MaleInvalid

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#312]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Click on add filter 
add filter Gender 
type male on filter and 
observe

**Actual Result:** third option is visible MaleInvalid 

**Expected Result:** MaleInvalid should not be present as option.
custom attribute field for gender should be in drop down option 

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 

![bug5](https://user-images.githubusercontent.com/48902251/87250975-2d21af00-c488-11ea-8d7f-17ff7af50e03.jpg)

![Device_info](https://user-images.githubusercontent.com/48902251/87250982-327ef980-c488-11ea-8df2-34d867f55dfa.png)

**Comment by callmekatootie** [comment]
the filter dropdown values are picked from what currently exists for a user - so a user probably had that value (set by another tester)
