### ISSUE TITLE
'Skills', 'Achievements' and 'Custom attributes' title are not aligned properly

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#313]
![image](https://user-images.githubusercontent.com/42398485/87250995-29f9d500-c42e-11ea-877f-62f5b13e2a9b.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Edit button of a profile
4. Check the titles 'Skills', 'Achievements' and 'Custom attributes' 

**Actual Result:** 'Skills', 'Achievements' and 'Custom attributes' title are not aligned properly

**Expected Result:** Should vertically align

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Not a bug. The vertical alignment is not expected to be centered
