### ISSUE TITLE
Search in "Add Filters" modal dialog works only when more than 2 characters are typed in the text box

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#316]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on 'Add filter'
5. Now in "Add Filters" modal dialog type "LO" in the text box
6. Notice the search results

### Screenshots or Screen Capture
<img width="1437" alt="Screenshot 2020-07-12 at 9 27 30 PM" src="https://user-images.githubusercontent.com/5712602/87251083-b9cb6d80-c486-11ea-8775-07fde114ed35.png">

### Current Results
Search in "Add Filters" modal dialog works only when more than 2 characters are typed in the text box

### Expected Results
Search in "Add Filters" modal dialog should work with one or 2 characters also. Since the same works in groups filter on groups tab.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
not a bug. this is intentional
