### ISSUE TITLE
Sort dropdown is still displayed as open when user performs another operation

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#317]
https://take.ms/8E2fw

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click on the Sort dropdown
4. Click RESET and check the profile cards
5. Click RESET and check the profile cards

**Actual Result:** Sort dropdown is still displayed as open when user performs another operation

**Expected Result:** Should clear the dropdown

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
duplicate #102
