### ISSUE TITLE
[Bug Hunt] Numbers are accepted for First name and last name

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#318]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/
2.Click on edit button for any profiles

3.Enter numbers for First name and last name
![image](https://user-images.githubusercontent.com/68163678/87251087-c18b1200-c486-11ea-8ddc-819fd333dd70.png)

**Actual result:**
Numbers are accepted for first name and last name
**Expected result:**
Numbers should not be accepted for first name and last name

**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Comment by komal123s** [comment]
Data Used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
free form text. no validation performed. not a bug.
