### ISSUE TITLE
tabs should be disabled when user has not selected any organization

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#32]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app 
2. Login with tonyj /appirio123
3. Click on the tabs listed on the landing page

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 6 43 20 PM" src="https://user-images.githubusercontent.com/5712602/87247144-98ab5280-c46f-11ea-8827-417442049567.png">

### Current Results
Though the buttons can be clicked nothing happens since use has not selected any organization.

### Expected Results
tabs should be disabled when user has not selected any organization

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
not a valid bug. Not being able to select the org indicates something serious has gone wrong. At that point, the UI is unusable anyway. selecting the tabs also does not change anything - ui continues to show that message

**Comment by rprakash20** [comment]
@callmekatootie clickable tabs would be confusing for the users when the user has not selected any organization. the mouse hover cursor should be default when User has not selected any organization.

**Comment by rprakash20** [comment]
Or, UI should be in such a way that Users can identify that they need to select the Organization first .

**Comment by callmekatootie** [comment]
I am afraid my decision stands.

**Comment by rprakash20** [comment]
np, thanks for checking.
