### ISSUE TITLE
There is no option for filtering How much cards can be shown

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#321]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Scroll until you found pagination

## Expected Result
There should be option of how much users cards can be show in UI like 5,10,20,25,50

## Actual Result
There is no be option of how much cards can be show in UI like 5,10,20,25,50

## Screenshot
![](https://www.dropbox.com/s/d3d2waqod9udcmo/raw_option.png?raw=1)

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser:Microsoft Edge Version 83.0.478.61 (Official build) (64-bit)

**Comment by callmekatootie** [comment]
not a bug - there's no such feature.

**Comment by callmekatootie** [comment]
Good feature though
