### ISSUE TITLE
Search results loads then flickers and loads again when navigating to Search tab from another tab or on the ver first load after selecting the organisation

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#323]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Notice the search results page content
5. Now navigate to third tab
6. and then come back to Search tab again 
7. Notice the content load again

### Screenshots or Screen Capture

[search_results_refreshes_twice.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908806/search_results_refreshes_twice.mov.zip)

### Current Results
Search results loads then flickers and loads again when navigating to Search tab from another tab or on the ver first load after selecting the organisation

### Expected Results
Search should load without the flicker on the UI

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
for now, taking this as not a bug - there are indeed duplicate requests made to fetch the users on initial load but this is more of a necessity than a bug. The issue would not be observed if there's lots of users... so for now, this is not a bug
