### ISSUE TITLE
Profile cards flicker when loading

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#324]
https://take.ms/CXzEc

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Select a group with 10+ profiles
4. Observe

**Actual Result:** Profile cards flicker when loading

**Expected Result:** Should not flicker

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
The "flicker" here is the grid arranging the cards based on the content - would not take this as a bug for now.
