### ISSUE TITLE
While Clicking On Reset W1 Background Colour Is always Changing

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#325]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Reset Continuously Then Observe.

4. See Screencast:-
[17.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908808/17.mp4.zip)

5. Current Result:- While Clicking On Reset W1 Background Colour Is always Changing

6. Expected Result:- While Clicking On Reset W1 Background Colour Should Not Change

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
profile pic background is dynamically calculated each time - and it ensures that it picks a unique one for each user - hence it changes each time depending on the number of users and number of colors
