### ISSUE TITLE
Home Page only shown 1 user card

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#327]
## Step To Reproduce
1. Go to https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. Only 1 user appear in the homepage
4. Type **Tony** in the header search
5. Click middle tab
6. Click one of my group

## Expected Result
Home page should be shown more of the users.

## Actual Result
Only 1 user shown in the home page.

## Video
https://www.dropbox.com/s/9xc66dyr9rfcxvu/U-Bahn%20employee%20skills%20search%20portal%20-%20Personal%20-%20Microsoft%E2%80%8B%20Edge%202020-07-12%2019-06-46%20-%20Copy.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser:Microsoft Edge Version 83.0.478.61 (Official build) (64-bit)

**Comment by callmekatootie** [comment]
While edge browser is not in scope, I need to check if deactivating a user still shows that user in group search. Will get back.

**Comment by callmekatootie** [comment]
Deactivated users indeed show up in group search

**Comment by wdprice** [comment]
@callmekatootie so is this issue that deactivated users show in search or is it something else?

Assuming your comment is the core of the issue, I am placing this as a high priority fix.

If this is just a UI issue please notify me for repiroritization

**Comment by callmekatootie** [comment]
@wdprice You are correct - deactivated users are showing up when one searches for users in a group.

I am not sure how to handle this - when a user gets deactivated, should we remove that user from all the groups they belong to? Or should we display the overlay over that card, as we do currently, when we deactivate a user - indicating that the user was deactivated...

**Comment by wdprice** [comment]
I like the idea of an overlay showing a deactivated user. Only show the deactivated user + overlay when looking at group members though. Do not return them in search results.

**Comment by callmekatootie** [comment]
Gotcha. 

Currently they are not returned in the search results - in the scenario of this ticket, we first fetch the users from the group - and for deactivated users, the groups does not know that the user was deactivated... so it returns that user - and the UI proceeds to fetch the details of the user to show

**Comment by callmekatootie** [comment]
This has now been resolved
