### ISSUE TITLE
"Add Filters" > COMPANY ATTRIBUTES Title is not aligned vertically

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#328]
![image](https://user-images.githubusercontent.com/42398485/87251358-bc9b7380-c430-11ea-9d01-ba0c55da8357.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add Filters
4. Check the COMPANY ATTRIBUTES Title

**Actual Result:** COMPANY ATTRIBUTES Title is not aligned vertically

**Expected Result:** Should align vertically

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Not a bug - we are not expecting it to be aligned vertically
