### ISSUE TITLE
"Add Filters" > COMPANY ATTRIBUTES Last item bottom line is not present

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#329]
![image](https://user-images.githubusercontent.com/42398485/87251382-e94f8b00-c430-11ea-83dd-787d9596bdb8.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add Filters
4. Go to the last item of the COMPANY ATTRIBUTES section

**Actual Result:** COMPANY ATTRIBUTES Last item bottom line is not present

**Expected Result:** Should display the last item bottom line

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a bug.
