### ISSUE TITLE
escape button on keyboard doesnt work

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#33]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. escape button doesnt work on this page on click of edit button

Current results
escape button doesnt work on this page 

Expected results

escape button should close down the edit page

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 6 43 56 PM](https://user-images.githubusercontent.com/57220292/87247173-c7c1c400-c46f-11ea-963e-4eeb9b654533.png)

**Comment by callmekatootie** [comment]
not a valid issue. there is no expectation here that ESC should close the modal

**Comment by akultalwar89** [comment]
@callmekatootie  - Escape button is very common in terms of closing tooltip or hover pages on any application. shouldnt it be functional, as Tab, and othe keyboard items work on application. Easy to traverse in the application.

**Comment by callmekatootie** [comment]
I think it's more of a feature than a bug. I am afraid my decision stands.
