### ISSUE TITLE
"Add Filters" and "Add to Group" header color is different

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#330]
https://take.ms/0uBon

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add Filters and check the header color (Light Gary)
3. Click Add to Group and check the header color (Drak Gary as the below title sections)

**Actual Result:** "Add Filters" and "Add to Group" header color is different

**Expected Result:** Should be the same as in the "Add Filters"  (Light Gray)

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
css says both are colored # 252526. not a bug
