### ISSUE TITLE
While Selecting Informatika, Upwork & Topcoder No Data Is Showing

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#331]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Informatika, Upwork & Topcoder Then Observe.

4. See Screencast & Screenshots:-
[18.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908823/18.mp4.zip)
![18 N](https://user-images.githubusercontent.com/42583358/87251457-8fc77a80-c489-11ea-9714-72d48b41e4b2.png)
![18](https://user-images.githubusercontent.com/42583358/87251464-9950e280-c489-11ea-80a3-f5ee8eb4ea53.png)

5. Current Result:- While Selecting Informatika, Upwork & Topcoder No Data Is Showing.

6. Expected Result:- While Selecting Informatika, Upwork & Topcoder It Should Show Some Data.

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
cannot reproduce
