### ISSUE TITLE
"Other Groups" are not loading sometimes

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#332]
https://take.ms/DIqnp

**No Any Console errors**

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add to Group and check the "Other Groups" 
4. Go to Groups Tab and check also

**Actual Result:** "Other Groups" are not loading sometimes

**Expected Result:** Should load always

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
cannot reproduce - most likely the user TonyJ was added to all groups - OTHER GROUPS are groups where the logged in user is not a part of
