### ISSUE TITLE
application shows 1 user profile while Unavailable and available are uncheck

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#333]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 1
Click on filter option uncheck  Unavailable and available 
Observe

**Actual Result:**  1 profile card is visible Warono majio
@TonyJ

**Expected Result:**  both Unavailable and available unchecked should shouw 0 profile cards

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 

![bug8](https://user-images.githubusercontent.com/48902251/87251539-2eed7180-c48c-11ea-8db7-7e0569954f71.jpg)

![Device_info](https://user-images.githubusercontent.com/48902251/87251540-31e86200-c48c-11ea-87b1-b27b401e340f.png)

**Comment by callmekatootie** [comment]
cannot reproduce - most likely there was indeed just 1 user and other users were deactivated when you tested
