### ISSUE TITLE
Should expand/ collapse the "expand/collapse" card when click to header

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#337]
**Reproduction Steps:**
1. Open the application
2. Click on header of Location item
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1c4rLKYaD4xJSr47bxHpxfFVLDOErxZU3

**Actual Result:**  Only expand/ collapse when click on chevron icon

**Expected Result:** Should expand/ collapse the "expand/collapse" card when click to header

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
duplicate #224
