### ISSUE TITLE
While Filtering Three Items Its Showing Only One 

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#339]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder 

3. Click On Informatika, Upwork & Topcoder. Then See Filters & Observe.

4. See Screencast & Screenshots:-
[19.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908829/19.mp4.zip)
![19](https://user-images.githubusercontent.com/42583358/87251640-c5b92e80-c48a-11ea-9ce8-fd0bb79f39c8.png)
![19A](https://user-images.githubusercontent.com/42583358/87251648-d4074a80-c48a-11ea-92bb-10e9f42472a4.png)

5. Current Result:- While Filtering Three Items Its Showing Only One 

6. Expected Result:- While Filtering Three Items Its Should Show Three

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
it is talking about # of filters applied - in this case, only 1 filter - achievements was applied.
