### ISSUE TITLE
[$10] White spaces are accepted as valid group names

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#34]
![image](https://user-images.githubusercontent.com/42398485/87247179-cebce800-c417-11ea-9148-2b5e12f18197.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click 'Add to Group'
4. Enter a white space
5. Click Create
6. Check the OTHER GROUPS list

**Actual Result:** White spaces are accepted as valid group names

**Expected Result:** Should validate it

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/ggNIOH

**Comment by callmekatootie** [comment]
valid issue. we need to trim input before we create the group

**Comment by callmekatootie** [comment]
Expected:

- Trim the input before group creation.
- We need to do this in both Add To Group modal and Group tab page

**Comment by callmekatootie** [comment]
Resolved
