### ISSUE TITLE
Distance in the bottom of "Edit profile" popup is wide compared to CUSTOM ATTRIBUTES

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#340]
**Reproduction Steps:**
1. Open the application 
2. On "Search" tab, click on "Edit" icon then observe distance in the bottom of "Edit profile" popup

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1i2BjLn0DJJ8ZSWNKD93yRrDLCDoTWVVS?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Distance in the bottom of "Edit profile" popup is wide compared to CUSTOM ATTRIBUTES

**Expected Result:** Should expand area for CUSTOM ATTRIBUTES and  Distance in the bottom of "Edit profile" popup will be small  

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Will wait for #17 to wrap up - might be resolved by the changes in that ticket

**Comment by callmekatootie** [comment]
No longer an issue - #17 resolved this
