### ISSUE TITLE
Search results reload twice

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#341]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Let it load
    3. Click on "Groups" tab button (Second tab)
    4. Click on "Search" tab button (First tab)
    5. Wait and observe

## Screenshots/Video
[sc14.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908848/sc14.zip)

##  Actual Result(s)

Search is done two times automatically. (It reloads twice). See video for clarity.

##  Expected Result(s)

Should either use results fetched earlier or show after a single search.

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
for now, taking this as not a bug - there are indeed duplicate requests made to fetch the users on initial load but this is more of a necessity than a bug. The issue would not be observed if there's lots of users... so for now, this is not a bug
