### ISSUE TITLE
Getting 500 Server internal error when filter via skill

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#343]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Try to filter via skill and observe network 

**Actual Result:** 
Getting 500 Sever internal error when search via skill

**Expected Result:** 
Should not get any server error when filter via any option

**Screenshot**
[Bug12.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908864/Bug12.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** Chrome 83.0.4103.106

**Comment by callmekatootie** [comment]
cannot reproduce
