### ISSUE TITLE
Different color for one user when search

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#345]
**Reproduction Steps:**
1. Open the application
2. Click on "Search talent or keyword" textbox
3.  Enter: "Tony" -> observe profile icon
4. Clear search then observe profile icon
5. Enter: "Tony" -> observe profile icon

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1bgQQHvSqbQIH1f1QZSE-P9U6MnAhgpNz

**Actual Result:**  Different color for one user when search

**Expected Result:** Should not change color for one user when search

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
not a bug - See #325  for explanation
