### ISSUE TITLE
Texts Are Overlapping

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#346]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click On Icon Next After Filter > Scroll Down Mouse To Larissa Sporer Details Then Observe.

3. See Screenshot:-
![21](https://user-images.githubusercontent.com/42583358/87251996-614b9e80-c48d-11ea-8979-891036ed2810.png)

4. Current Result:- Texts Are Overlapping

5. Expected Result:- Texts Should Not Overlap

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #91
