### ISSUE TITLE
Upload box top and bottom spacing issue

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#347]
https://take.ms/opRCJ

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 03 (Upload)
3. Check the dotted border-spacing from the top and bottom

**Actual Result:** Upload box top and bottom spacing issue

**Expected Result:** Should have the same spacing

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a bug - intentional
