### ISSUE TITLE
Number filters applied show incorrectly

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#348]
**Reproduction Steps:**
1. Open the application 
2. On the first tab, try to click on some items in Location and observe the number filters applied 
(E.g: Click on "London" -> observe the number filters applied , then click on "New York" and "East Carmen")

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1vKwKhzjtskIyEc4vmBWmw8YcbkEcVVw1?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Number filters applied still show 1 although we select 3 filter value

**Expected Result:** Number filters applied should show correctly corresponding to number selected filter value 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
number of filters is the count of filter sections - not the count of filters in each section
