### ISSUE TITLE
Add Group box shrink when user paste a text

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#349]
![image](https://user-images.githubusercontent.com/42398485/87252164-97116880-c436-11ea-97c3-6102a2aa73da.png)

https://take.ms/gpHQx

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click Add Group and Paste "adsdadad gdhdajdajdgsdjs sssssaaa sadsada sdsdsadadasdadsdsdsdsd"

**Actual Result:** Add Group box shrink when user paste a text

**Expected Result:** Should not shrink the popup

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
Will take this as part of #336
