### ISSUE TITLE
Sort by data  is not properly aligned

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#35]
**Describe the bug**
Sort by data  is not properly aligned

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Click on sort by and observe the dropdown text is not properly aligned

**Actual Behavior**
observe the dropdown text is not properly aligned

**Expected behavior**
Text must be properly aligned from left to right

**Screenshots**
![Snapshot 2020-07-12 18 35 36](https://user-images.githubusercontent.com/42939505/87247187-dad49400-c46f-11ea-9512-90d2c6e70e33.png)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
not a valid issue. css explicitly has it right aligned
