### ISSUE TITLE
While Search Via Location & Select Filter As @ Its Showing Details To Select

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#354]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click Add Filter > Select Location > Try To Filter Via @ Then Observe

3. See Screencast & Screenshot:-
[22.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908904/22.mp4.zip)
![22](https://user-images.githubusercontent.com/42583358/87252336-d0c28d80-c48f-11ea-8097-60784d5045a0.png)

4. Current Result:- While Search Via Location & Select Filter As @ Its Showing Details To Select

5. Expected Result:- While Search Via Location & Select Filter As @ It Should Not Show Details To Select

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
Will take this as part of #295 - handling of special characters

**Comment by devsreekrishna** [comment]
Hi

In My Case #354, #358 & #376 Its Different From 295. In This "Special Character Case" I Am Able To Find Details, Which Should Not Happen. Kindly Go Through It Then Decide. 

Thanks

**Comment by callmekatootie** [comment]
I understand what you mean - that you are talking about the results in the dropdown itself v/s results in the search. I am taking them all as one because internally, we are dealing with the same entity - elasticsearch - and in both the cases, it is elasticsearch that is returning with the data (or lack thereof).
