### ISSUE TITLE
No change in color while hover over edit icon 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#355]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 01
Hover over the cross icon 
Now hover over the edit icon 
observe

**Actual Result:**  No change in color of icon while hovering 

**Expected Result:** As hovered over other icons in application ,  Edit icon should have color while focused/ hovering over the icon 

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 
![Device_info](https://user-images.githubusercontent.com/48902251/87252443-c9e94a00-c492-11ea-8e78-9191baedb1fb.png)

Bug video: https://drive.google.com/file/d/1Am52vAF-8MaefuptNe3lNR8q0vzxaJti/view?usp=sharing

**Comment by callmekatootie** [comment]
not a bug
