### ISSUE TITLE
Should show different icon in the header when collapsed/ expand

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#356]
**Reproduction Steps:**
1. Open the application 
2. On the first tab, observe icon beside Location/Availability/Skills/Achievements -> it is down icon
3. Click on this icon and observe the result 

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1FenP2Iw2GK0Axn-OWItdyFHXyeTA3Ty-?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** 
When Location/Availability/Skills/Achievements expand -> Icon is down
When Location/Availability/Skills/Achievements collapsed -> Icon is still down

**Expected Result:** Should show different icon in the header when collapsed/ expand
When Location/Availability/Skills/Achievements expand -> Icon is down
When Location/Availability/Skills/Achievements collapsed -> Icon is up

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
duplicate #88
