### ISSUE TITLE
Should not show hand cursor when hover on disabled next/previous button 

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#357]
**Reproduction Steps:**
1. Open the application
2. Scroll down page then hover on Next/ previous buttons
4. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1DhRFgV7OXo5hAexq9YGzXpCQyuUfjSF7

**Actual Result:**  Show hand cursor when hover on disabled next/previous button 

**Expected Result:** Should not show hand cursor when hover on disabled next/previous button.

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
not a bug
