### ISSUE TITLE
While Search Via Company & Select &, * Its Showing Data

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#358]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click Add Filter > Select Company > Try To Search With & , * Then Observe.

3. See Screencasts & Screenshots:-
[23.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908912/23.mp4.zip)
![23](https://user-images.githubusercontent.com/42583358/87252487-2f3c3b80-c491-11ea-8978-aab940c49d58.png)
![23A](https://user-images.githubusercontent.com/42583358/87252489-39f6d080-c491-11ea-85d0-793a04ea3729.png)

4. Current Result:- While Search Via Company & Select &, * Its Showing Data

5. Expected Result:- While Search Via Company & Select &, * It Should Not Show Any Data

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
will take this as part of #295 - special chars handling in search
