### ISSUE TITLE
Can Click Both Available and Unavailable

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#36]
## Step To Reproduce
1. https://skill-search.topcoder-dev.com/
2. Click **Benefit** Logo

## Expected Result
We can only choose 1 choice

## Actual Result
We can click both Both of choice (available and unavalaible).

## Screenshot
![](https://www.dropbox.com/s/n8584qvkobneplv/availability2.png?raw=1)

## Video
https://www.dropbox.com/s/h1fcpz9157lywyb/2020-07-12-16-09-13.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
valid issue

**Comment by callmekatootie** [comment]
On second thoughts, not a valid bug

If I take the approach of having both of them active by default, then when the user has to filter only users that are available, then they need to click on Unavailable to turn it off. Now, if they want to see users that are unavailable, they would have to first click on Unavailable to toggle it on and then Available to toggle it off - not a good UX. So keeping current behaviour
