### ISSUE TITLE
While Filtering With Gender & Search With "(" Its Showing 400 Error In Console

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#360]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click Add Filter > Select Gender > Try To Search With "(" Then Observe In Console.

3. See Screencast & Screenshot:-
[24.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908935/24.mp4.zip)
![24](https://user-images.githubusercontent.com/42583358/87252676-a0302300-c492-11ea-9e9a-882fb9a00698.png)

4. Current Result:- While Filtering With Gender & Search With "(" Its Showing  Error In Console

5. Expected Result:- While Filtering With Gender & Search With "(" It Should Not Show Any Error In Console

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #295
