### ISSUE TITLE
[Common] Can't close popup by using ESC key

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#361]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Scroll down page then click on " Add filter" button
3. Try to close popup by using ESC key
4. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1BpOGfqlhKD8QhPg8Mh5hbznXbcrTbT9d

**Actual Result:**  Can't close popup by using ESC key

**Expected Result:** Should close popup by using ESC key

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
not a bug. this is more of a feature
