### ISSUE TITLE
Location and location two similar usage filter option available 

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#362]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Add on add filter and enable toggle of location
4. Observe Location and location have two similar option available 

**Actual Result:** 
Location and location have two similar filter option available 

**Expected Result:** 
All filter options should be identical

**Screenshot**
[Bug13.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908943/Bug13.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0

**Comment by callmekatootie** [comment]
duplicate #85
