### ISSUE TITLE
While Filtering With Gender & Search With {,[ Brackets With Opening. Its Showing An Error Message

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#363]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click On Search Field & Try To search with Opening {, [ Brackets Then Observe.

3. See Screencast:-
[25.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908948/25.mp4.zip)

4. Current Result:- While Filtering With Gender & Search With {,[ Brackets With Opening. Its Showing An Error Message

5. Expected Result:- While Filtering With Gender & Search With {,[ Brackets With Opening. It Should Not Show Any Error Message

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #295
