### ISSUE TITLE
Inconsistent size of dropdown when enter one character and two characters in location search box

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#364]
**Reproduction Steps:**
1. Open the application 
2. On first tab, click on "Add filter" button then add some filters (e.g: location)
3. Enter "a" in location -> observe the result
4. Remove then enter "at" in location -> observe the result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1hwngKSYv2Mx3OFKRoT5ipEYLycdvodhg?fbclid=IwAR2pD3gYGvZcsncY7T4ewgF1IEi-61WkcDjy_Rs7N6WIH86KnWvGCSpOFdU

**Actual Result:** Inconsistent size of dropdown when enter one character and two characters in location search box

**Expected Result:** Should consistent size of dropdown when enter one character and two characters in location search box

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
duplicate #300
