### ISSUE TITLE
Sort by drop-down still open after reset 

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#365]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Tap on Sort by so drop-down pop up open
4. Now reset filter so Sort by drop-down still open

**Actual Result:** 
Sort by drop-down still open after reset

**Expected Result:** 
Sort by drop-down should be close when reset filter

**Screenshot**
[Bug1.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908996/Bug1.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** Chrome 83.0.4103.106

**Comment by callmekatootie** [comment]
duplicate #102
