### ISSUE TITLE
Avatar color changes each time

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#366]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Let it load
    3. Click Reset

## Screenshots/Video
![Screenshot from 2020-07-12 23-10-33](https://user-images.githubusercontent.com/32861951/87252985-f8682480-c494-11ea-8e5e-476d49d0fe34.png)
![Screenshot from 2020-07-12 23-10-51](https://user-images.githubusercontent.com/32861951/87252987-f9995180-c494-11ea-8634-35d13d341bf2.png)
 For same user on reset.

##  Actual Result(s)

Background color of Avatar image changes each time (for each user)

##  Expected Result(s)

Avatar should be same each time (unless there's a change in Name)

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
not a bug for reasons mentioned here - #325
