### ISSUE TITLE
Different numbers are showing for Other Groups while same user logged in in multiple browser 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#367]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 02
Click observe the other group fields 
now repeate in another browser IE11

**Actual Result:** numbers in avengers are shown different in multiple browser

**Expected Result:** While same user is logged in different browser number count should not mismatch 

**Device/OS:** Laptop / Windows 10

**Browser Information:** Chrome 83.0.4103.116 
![IE_details](https://user-images.githubusercontent.com/48902251/87253018-70374e80-c497-11ea-9807-7a399635e7c7.png)
![Device_info](https://user-images.githubusercontent.com/48902251/87253019-73323f00-c497-11ea-87c8-8a20a9607fb2.png)

https://drive.google.com/file/d/1a8FKFNKnrRJBcsfsZCbwMKYpE29dM6WU/view?usp=sharing

**Comment by callmekatootie** [comment]
not a bug with the app - we use a different api for the group
