### ISSUE TITLE
While Filtering With isavailable & Search With (,),{,[ Its Showing An Error Message Is Showing In Console

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#368]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click Add Filter > Select isAvailable > try To Search With (,),{,[ Then Observe.

3. See Screencast:-
[26.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909009/26.mp4.zip)

4. Current Result:- While Filtering With isavailable & Search With (,),{,[ Its Showing An Error Message Is Showing In Console

5. Expected Result:- While Filtering With isavailable & Search With (,),{,[ It Should Not Show Any Error Message  In Console

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #295
