### ISSUE TITLE
[IE11] Duplicate clear button in search field in IE browser

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#369]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on "Search talent or keyword" search field then enter any text
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1erJPu--HcJUlRyx6EDnSj0Tb_4O9fcGu

**Actual Result:** Duplicate clear button in search field

**Expected Result:** Should not show duplicate clear button in search field

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
duplicate #173
