### ISSUE TITLE
More button text not aligned vertically

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#37]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Observe Left sidebar 

## Screenshots/Video
![Screenshot from 2020-07-12 18-44-06](https://user-images.githubusercontent.com/32861951/87247194-e1fba200-c46f-11ea-98f9-1cb7f8ac2370.png)

##  Actual Result(s)

More button text is not aligned (vertically) with other buttons' text

##  Expected Result(s)

All texts of buttons should be aligned

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
![image](https://user-images.githubusercontent.com/2317133/87510995-3d0cdf00-c692-11ea-9cfe-483456f732be.png)

Alignment seems to be fine, though on initial observation it did seem to be higher than the others.

not a valid issue
