### ISSUE TITLE
Filter not ignore cases when content match

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#370]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Tap on the London from Location filter option so filter result visible
4. When edit member profile London to london and apply filter via London so no filter result found

**Actual Result:** 
Content case filter result not applied 

**Expected Result:** 
filter should ignore cases to match result

**Screenshot**
[Bug15.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909012/Bug15.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** Chrome 83.0.4103.106

**Comment by callmekatootie** [comment]
not a bug - the search is case sensitive

**Comment by Krishna1507** [comment]
> 
> 
> not a bug - the search is case sensitive

Hi callmekatootie

I saw some bug accepted still search via case insensitive so i think every search should be case sensitive like Topcoder vs TopCoder

**Comment by callmekatootie** [comment]
Let me verify that and get back to you

**Comment by callmekatootie** [comment]
Checked - only the keyword search (the one in the header) is case insensitive. Otherwise the sidebar filters are case sensitive.
