### ISSUE TITLE
[IE11] Show redundant empty space in the right of page

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#373]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Observe scroll bar in the bottom page

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1OF1mstQ-J4y-a33u364QyiLUI9qDpbiG

**Actual Result:**  Show redundant empty space in the right of page

**Expected Result:** Should not show redundant empty space in the right of page

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
duplicate #62
