### ISSUE TITLE
My groups is not showing on Add to group window

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/u-bahn-app#374]
**Reproduction Steps:** 

Open the Application https://skill-search.topcoder-dev.com/
Click Topcoder > Go to tab 02
Click on edit icon 
click on + icon 
observe the My group field 

**Actual Result:** My group list is not visible 

**Expected Result:** my group list should be visible 

**Device/OS:** Laptop / Windows 10

**Browser Information:**  Chrome 83.0.4103.116 
![IE_details](https://user-images.githubusercontent.com/48902251/87253373-682cde00-c49a-11ea-953d-600a91f8f1ee.png)

https://drive.google.com/file/d/1fXY-HzDoXU92_v1ltEYFxnn3qdbMj3xZ/view?usp=sharing

**Comment by callmekatootie** [comment]
most likely the logged in user (which also shows up in search results) had all groups removed from them. MY GROUPS shows groups that the logged in user belongs to and you can add remove them
