### ISSUE TITLE
[All Filters like "Location" and "Achievements"]  Not all the filter options displayed even though the search text is cleared

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#375]
https://take.ms/Zyo7B

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Go to "Location" or "Achievements"
4. Type 'lon' in locations and Only London displayed
5. Clear the text (All displayed)
6. Type 'lon' in locations 
7. Collapse the section and Expand it (Search text is cleared but only London is displayed)

**Actual Result:** Not all the filter options displayed even though the search text is cleared

**Expected Result:** Should display all the location because the search text is cleared

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
Similar issue: https://take.ms/s4GZX

**Comment by callmekatootie** [comment]
duplicate #163
