### ISSUE TITLE
While Filtering With title & Searching With .,\,|,? Its Showing Option To Select

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#376]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click add Filter > Select title & Try to Search With ., \, |, ? Then Observe.

3. See Screencast:-
[27.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909057/27.mp4.zip)

4. Current Result:-  While Filtering With title & Searching With .,\,|,? Its Showing Option To Select

5. Expected Result:- While Filtering With title & Searching With .,\,|,? It Should Not Show Any Option To Select

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
duplicate #295
