### ISSUE TITLE
X button on search is not centrally aligned with Text like Magnifying image

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#377]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. observe the Top Search button X not centrally aligned with text like magnifying image is in center

Current results
Top Search button X not centrally aligned with text like magnifying image is in center

Expected results
Top Search button X not centrally aligned with text like magnifying image is in center . X button should be in center , minor different in alignment but UI defect. 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots -
![Screen Shot 2020-07-12 at 11 33 23 PM](https://user-images.githubusercontent.com/57220292/87253382-65c98480-c498-11ea-97c2-3e6674652a6b.png)

**Comment by callmekatootie** [comment]
Cannot reproduce. Not a bug

**Comment by akultalwar89** [comment]
Hi @callmekatootie  - apologies for this, but i can still reproduce it, definitely a minor bug, but not centrally aligned.
Its on the main  search page 
![Screen Shot 2020-07-17 at 9 36 42 PM](https://user-images.githubusercontent.com/57220292/87807535-fb3c8e00-c875-11ea-91f4-a8acd11513be.png)

![Screen Shot 2020-07-17 at 9 39 37 PM](https://user-images.githubusercontent.com/57220292/87807578-08f21380-c876-11ea-9f4d-525c494aa727.png)

**Comment by callmekatootie** [comment]
I am not denying that you can see it - just that I cannot see it at my end and thus I cannot treat it as a bug

**Comment by akultalwar89** [comment]
@callmekatootie - Can i share any steps or any other detail around it , that might help, i have time to get some more information around it.  :)
