### ISSUE TITLE
COMPANY ATTRIBUTES filters doesn't show "no <filter_name> found" message when searched for a non-existing keyword

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#378]
### Steps to Reproduce

1. Open https://skill-search.topcoder-dev.com/ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on "Add Filter"
5. Add all the filters available under 'COMPANY ATTRIBUTES'
6. Click Done.
7. Now, type "msndmsn" in company attribute filters like 'location, company, gender' etc
8. Notice the results

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 11 30 11 PM" src="https://user-images.githubusercontent.com/5712602/87253386-6a8e3880-c498-11ea-8d00-d7a4b79efee6.png">
<img width="1440" alt="Screenshot 2020-07-12 at 11 30 39 PM" src="https://user-images.githubusercontent.com/5712602/87253391-74b03700-c498-11ea-91fe-a7d35e04eff6.png">
<img width="1440" alt="Screenshot 2020-07-12 at 11 30 55 PM" src="https://user-images.githubusercontent.com/5712602/87253392-7679fa80-c498-11ea-834c-93a8dfb6a004.png">

### Current Results
COMPANY ATTRIBUTES filters doesn't show "no <item> found" message when searched for a non-existing keyword

### Expected Results
Should show "no <filter_name> found" based on the filter similar to GENERAL ATTRIBUTES filters.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #267
