### ISSUE TITLE
Billing Account should Have Some Limitations Of Alphabets & Numericals

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#379]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click Add Filter > Select Billing Account > Try To Fill Some Numericals & Alphabets Then Observe.

3. See Screencast & Screenshot:-
[28.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909075/28.mp4.zip)
![28](https://user-images.githubusercontent.com/42583358/87253455-fa33e700-c498-11ea-971b-dbee24d95005.png)

4. Current Result:- Billing Account should Have Some Limitations Of Alphabets & Numericals

5. Expected Result:- Billing Account Not Having Limitations Of Alphabets & Numericals

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
no limitations - it is free form text
