### ISSUE TITLE
Tag remove icon UI issue 

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#38]
![image](https://user-images.githubusercontent.com/42398485/87247229-15aadd80-c418-11ea-801d-75f779f4e4cc.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click 'Add to Group'
4. Select a Tag
5. Click Done
6. Check the tab remove button

**Actual Result:** Tag remove icon UI issue 

**Expected Result:** Should center align within the tag

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
Checked in IE11 - could not find any issue:

![image](https://user-images.githubusercontent.com/2317133/87796245-b6f5c180-c866-11ea-8cad-f2ad3757a6fe.png)
