### ISSUE TITLE
[IE11] Popup show weird full browser height without search result

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#380]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on "Add to group" then enter "tt"
3. Observe result

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1j0j6yo1Zmq3RkAddUCR5YnrCA6mlkKYF

**Actual Result:**  Popup show weird full browser height without search result

**Expected Result:** Should show reasonable popup height

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
duplicate #336
