### ISSUE TITLE
[Common for All Filters] Long Numbers and Texts will increase the width of the dropdown

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#381]
![image](https://user-images.githubusercontent.com/42398485/87253469-160b9e80-c441-11ea-91cf-7d655099b7e7.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Add all the filters
4. Set 'Experience (in months)'=2

Common for all the other filters that have long text and numbers

**Actual Result:** Long Numbers and Texts will increase the width of the dropdown

**Expected Result:** Should trim the long text

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #300
