### ISSUE TITLE
[Common] Long 'Billing Account' goes out of the container

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#382]
![image](https://user-images.githubusercontent.com/42398485/87253441-dd6bc500-c440-11ea-895d-77b039c45e52.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Add all the filters
4. Set 'Billing Account'=41
5. Select the long number

**Actual Result:** Long 'Billing Account' goes out of the container

**Expected Result:** Should trim the long text

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #294
