### ISSUE TITLE
Multiple clicks lead to /undefined path

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#383]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Go to Bulk upload tab (Third tab)
    3. Click 4-5 times continuously on "Download Import Template (.XLS)" 

## Screenshots/Video
[sc16.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908945/sc16.zip)

##  Actual Result(s)

You are taken to "https://skill-search.topcoder-dev.com/undefined"
Which shows error - 

>Error 404: Page is not found.
>,

##  Expected Result(s)

Should not lead to this strange page

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by g1tman** [comment]
Note: I'm throttling connection speed from dev tools to emulate slow network speed. (See video attached)

I'm able to reproduce this only for slow connections.

**Comment by g1tman** [comment]
Issue for Firefox. Works on Chrome

**Comment by callmekatootie** [comment]
Cannot reproduce. Clicking multiple times gives "Request Aborted" error

**Comment by g1tman** [comment]
@callmekatootie 

> Cannot reproduce. Clicking multiple times gives "Request Aborted" error

Yeah so in #359 , I mentioned this issue only. Can you please have a look at it again.

Without throttling, double click on the button leads to "Error Occurred Request Aborted".

For this issue, 
When I throttle the connection to 2G speed, and click on the button multiple times (3-5 times works for me), it leads to the /undefined path.

Note: clicks are continuously done.

**Comment by callmekatootie** [comment]
Yep. Understood the issue in #359 - but it is not a bug. It is expected behaviour (the one in 359) when the request fails

**Comment by g1tman** [comment]
@callmekatootie You are not able to reproduce this?
Make sure to throttle the connection.

**Comment by callmekatootie** [comment]
Was able to reproduce after throttling. However, I had to click in succession a number of times - I do not see the use case here and this will not be able to take this as a valid bug (as in, I do not see the action that causes the issue to be a valid action to warrant a bug fix)

**Comment by g1tman** [comment]
@callmekatootie Yeah it is not very likely to occur for most users.

The possible scenario where user may experience this maybe-
When a user has slow network, they tend to click on the same link again and again after they dont see any response.
