### ISSUE TITLE
No way to see the available options for COMPANY ATTRIBUTES filters

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#384]
### Steps to Reproduce

1. Open 'https://skill-search.topcoder-dev.com'  web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on 'Add Filter' and add all the available options in the 'COMPANY ATTRIBUTES' filters
5. Click Done in the modal dialog
6. On Search tab, click in the 'isAvailable' or  filter text box
7. User has no option to see what options are valid for 'isAvailable' filter 

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 11 43 03 PM" src="https://user-images.githubusercontent.com/5712602/87253513-7af2e300-c499-11ea-81a5-b1b6225bfe5c.png">

### Current Results
No way to see the available options for COMPANY ATTRIBUTES filters.
User has no option to see what options are valid for 'isAvailable' filter - whether it's true/false or yes/no.
Same issue with other filters like 'On internship' etc.

### Expected Results
Clicking inside the company attribute filters should show the list of options available for that filter

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
you need to type first - which searches for the filter you can set
