### ISSUE TITLE
While Going To Group Page & Returning Back To Filter Page, Selected additional Filter Is Not Showing

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#385]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click Add Filter > select any additional Filter > Then Move To Group Page > Again Return Back To Filter Page Then Observe.

3. See Screencast:-
[29.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909110/29.mp4.zip)

4. Current Result:- While Going To Group Page & Returning Back To Filter Page, Selected additional Filter Is Not Showing

5. Expected Result:- While Going To Group Page & Returning Back To Filter Page, Selected additional Filter Should Show

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
additional filters are indeed reset if user leaves the page - not a bug
