### ISSUE TITLE
[IE11] Switch buttons of "other groups" should be aligned with Switch buttons of "My groups"

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#387]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on "Add to group" button
3. Observe Switch buttons

**Screenshot/screencast:**
![Screenshot_2](https://user-images.githubusercontent.com/26895101/87253688-5c93e400-c4a7-11ea-9fad-b031b73bb554.png)

**Actual Result:**   Switch buttons of "other groups" doesn't align with Switch buttons of "My groups".

**Expected Result:**  Switch buttons of "other groups" should be aligned with Switch buttons of "My groups"

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
cannot reproduce
