### ISSUE TITLE
Selecting a longer Billing Account and company name is not shown properly in the filter

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#388]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ web app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Click on 'Edit' icon to edit a member
5. Now change the company name to 'This is a very very very very long company name' and Billing account to a larger number '413312124133121241331212413312124133121'
6. Save the profile
7. Click on 'Add Filter' and enable 'company name' and 'Billing Account' filters and click Done.
8. Now type in '4133' in the 'Billing account' filter text box, select the available option 
9. Notice the selected account number in the UI.
10. Search for 'This' in the 'Company name' filter and select the name created in previous steps.
11. Notice the box

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-12 at 11 49 16 PM" src="https://user-images.githubusercontent.com/5712602/87253726-218bb380-c49b-11ea-995f-6c365daef0f0.png">

### Current Results
- Long company name with spaces are wrapped but the padding seems less for wrapped names container
- Longer Billing account is overflowing out of the filter container

### Expected Results
- Padding should be correct for wrapped words
- Longer words which can not be wrapped can be shown with ellipsis after selection.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #294
