### ISSUE TITLE
While Clicking To Go Back Arrow key Its Showing An Error Message

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#389]
1. Go To https://skill-search.topcoder-dev.com/

2. select topcoder > Click On Another Icon Near filter > Click Go Back Arrow key Then Observe.

3. See Screencast & Screenshot:-
[30.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909162/30.mp4.zip)
![30](https://user-images.githubusercontent.com/42583358/87253891-6b28ce00-c49c-11ea-9722-d50e709111e8.png)

4. Current Result:- While Clicking To Go Back Arrow key Its Showing An Error Message

5. Expected Result:- While Clicking To Go Back Arrow key It Should Not Show Any Error Message

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
cannot reproduce
