### ISSUE TITLE
[$10] Add Filter opacity is too low

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#39]
![image](https://user-images.githubusercontent.com/42398485/87247245-4ab73000-c418-11ea-99f4-64c0f0841d9e.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click 'Add Filter'

**Actual Result:** Add Filter opacity is too low

**Expected Result:** Should visible the content more

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
valid issue

**Comment by callmekatootie** [comment]
Expected: Add Filter modal opacity should be equal to the one set on the Edit Profile modal opacity

**Comment by callmekatootie** [comment]
Resolved
