### ISSUE TITLE
[Common] Can create Groups with leading and trailing spaces

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#390]
https://take.ms/ddKwL

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group) or Add Group option in Tab 01 (Search)
3. Enter 'group' and click Create
4. Enter 'GROUP' and click Create
5. Enter ' group' and click Create
6. Enter 'group ' and click Create

**Actual Result:** Can create Groups with leading and trailing spaces

**Expected Result:** Should trim the leading and trailing spaces

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #34
