### ISSUE TITLE
[Bug Hunt]Special characters are accepted for all the fields

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#391]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with data.

3.Navigate to 2nd tab
![image](https://user-images.githubusercontent.com/68163678/87253919-8c89ba00-c49c-11ea-87a4-2a363abdd428.png)
4.Click edit button for any profile
![image](https://user-images.githubusercontent.com/68163678/87253938-9f9c8a00-c49c-11ea-9aec-eba5cd7f155e.png)
5.Enter special characters for all fields.
![image](https://user-images.githubusercontent.com/68163678/87253972-c2c73980-c49c-11ea-90d2-b9e8c57e5710.png)
6.Click on Save changes

**Actual result:**
Special characters are accepted for all the fields
**Expected result:**
Special characters should not be accepted for all the fields

**Device/Browser/OS:**
Laptop
Google Chrome(Version 83.0.4103.116)
Windows10

**Login credential used:**
tonyj\appirio123

**Comment by callmekatootie** [comment]
duplicate #114
