### ISSUE TITLE
Toggle button state gets changed after search

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/u-bahn-app#394]
[bug1.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909204/bug1.zip)

**Reproduction Steps:**

- Open the Application https://skill-search.topcoder-dev.com/
- Click Topcoder > Go to Tab 01 (Search)
- Click On 'Add Filters'
- Select any 'Company Attributes' and toggle the button ON
- Now search the same attribute in the search bar
- Observe the toggle button

**Actual Result:** Toggle state gets change after search.

**Expected Result:** Toggle state should not change after search.

**Device/OS:** macOS 10.12.6

**Browser Information:** Chrome 83.0.4103.116

**Comment by callmekatootie** [comment]
duplicate #141
