### ISSUE TITLE
After Uploading File Unable To See While Searching With File Name Its Showing An Error Message

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#395]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder > Click On Icon Upload > Click Close > Then Go To Search Field & Try To Search Then Observe.

3. See Screencast & Screenshot:-
[31.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909226/31.mp4.zip)
![31](https://user-images.githubusercontent.com/42583358/87254349-aa0c5300-c49f-11ea-88c5-03d65bd9208b.png)

4. Current Result:- After Uploading File Unable To See While Searching With File Name Its Showing An Error Message

5. Expected Result:- After Uploading File Unable To See While Searching With File Name It Should Not Show Any Error Message & Should Show File.

6. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

7. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
you need to search for the user that you attempted to create or update
