### ISSUE TITLE
[Bug Hunt] User is not able to enter anything for Achievement section in edit mode

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#397]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with data.
![image](https://user-images.githubusercontent.com/68163678/87254441-50f0ef00-c4a0-11ea-937a-0f25730b45f2.png)

3.Click on Edit button of any profile.
![image](https://user-images.githubusercontent.com/68163678/87254447-5d754780-c4a0-11ea-9f31-46deb1af3c05.png)

4.Navigate to Achievement section.
![image](https://user-images.githubusercontent.com/68163678/87254458-741b9e80-c4a0-11ea-8656-189678415733.png)
5.Verify user is not able to enter anything in Achievement section

Actual result:
user is not able to enter anything in Achievement section
Expected result:
User should be able to Edit Achievements.

Device/Browser/OS:
Laptop
IE 11 (Version:11.0.9600.19400)
Windows10

Login credential used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
achievement is read only for now
