### ISSUE TITLE
[BUG HUNT] Multiple set of requests.

### ISSUE THREAD

**Issue by yogigachinmath** [topcoder-platform/u-bahn-app#398]
[BUG HUNT] To Reproduce follow the below steps or watch the video attached.

In the groups tab, on click of any group, The data is fetched, 
If Pressed again on same group, The data is fetched again.

[issue1.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909261/issue1.zip)

**Comment by callmekatootie** [comment]
duplicate #165
