### ISSUE TITLE
member can not be seen or found after removing all the tagged groups from a member

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#399]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“  app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Go to Groups tab
5. Select a group which has at least one member
6. Now remove all the tagged groups from the member
7. Now refresh the page or navigate to another tab and come back to Groups tab
8. Try to find out the member whose tagged groups were removed in step 6

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-13 at 12 41 05 AM" src="https://user-images.githubusercontent.com/5712602/87254666-b2fe2400-c4a1-11ea-9c55-2d540baeec33.png">

### Current Results
member can not be seen or found after removing all the tagged groups from a member

### Expected Results
Ungroups members can also seen somewhere there can be an ungrouped tab which shows member s without any group.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
valid behaviour - in this tab, you are getting members of a group. you removed all groups from the member and thus you cannot get that user again - you will have to go to first tab and add the group again to the user
