### ISSUE TITLE
Escape button on keyboard is not working on add filter page

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#40]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. escape button doesnt work on this page on click filter option, cant close down add filters page

Current results
escape button doesnt work on this page

Expected results

escape button should close down the filter page

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 6 48 43 PM](https://user-images.githubusercontent.com/57220292/87247250-56cedc00-c470-11ea-9796-44c4199a3875.png)

**Comment by callmekatootie** [comment]
not a valid issue. There is no requirement to have ESC close the modal
