### ISSUE TITLE
[Bug Hunt] Flickering issue on IE browser

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#400]
**Steps:**
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with data.
![image](https://user-images.githubusercontent.com/68163678/87254704-0a9c8f80-c4a2-11ea-9f72-d6a1fd82786f.png)

3.Reload the page and verify below page flickers for few seconds
![image](https://user-images.githubusercontent.com/68163678/87254718-26a03100-c4a2-11ea-9bd0-f7411ea0e091.png)

**Actual result:**
Above page flickers while reloading
**Expected result:**
No flickering should be displayed

**Device/Browser/OS:**
Laptop
IE 11 (Version:11.0.9600.19400)
Windows10

**Login credential used:**
tonyj\appirio123

**Comment by callmekatootie** [comment]
not a bug for reasons mentioned here -0 #341

**Comment by komal123s** [comment]
But this issue is observed everytime when user clicks reload button on IE browser.
