### ISSUE TITLE
[BUG HUNT] Search Talent and Keyword - No Validation.

### ISSUE THREAD

**Issue by yogigachinmath** [topcoder-platform/u-bahn-app#401]
[BUG HUNT] To Reproduce follow the below steps or watch the video attached.

On the main page, The search bar has no Validation or any Debouncing is Provided. 

[issue2.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909276/issue2.zip)

**Comment by callmekatootie** [comment]
not enough details provided. currently, you have to press enter key to search but it appears that in your case, it searches on input itself...
