### ISSUE TITLE
Tagging a member into a new group and saving doesn't update the member count in the left hand side showing group name and member count

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#402]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“  app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Navigate to Groups tab
5. Notice the number of member in one of the groups
6. Click on one of the group names
7. Now add one more group to a member of the group
8. Click on Done in 'Add to group' modal dialog
9. Notice the number of members in the group tagged in the step 7
10. Click on the group name tagged in step 7
11. Notice the new member being added to the group 
12. notice the member count in the left hand showing group name and member count and the members showing up in the group

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-13 at 12 47 08 AM" src="https://user-images.githubusercontent.com/5712602/87254825-39673580-c4a3-11ea-94b4-b8f7c7c50739.png">

[member_count_grous.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909281/member_count_grous.mov.zip)

### Current Results
Tagging a member into a new group and saving doesn't update the member count in the left hand side showing group name and member count

### Expected Results
Tagging a member into a new group and saving should update the member count in the left hand side groups 

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
member count is static. you need to visit the page again to see it updated
