### ISSUE TITLE
Create a new group and assign a profile to it won't show that group on the group list

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#405]
https://take.ms/PG35C

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Select a group and click Edit profile and create a new group and assign a profile to it
4. Check the group list

**Actual Result:** Create a new group and assign a profile to it won't show that group on the group list

**Expected Result:** Should display the group on the group list

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #187

**Comment by callmekatootie** [comment]
actually - this is not a bug - the group will not show up immediately - the group list is static. you need to refresh the page or visit it again from another tab
