### ISSUE TITLE
[BUG HUNT] No proper Error handling.

### ISSUE THREAD

**Issue by yogigachinmath** [topcoder-platform/u-bahn-app#406]
[BUG HUNT] To Reproduce follow the below steps or watch the video attached.

In the group tab, while creating a group with already present group name, The backend server is providing the 409 error.
But no error handling in the application.
Same issue in Edit profile -> add group.
[issue4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4909294/issue4.zip)

**Comment by callmekatootie** [comment]
duplicate #116
