### ISSUE TITLE
"Create" button on Groups tab should be enabled only after User has entered some characters in the 'Search or Create Group' text box

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#407]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“  app
2. Login with tonyj /appirio123
3. Select topcoder as organization
4. Navigate to Groups tab
5. Mouse hover over Create button
6. Click on Create button
7. Notice the result

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-13 at 1 04 05 AM" src="https://user-images.githubusercontent.com/5712602/87255054-0f167780-c4a5-11ea-8d39-89a964d1597c.png">

### Current Results
Nothing happens when User clicks on the 'Create' button without entering anything in the text box.
With the current design, It's confusing.

### Expected Results
"Create" button on Groups tab should be enabled only after User has entered some characters in the 'Search or Create Group' text box.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #60
