### ISSUE TITLE
"Saving changes, Please wait" should not be displayed inside button

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#409]
**Steps:**
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Click on edit icon 
3) In Edit profile page, Do some change and save.
Observe

**Current Result :**
"Saving changes, Please wait" is displaying in buttom.

**Expected result:**
"Saving changes, Please wait" should not be displayed inside buttom.

**Browser** : IE 11.900.18362.0
**OS:** Windows 10

Screenshot 
![31](https://user-images.githubusercontent.com/51490878/87255093-746a6880-c4a5-11ea-98f9-06828764933f.png)

**Comment by coderkid19** [comment]
![IE_version_11 900 18362 0](https://user-images.githubusercontent.com/51490878/87255116-97951800-c4a5-11ea-8bd7-7c7df45d0cf3.png)

**Comment by callmekatootie** [comment]
not a bug
