### ISSUE TITLE
Console errors displayed when user tries to save a profile without 'CUSTOM ATTRIBUTES' data

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#411]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 02 (Group)
3. Select a group and click Edit profile and remove all the 'CUSTOM ATTRIBUTES' data
4. Click Save

**Actual Result:** Console errors displayed when user tries to save a profile without 'CUSTOM ATTRIBUTES' data

**Expected Result:** Should NOT display any errors

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #148
