### ISSUE TITLE
[Bug Hunt] User edit window is not scrollable

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#412]
![not_scroll](https://user-images.githubusercontent.com/68201321/87255202-3ae62d00-c4a6-11ea-9d07-782cfa60a1b3.png)

User edit window is not scrollable and user can not see all the option.

Steps to reproduce:
1. Click edit button beside available status on any user and the edit window will come up.

**Comment by callmekatootie** [comment]
duplicate #17
