### ISSUE TITLE
[Bug Hunt] Filtering using experience attribute is showing suggestions abruptly and not legitimate

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#413]
Filter using experience(in months) is showing abrupt suggestions which are not practical. Sometime it is showing 16 digit number as experience in months which should not be more than 500 months.

Reproduction steps:
1. Type '1'. will see different options.
2. type '11' will see only 3 digit suggestion.
3. type '123' will see ~16digit suggestion.
![exp_filter](https://user-images.githubusercontent.com/68201321/87255562-82ba8380-c4a9-11ea-93da-67a10fc7209f.png)

**Comment by callmekatootie** [comment]
not a bug - it shows the values that match the search text... in your case the long digit was not shown initially because there were other closer matching ones before it
