### ISSUE TITLE
[Bug Hunt] Filtering using location is showing wrong suggestion

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#414]
Issues:
1. Showing 'EDIT' as a location suggestion.
2. All the suggestion should follow same case, all should be either in title case or upper case and not mixed. For, e.g. 'EDIT' is showing upper case whereas other options are showing in different case.
3. If a letter is pressed then the suggestion should start with that letter and should not show any random suggestion that contains the letter. For e.g. if e is pressed then suggestions should be shown starting with e and not a/b like Athenamouth/Bergstrombury.

Reproduction steps:
1. Type e and see the suggestions. Then type 'el' and see.
![filter_location1](https://user-images.githubusercontent.com/68201321/87255828-b5fe1200-c4ab-11ea-9cd6-81506fffa530.png)
![filter_location2](https://user-images.githubusercontent.com/68201321/87255837-cadaa580-c4ab-11ea-8c69-26d5fc40504b.png)

**Comment by callmekatootie** [comment]
the filter values are actual values present for the user... it is dynamically fetched basically... so EDIT and others are values set on some user and thus you can see it
