### ISSUE TITLE
[Bug Hunt] Discrepancy in suggestions by company attribute location and general attribute location

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#415]
1. type lond in general attribute, only one suggestion will come. Correct. But Try same thing using company attribute location, it will show repeated entries on London.
2. Select a location in general attribute location where no user profile is there and select a location in company attributes where a user profile exists. It will show no result is found even if a correct location is selected in company attribute.

Reproduction steps:
1. Type 'lond' in general attribute location. It will show London.
2. Come to company attribute location field. Type 'lond'. It will show two London as suggestion i.e. duplicate entries of london will be shown.
3. Suppose there is a profile with location London. Select London in general attribute. Profile will be shown correctly.
4. Now select same in company attribute. Will show correctly.
5. Select other locations(where no profile is present). Will show correctly.
6. Remove London from general attribute but not from company attribute. Now it will show no result found even if London value still presents in company attribute.

![location_repeation](https://user-images.githubusercontent.com/68201321/87256019-1ccffb00-c4ad-11ea-953d-c0de816aad96.png)
![location_noUser](https://user-images.githubusercontent.com/68201321/87256401-c44e2d00-c4af-11ea-90ad-5c3b78015b11.png)
![location_nowShowing](https://user-images.githubusercontent.com/68201321/87256416-f9f31600-c4af-11ea-9b6a-918c50b62673.png)

**Comment by callmekatootie** [comment]
not a bug. One is a static filter (values are known beforehand) The other is dynamic and it's a custom attribute - the two are not the same... it is just a coincidence they were called the same...
