### ISSUE TITLE
[Bug Hunt] Try creating an existing group. Would be stuck.

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#416]
Try creating a duplicate group. Would be stuck and showing "Creating".

Reproduction steps:
1. Create a group, for e.g. 'abcdxyz'.
2. Try create a new group with same name i.e. 'abcdxyz'.
3. Would be showing "Creating".
4. Remove the group name and try with different name. Click on the creating button, would be stuck.

![image](https://user-images.githubusercontent.com/68201321/87256488-ba78f980-c4b0-11ea-99b8-1d8b8f4b1cad.png)

**Comment by callmekatootie** [comment]
duplicate #93
