### ISSUE TITLE
[Bug Hunt] Group member count is not getting updated after removing a user

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#417]
After removing some user the group member count is still showing same.

Reproduction steps :
1. Select any group member. 
2. Delete the group name from his profile.
3. Check the group count before and after deleting. Would be same.

![wrong_groupcount](https://user-images.githubusercontent.com/68201321/87256705-a46c3880-c4b2-11ea-9d1b-292148734a2c.png)

**Comment by callmekatootie** [comment]
group member count is static value - you need to load page again to see latest count
