### ISSUE TITLE
[Bug Hunt] isAvailable can be selected true and false at same time

### ISSUE THREAD

**Issue by nilatpalfree** [topcoder-platform/u-bahn-app#418]
isAvailable should be selected either yes or no. Selecting both or none is default case. Same applicable for 'On internship'.

Reproduction steps:
1. select isAvailable as yes.
2. then select isAvailable as no.

![isAvailable](https://user-images.githubusercontent.com/68201321/87256967-afc06380-c4b4-11ea-8035-2fe535a1c1ce.png)

**Comment by callmekatootie** [comment]
this is a custom attribute - it is just a coincidence that it is matching the primary availability attribute...
