### ISSUE TITLE
[BugHunt] Profile logo-Logout option is not hiding while clicking anywhere in the page.

### ISSUE THREAD

**Issue by Jacksug** [topcoder-platform/u-bahn-app#419]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with credentials

3.Click on Profile logo. Logout option is shown.

4. Click on anywhere outside the page. Logout option is not getting hided.

Actual result:
Logout option is not getting hided after clicking anywhere in the page once its selected,

Expected result:
Logout option should get hided

ScreenCast:

![Profilelogo](https://user-images.githubusercontent.com/67252301/87269773-ce8e1c80-c4eb-11ea-8950-c52a963402d4.jpg)

Device/Browser/OS:
Laptop
Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows10

Login credential used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
duplicate #69
