### ISSUE TITLE
[Bug Hunt] User able to read the text behind the Filter window when its opened

### ISSUE THREAD

**Issue by Jacksug** [topcoder-platform/u-bahn-app#420]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with credentials

3.Click on Add Profile

4. Filter panel get opened. Its showing the text behind the Filter window

Actual result:
Filter panel is showing the text behind when its open

Expected result:
It should not show the text behind it.

ScreenCast:

![FilterPanel_Background text](https://user-images.githubusercontent.com/67252301/87270204-12355600-c4ed-11ea-8ed7-6081becb6cdd.jpg)

Device/Browser/OS:
Laptop
Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows10

Login credential used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
duplicate #39
