### ISSUE TITLE
[Bug Hunt] Edit Member Popup- close button is not available 

### ISSUE THREAD

**Issue by Jacksug** [topcoder-platform/u-bahn-app#422]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with credentials

3.Click on Edit member icon of any member

4. Close button(x) is not available for Edit member popup

Actual result:

Close button(x) is not available for Edit member popup

Expected result:

Close button(x) should be available for Edit member popup

ScreenCast:

[EditGroup.zip](https://github.com/topcoder-platform/u-bahn-app/files/4910648/EditGroup.zip)

Device/Browser/OS:
Laptop
Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows10

Login credential used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
duplicate #17
