### ISSUE TITLE
[Bug Hunt] User edit window is not scrollable and user can not see all the option.

### ISSUE THREAD

**Issue by chetaneha520** [topcoder-platform/u-bahn-app#423]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with credentials

3.Click on Edit User

Actual result:
User edit window is not scrollable and user can not see all the option.

Expected result:
User edit window  should be  scrollable and user can see all the option.

Device/Browser/OS:
Laptop
![Screenshot (19)](https://user-images.githubusercontent.com/62207282/87271755-d650bf80-c4f1-11ea-9ce2-f6eadcbdbdfc.png)

Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows10

Login credential used:
tonyj\appirio123

**Comment by callmekatootie** [comment]
duplicate #17
