### ISSUE TITLE
[Bug hunt] - Logout button is not aligned with Profile icon dropdown

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#424]
Steps:-

1. Enter the URL : https://skill-search.topcoder-dev.com/
2. Login with credentials  tonyj / appirio123
3. Select Topcoder
4. Click on Logout icon

Issue : Logout button is not aligned with Profile icon dropdown
Expected Result : Logout button should get linked with profile icon dropdown

![image](https://user-images.githubusercontent.com/61318135/87272532-23ce2c00-c4f4-11ea-9f46-456d30f12b9e.png)

**Comment by callmekatootie** [comment]
not a bug. the alignment is correct

**Comment by ab668685** [comment]
So the logout dropdown shouldnot be linked with profile icon?

**Comment by callmekatootie** [comment]
I mean to say the alignment is fine - the distance between the dropdown and the parent element is fine. This is not a bug
