### ISSUE TITLE
[Bug Hunt] In Availability 2 options selected

### ISSUE THREAD

**Issue by chetaneha520** [topcoder-platform/u-bahn-app#425]
Steps:
1.Navigate to https://skill-search.topcoder-dev.com/

2.Login with credentials

3. Go  to Availability

4. Select Available or Unavailable

Actual result:
Available and Unavailable both option selected
Expected result:
Only one option should be selected

Device/Browser/OS:
Laptop
Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows10

Login credential used:
tonyj\appirio123
![Annotation 2020-07-13 103707](https://user-images.githubusercontent.com/62207282/87272764-de5e2e80-c4f4-11ea-83b2-0dcfc8a918af.png)

**Comment by callmekatootie** [comment]
not a bug for reasons mentioned in #36
