### ISSUE TITLE
[Bug hunt] - Unable to add skills in Profile edit

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#427]
Steps:-
Browser : Chrome Version 83.0.4103.116 
Windows -10

 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4.  Select any profile Carroll Vandervort ,which is in available status.
5. Click on Edit.
6. Try to add skills - java

Issue : Unable to add skills in Profile edit
Expected Result : Should be able to add skills in Profile edit.
 

![image](https://user-images.githubusercontent.com/61318135/87273042-b1f6e200-c4f5-11ea-952f-c08a1a4f070b.png)

**Comment by callmekatootie** [comment]
cannot reproduce - can see dropdown show up

**Comment by ab668685** [comment]
This is a bug.Please find above screenshot which donot have any dropdown when "java" subject is mentioned. 
As compared todays screenshot.This issue has been fixed now.


![image](https://user-images.githubusercontent.com/61318135/87881831-80ac7380-ca19-11ea-8d07-6cdfc1947cff.png)

**Comment by callmekatootie** [comment]
We did not push any fix - we use a third party service for that dropdown values and most likely it was facing issues which is why, when you tested, you did not get any suggestions. Or maybe a network issue.

I cannot reproduce it right now and thus I cannot take it as a bug
