### ISSUE TITLE
[Bug Hunt] In Add filter - Close button & Filter button cuts off. Unable to close Add filter

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#428]
Browser : Chrome Version 83.0.4103.116 
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. Click on + Add filter button
 
Issue : Close button & Filter button cuts off.
Expected Result : Close button & Filter button should display. Should be able to close Add filter
![image](https://user-images.githubusercontent.com/61318135/87273532-fe8eed00-c4f6-11ea-9854-88090802f876.png)

![image](https://user-images.githubusercontent.com/61318135/87273680-6a715580-c4f7-11ea-93c8-3d0a31eef60c.png)

**Comment by callmekatootie** [comment]
duplicate #17
