### ISSUE TITLE
[Upload tab] Layout UI issue

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#43]
**Reproduction Steps:**
1. Open the application 
2. Click on "Upload" tab and observe background

**Screenshot/screencast:**
https://prnt.sc/tgbp34

**Actual Result:** Background is overlapped with background profiles

**Expected Result:** Should not like that

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
Checked the design. Matches. Not a valid issue.
