### ISSUE TITLE
favicon.ico for the web app is the default react icon

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#430]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“  app
2. Notice the U-Bahn logo on the login page
3. Login with tonyj /appirio123
4. Notice the web app's icon in the browser tab

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-13 at 11 11 38 AM" src="https://user-images.githubusercontent.com/5712602/87274786-35b2cd80-c4fa-11ea-8bd1-ffb2a35aa3ac.png">
<img width="1416" alt="Screenshot 2020-07-13 at 11 12 06 AM" src="https://user-images.githubusercontent.com/5712602/87274794-39deeb00-c4fa-11ea-8e62-2b63d974d8d2.png">

### Current Results
favicon.ico for the web app is the default react icon

### Expected Results
favicon.ico should be changed to the web app's icon as shown in login page.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
Will take this as a bug since we do need to update the favicon

**Comment by wdprice** [comment]
@callmekatootie replace with a TC logo. While we're at it, use a TC logo in place of the word "U-Bahn" in the header.

**Comment by callmekatootie** [comment]
@wdprice This update needs to be carried out in the Auth0 configuration (the one shown in the login page)

**Comment by callmekatootie** [comment]
And if Topcoder already has a favicon that I can use, let me know too

**Comment by wdprice** [comment]
@cwdcwd - will need your guidance on updating the favicon in Auth0.

**Comment by callmekatootie** [comment]
Favicon's updated. Note that the icon in the login page needs to be updated through Auth0's configuration
