### ISSUE TITLE
On mouse hover / select  in Add filter - button is not highlighted

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#431]
Browser : Chrome Version 83.0.4103.116 
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. Mouse hover on + Add Filter 
 
Issue : On mouse hover / select  in Add filter - button is not highlighted
Expected Result :  On mouse hover in Add filter ,button should get highlighted

[Video.zip](https://github.com/topcoder-platform/u-bahn-app/files/4910823/Video.zip)

**Comment by callmekatootie** [comment]
duplicate #188
