### ISSUE TITLE
Switch buttons of "General attributes" should be aligned with Switch buttons of "Company attributes"

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#432]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on "Add Filter" button -> Show Add Filters popup
3. Observe Switch buttons

**Screenshot/screencast:**
![Screenshot_3](https://user-images.githubusercontent.com/26895101/87275678-d6a88500-c508-11ea-9776-5d8dd92c61cc.png)

**Actual Result:**   Switch buttons of "General attributes" doesn't align with Switch buttons of "Company attributes"

**Expected Result:**  Switch buttons of "General attributes" should be aligned with Switch buttons of "Company attributes"

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11, Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
cannot reproduce

**Comment by HongHT** [comment]
Hi @callmekatootie - I can still reproduce it. 
https://drive.google.com/drive/folders/1iOY7Bzc_W2q5faFxAkngxS1lp0r4RsYU

**Comment by callmekatootie** [comment]
Got it. Thank you for the video.

The issue here is because COMPANY ATTRIBUTES has a scroll bar, but GENERAL ATTRIBUTES does not. It is expected behaviour and not a bug
