### ISSUE TITLE
Sort the list again with the same sort option after changing profile data won't display the correct order

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#433]
https://take.ms/8wHGm

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Sort the List by Availability
4. Change the toggle to 'Unavailable'
5. Sort the List by Availability again
6. Do the name for Sort by name and change the name and sort again with the Name
7. Do the same for locations

**Actual Result:** Sort the list again with the same sort option after changing profile data won't display the correct order

**Expected Result:** Should display the correct order, Changing to another sort option and select the current selection again will add extra steps

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
sort order did not change and thus no new search is performed.

not a bug
