### ISSUE TITLE
[Bug Hunt]IE11 - A horizontal scroll appears with white spacing

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#434]
Browser : IE 11
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
4. View the page

Issue : A horizontal scroll appears with white spacing
Expected Result: Horizontal scroll should not appear.
 

![image](https://user-images.githubusercontent.com/61318135/87276111-49abfe80-c4fd-11ea-96af-e4243b7cfec8.png)

![image](https://user-images.githubusercontent.com/61318135/87276180-6d6f4480-c4fd-11ea-9c28-68c0b26b67ed.png)

**Comment by callmekatootie** [comment]
not a bug - the sort order does not change and that does not trigger a new search. Expected behaviour

**Comment by ab668685** [comment]
This is a UI issue.As white space appears on scroll.This bug is not related to functionality

**Comment by callmekatootie** [comment]
Sorry - I think github added the comment on the wrong ticket.

This one is duplicate of #62
