### ISSUE TITLE
Inconsistent size of the "Create" button in app

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#435]
**Reproduction Steps:**
1. Open the application 
2. On second tab, observe "Create" button
3. Click on any My Groups 
4. Click on any "Add to group" -> Observe "Create" button
5. Compare the "Create" button in step 2 and step 4

**Screenshot/screencast:**

![Screenshot_4](https://user-images.githubusercontent.com/26895101/87276518-b37ed500-c50a-11ea-8071-3bdcb86a7b8b.png)

**Actual Result:** Inconsistent size of the "Create" button in app

**Expected Result:** Should consistent size of the "Create" button in app

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
not a bug
