### ISSUE TITLE
[Bug Hunt] -  Company attributes -title & isAvailable text not written in capital

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#436]
Browser : Chrome Version 83.0.4103.116 
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. Click on Add Filter
5. Goto Company attributes

Issue : title & isAvailable text not written in capital
Expected Result :  title & isAvailable text should start with Capital.

![image](https://user-images.githubusercontent.com/61318135/87277317-af998580-c4ff-11ea-9cbf-b608903fd0d1.png)

**Comment by callmekatootie** [comment]
those are custom attributes - you can create any custom attribute and the casing is not corrected through CSS - it is displayed as is.
