### ISSUE TITLE
[$10] CSV File uploads dont work

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#439]
##Steps:

	1. Go to https://skill-search.topcoder-dev.com/ and login
	2. Go to third tab (Bulk Upload tab)
	3. See instructions written there (Screenshot Attached)
	4. Upload a CSV file
	5. Observe error

##Actual Result:

	Shows error that only XLS and CSV are allowed. (Screenshot Attached)

##Expected Result:
	
	CSV should work same as XLS uploads

##Screenshot/Video:
![Screenshot from 2020-07-13 12-34-05](https://user-images.githubusercontent.com/32861951/87280147-6fda9a00-c50f-11ea-95ee-be6492cdaad2.png)
![Screenshot from 2020-07-13 12-34-22](https://user-images.githubusercontent.com/32861951/87280154-71a45d80-c50f-11ea-99aa-0f50f6f6ab78.png)

##Attachments:

Sample CSV file
[business-price-indexes-march-2020-quarter-corrections-to-previously-published-statistics.zip](https://github.com/topcoder-platform/u-bahn-app/files/4911150/business-price-indexes-march-2020-quarter-corrections-to-previously-published-statistics.zip)

	
Browser: Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
valid bug

**Comment by wdprice** [comment]
If this is a major issue, we can adjust language in the front end to say XLS only until we roll out CSV support later.

@callmekatootie let me know when we have estimate on it.

**Comment by callmekatootie** [comment]
@wdprice Minor issue - the file type was not in the white list. This is now resolved.

**Comment by callmekatootie** [comment]
Also - verified that processor is able to work with CSV files - uploaded a CSV file and it updated the data successfully
