### ISSUE TITLE
Available & Unavailable Both Options Are Highlighting

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#44]
1.  Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click On Location Dropdown

4. Select Available Then Unavailable & Observe.

5. See Screencast & Screenshot:-
[2.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908552/2.mp4.zip)
![2](https://user-images.githubusercontent.com/42583358/87247255-5afaf980-c470-11ea-8886-6d370a844086.png)

6. Current Result:- Available & Unavailable Both Options Are Highlighting

7. Expected Result:- Available & Unavailable Both Options Should Not Highlight Should Highlight Only One.

8. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

9. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
same as #36
