### ISSUE TITLE
[Bug Hunt] Blank fields are accepted for first name and last name but on saving same Name is displayed

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#440]
Steps to reproduce:
1.Launch the url https://skill-search.topcoder-dev.com/
2.Login with credentials :-tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87280785-26d71580-c510-11ea-8dee-34db50eac8df.png)

3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87280851-3c4c3f80-c510-11ea-89aa-8b0d8fdacd88.png)
4.Verify various profiles are displayed
![image](https://user-images.githubusercontent.com/68163678/87280923-52f29680-c510-11ea-841f-88597ae1cd27.png)

5.Click on Edit button of any profile.
Here I have edited Brady Swift profile.
![image](https://user-images.githubusercontent.com/68163678/87281042-71f12880-c510-11ea-89c3-af2b64776137.png)
6.Now remove text of all fields
![image](https://user-images.githubusercontent.com/68163678/87281147-8d5c3380-c510-11ea-8e3e-d67cc994ad7d.png)
7.Now click on Save (Due to another defect Save option is not displayed but I have done it by opening it in vertical mode)
![image](https://user-images.githubusercontent.com/68163678/87281447-ddd39100-c510-11ea-9320-3784d77f1045.png)
8.Verify user profile is updated with same name but user have updated it to blank.
![image](https://user-images.githubusercontent.com/68163678/87281677-18d5c480-c511-11ea-8ae4-ca98a27e3439.png)

Actual result:
When user have saved profile with blank for first name and last name then also name is not removed.
Expected result:
User should not be allowed to Save with blank field ,an inline error message should be displayed.

Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #148
