### ISSUE TITLE
[Bug Hunt]User is able to remove Groups of profile without entering in Edit mode

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#441]
Steps to reproduce:
1.Launch the url https://skill-search.topcoder-dev.com/
2.Login with credentials :-tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87282913-6141b200-c512-11ea-9ab8-33712bb0d8a1.png)

3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87282940-69015680-c512-11ea-8185-e025961600fd.png)

4.Verify various profiles are displayed
![image](https://user-images.githubusercontent.com/68163678/87282968-71599180-c512-11ea-9312-54b6b0b446c1.png)

5.Now remove groups of any profile without clicking on Edit button.
Here I have Used Brady Swift profile.
![image](https://user-images.githubusercontent.com/68163678/87283106-95b56e00-c512-11ea-8393-2ce8b813721f.png)
Have removed all groups of profile
![image](https://user-images.githubusercontent.com/68163678/87283137-9ea63f80-c512-11ea-9281-a7d199e94738.png)

Actual result:
Without clicking on Edit button user is able to remove Groups from profiles
Expected result:
User should not be allowed to remove Groups from profile without going to Edit mode
Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
not a bug - that's a feature
