### ISSUE TITLE
[Bug Hunt]User is able to Add groups to the profile without entering in Edit button

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#442]
Steps to reproduce:
1.Launch the url https://skill-search.topcoder-dev.com/
2.Login with credentials :-tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87284137-a9150900-c513-11ea-89fc-360bcfa1ede2.png)

3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87284154-ad412680-c513-11ea-97b4-ce0ea774a8f2.png)

4.Verify various profiles are displayed
![image](https://user-images.githubusercontent.com/68163678/87284196-b8945200-c513-11ea-828f-c6756494eee4.png)

5.Now click on + button for Groups
Here I have done it for Braeden Kuhic profile
![image](https://user-images.githubusercontent.com/68163678/87284413-f5f8df80-c513-11ea-849a-008cf10b775c.png)

6.Verify Add to Group Popup is displayed
![image](https://user-images.githubusercontent.com/68163678/87284507-132dae00-c514-11ea-8bde-b193f1f83ab4.png)
7.Select any group from the list and click on Done
![image](https://user-images.githubusercontent.com/68163678/87284702-4b34f100-c514-11ea-8f71-366618dc3b05.png)
![image](https://user-images.githubusercontent.com/68163678/87284712-4f610e80-c514-11ea-8812-3a5d0124e7a9.png)
8.Verify Groups are added to the profile.
![image](https://user-images.githubusercontent.com/68163678/87284755-5c7dfd80-c514-11ea-9d8b-8b0e4f232323.png)

Actual result:
Without clicking on Edit button user is able to Add Groups to profiles
Expected result:
User should not be allowed to Add Groups to profile without going to Edit mode
Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
not a bug - that is a feature
