### ISSUE TITLE
[Bug Hunt]Not able to remove and add Achievements for profile

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#443]
Steps to reproduce:
1.Launch the url
2.Login with credential : tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87286575-a536b600-c516-11ea-8faf-b03a8499b1f5.png)

3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87286644-baabe000-c516-11ea-977d-541fc153f2bf.png)
4.Verify various user profiles are displayed.
![image](https://user-images.githubusercontent.com/68163678/87286708-d0b9a080-c516-11ea-8990-92366f856ade.png)
5.Scroll down and select all options for achievements filter
![image](https://user-images.githubusercontent.com/68163678/87286826-f8a90400-c516-11ea-9292-59c38b597452.png)

6.One profile is displayed.(John Doe)
![image](https://user-images.githubusercontent.com/68163678/87286880-078fb680-c517-11ea-87b1-f52cc9a3bcfc.png)
7.Now click on Edit button of Profile.
![image](https://user-images.githubusercontent.com/68163678/87286983-2b52fc80-c517-11ea-8570-2f5ed60a2d23.png)
8.Verify there is no close icon for removing achievements
![image](https://user-images.githubusercontent.com/68163678/87287079-4c1b5200-c517-11ea-8082-14eb2d163219.png)
9.Verify there is no option for adding Achievements

Actual result:
User is not able to remove and add Achievement
Expected result:
User should be able to add and remove from Achievements
Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by komal123s** [comment]
url in 1st step:https://skill-search.topcoder-dev.com/

**Comment by callmekatootie** [comment]
achievements are indeed read only - not a bug. expected.
