### ISSUE TITLE
[Bug Hunt] Search option not working for skills

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#445]
**Steps:**
1.Launch the url
https://skill-search.topcoder-dev.com/
2.Login with credential: tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87287812-2b073100-c518-11ea-8a55-1706c551bd25.png)
3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87287883-42461e80-c518-11ea-85f5-07e4d7b970e6.png)
4.Verify various profiles displayed.
![image](https://user-images.githubusercontent.com/68163678/87287938-538f2b00-c518-11ea-8528-ffd082421a42.png)

5.Now click on edit button for any profile.
Here I have used Braeden Kuhic profile.
![image](https://user-images.githubusercontent.com/68163678/87288053-76214400-c518-11ea-8a85-8afe29740e00.png)

6.Now enter any skill and try to click on search option for Skills field->serach option is not clickable
![image](https://user-images.githubusercontent.com/68163678/87288135-951fd600-c518-11ea-8cec-45eccb4dd0a9.png)
**Actual result:**
Search option is not clickable for Skills
**Expected result:**
Search option should be clickable and if what user is trying to search is not available then suitable message should be displayed
**Device\Browser\OS:**
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
search dropdown should have shown automatically - cannot reproduce at the moment => it is working as expected
