### ISSUE TITLE
[Bug Hunt]U-Bahn banner/icon is nonclickable

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#446]
Browser : Chrome Version 83.0.4103.116 
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. Click on U-Bahn banner/icon

Issue : U-Bahn icon is nonclickable
Expected Result : U-Bahn icon should be clickable.When the icon is clicked application should redirect to Home page.
 
![image](https://user-images.githubusercontent.com/61318135/87289163-ea101c00-c519-11ea-88db-aff2c055b44b.png)

**Comment by callmekatootie** [comment]
not a bug

**Comment by callmekatootie** [comment]
we don't have a home page as such for now
