### ISSUE TITLE
The location filter is unable to handle long strings when minimized

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/u-bahn-app#447]
**Target URL**

https://skill-search.topcoder-dev.com/

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Please enter a long string, for instance, "Z4lD0cP3QE5xKrkFLJNCJaX5gE9VK5c562yXAVYt9a6P4MwjSs9anc58yxn5PK3JpmkV4V8DfyNMRykmPdsA42W9361JqYe4fzQVz22Mv3xhTF5LHqdUuzCMJfIhxDwFLmAv77F01L8TTJPQ2uKUKnD5KUbe0RSlqj7NXxw4c9bcV53sXElNrglPSBGUpyeb8PH0bYKeE7fgiP2Bn7sT6qLVYkojurzgC40BQTeC5YDVyyJl4fslJ6RXyeH41BOwfiPyMRiymfssxoApsypVUxKKdxZXIpXkvHmvvQykdRlPvPCYyZfuEMOFwMMbwnJyPQfBpAppYxBAuUIOhCjTBiRLPPqkbxAznuNnnghNjsPAEcHhGOfKiOzklkHgxKgswMkNRNPKuucjtBhihRFUNNCKBiykWlwtDfoxFvZmXoDRVepwlORmPjXnLORstjTezhXaSZFeXomVtaOcXWJreFGISCYazuHVbohDeQObkPMBceTSIgTvfpoUrVlIzEAhYsjqXwpTHGORSciwSHvAZzTJQkNmhWrWkXuiJSWTMkRqkzzkNfWmndpWoDbXrBEZyFdxJLZzfsxFLoJWcPjolddgfRQTioUCtvbsQRfiIrrcGKfjYNsnYevudWahFmiILtCvcRLRKLmkfiooNXimhTMAtOfyFnYVKwXMmOEQwIkhuLSUFSakpxLgHbBphCrVwHcLTAEgAuTDArykCocBymrffjMsdBYugMimWPpsIDaJQYoILiOAkxUdMFPPveWmuZMgebWQSHZRaQGSihdNyucrDaxRwOApHhoXnDSdctUWfvSCizexIyEGIzeEBEbJipXYrJYDpyjCnnyKrYPPCNdkCmhOKZYZRUNoaWIVAwizapOhGPNdMKenHQXCOQSBNwFbkNdSYASZBRIaKnADXpixcpzqotdbMWHZvUzSDksznJEBDrwlmqfaVAJRfbVOUAHXsSjqgMEovfMbXvtABlNvTVdpYIPpewyBhGwmJFYBwYIyahWFUSxZRqRYJnQLaVDMvRxUpQRFuzrioYZTwwUBFZXUkPBHAMwojRnpWDyMnYYqBMUUXrDLOZJmHBAxChTEpLeCWoKbrLVsMbAycCJMiWMeKKUJPtsgmUOPiXoOJJwBFLgWeJkjzQrtwCcvVETMRovItPpiMguzORvKVTMtIWdkKXDOQbTlpGRHxAKsKCYBANsxfJYQOZnHpvLGkBJcynVfNxNSltigqkfLegvECBgVkhgPluXbvvvAlkcEkXQreNTGHGoIJxSThKqdXSfolHogqnalQwTmIIbsgdhuzSwnhnkuTLiZMnJIpzTNGsHtUVrsDBIpYjJkoejXENSqOZdAQeitDPsbXPtOgjreifpzuMWPvBItcVMvNvziQhKvPnRyMdeRwwWzmRblaRfyVxAUplpgadCTwmPxtuZjDceGiLzkLUxnfoLXKJnQfRQmotcgkAJUDzfRcaiCWJBMaOeTaVvSUMmQeVdRlCtuiIKM".
3. Click outside the textbox.
4. Minimize the filter panel by pressing the down arrow.
5. Maximize again by pressing the down arrow.

**Expected Result**

1. The long string should be present in the textbox.

**Actual Result**

1. The textbox is empty and there is no result.

**Screenshots or screencast**

[The location filter is unable to handle long strings when minimized.zip](https://github.com/topcoder-platform/u-bahn-app/files/4911627/The.location.filter.is.unable.to.handle.long.strings.when.minimized.zip)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 83.0.4103.116 (official build) (32-bit)

**Comment by callmekatootie** [comment]
duplicate #163
