### ISSUE TITLE
[Bug Hunt] Error page is displayed on Back navigation

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#448]
Steps:
1.Launch the url:
https://skill-search.topcoder-dev.com/
2.Login with credential: tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87290705-f5fcdd80-c51b-11ea-9156-869e44e24224.png)
3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87290771-09a84400-c51c-11ea-8578-1d81309b7ed6.png)
4.Verify various profile displayed
![image](https://user-images.githubusercontent.com/68163678/87290797-15940600-c51c-11ea-9127-28381f03eae6.png)

5.Now click on Back navigation->Verify same page is displayed but url changes
![image](https://user-images.githubusercontent.com/68163678/87290839-247ab880-c51c-11ea-8dcf-d6beb8e56ed4.png)
![image](https://user-images.githubusercontent.com/68163678/87291106-7e7b7e00-c51c-11ea-822a-08d8511654d3.png)

6.Now again click on Back button->Verify below error page is displayed.
![image](https://user-images.githubusercontent.com/68163678/87291168-905d2100-c51c-11ea-81a6-b7ce02d3c19d.png)

Actual result:
On back navigation correct page is not displayed
Expected result:
On first click of back navigation below page should be displayed and on second click of back navigation error page should not be displayed
![image](https://user-images.githubusercontent.com/68163678/87291282-b84c8480-c51c-11ea-9ab3-2e8762f05ac6.png)

Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
Checked here - https://community.auth0.com/t/is-it-possible-to-avoid-errors-caused-by-user-pressing-back-button-immediately-after-login/6589/2 - apparently this is expected behaviour

**Comment by komal123s** [comment]
@callmekatootie But in this application we have another page where we select Topcoder. If the user clicks on Back button from the page where we select Topcoder then only the above reason is justified. But here we have a page in between so ideally it should navigate to that page.

**Comment by callmekatootie** [comment]
This one's a Single Page app with just one route - even though you see different pages, you can verify that the url does not change (there's no paths appended at the end of the url either)... So when you press back, it goes to the last visited url which is the auth0's page
