### ISSUE TITLE
[Bug Hunt]Loading text is not consistent through out the application.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#449]
Browser : Chrome Version 83.0.4103.116 
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. Click on Groups icon
5. Click on Create button 
6. View the loading group message

Actual Result : Displayed as LOADING ..... Loading text is not consistent through out the application.

Expected Result : Loading text should be consistent as displayed in users ..It should be Loading...

![image](https://user-images.githubusercontent.com/61318135/87291219-9fdc6a00-c51c-11ea-8ae9-f34fbe7c5df9.png)

**Comment by callmekatootie** [comment]
not a bug.
