### ISSUE TITLE
Wrong notification message for search bar

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/u-bahn-app#451]
**Target URL**

https://skill-search.topcoder-dev.com/

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Please enter the string, "xxxxxx" in the search bar at the top and press enter.

**Expected Result**

1. The notification message should be is, "No users found. Try applying a different search phrase."

**Actual Result**

1. The notification message displayed is, "No users found. Try applying a different filter."

**Screenshots or screencast**

![U-Bahn employee skills search portal](https://user-images.githubusercontent.com/3612991/87292469-7a506000-c51e-11ea-87a5-07f9a14c3528.png)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 83.0.4103.116 (official build) (32-bit)

**Comment by callmekatootie** [comment]
not a bug. the search phrase is also part of the filter
