### ISSUE TITLE
[Bug Hunt]Unable to reset locations

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#452]
Browser : Chrome Version 83.0.4103.116 
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. Goto location .Search New York.Select it.
5. Click on Reset button.
6. View the location filter and reset count.

Issue : Reset count is getting filtered but all locations are not getting displayed in location result.

Expected Result : Post reset all location should get displayed. 

![image](https://user-images.githubusercontent.com/61318135/87292975-40338e00-c51f-11ea-8e8e-e8b277bb6432.png)

**Comment by callmekatootie** [comment]
not a bug - the filter is not selected - only shown. you need to click on the pill to select it

**Comment by ab668685** [comment]
Have you gone through the description of bug?
Already filter was applied . Post reset all the location should display.

**Comment by callmekatootie** [comment]
Gotcha.

So the Reset and the filter count is for active filters. In this case, reset did work - it unselected New York. But it is still shown because the search text has New York in it (search text is not cleared by Reset). You need to click on the Pill for it to be set

**Comment by ab668685** [comment]
Please try above steps it will replicate.Search is already reset.Therefore the filter appears as 0 .As reset was done expected behaviour was all location should display.

**Comment by callmekatootie** [comment]
When you click on reset - it will remove active filters.

In your case, it has. What you are seeing is the search result of the text "new york" - this search text is NOT reset by the reset button. And that is why, you are only seeing New York location and not all the locations
