### ISSUE TITLE
Error loading user in groups tab

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#453]
## Steps:

	1. Go to https://skill-search.topcoder-dev.com/ and login
	2. Go to second tab (Groups tab)
	3. Select Group "House Stark"
	4. Scroll downwards and observe the users displayed

## Actual Result:

	One user box shows "Error loading user"

## Expected Result:
	
	Should load users in most cases. Should try to show the data without errors (If error occured while parsing some attribute of user, that attribute may be skipped). Should also log detailed error in console.

## Screenshot/Video:

![Screenshot from 2020-07-13 15-42-54](https://user-images.githubusercontent.com/32861951/87293512-0b740680-c520-11ea-8721-daafa880af7d.png)

	
Browser: Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
No issue here - it is possible that loading a user fails. In which case you see that message.
