### ISSUE TITLE
Cannot select text in Bulk Uploads tab

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#454]
## Steps:

	1. Go to https://skill-search.topcoder-dev.com/ and login
	2. Go to third tab (Bulk Upload tab)
	3. Try selecting the instructions/text written there. (Drag profile data, or ‌browse ....)

## Actual Result:

	Not able to select text

## Expected Result:
	
	Should be able to select text. 

## Screenshot/Video:
![Screenshot from 2020-07-13 15-49-49](https://user-images.githubusercontent.com/32861951/87293871-8b01d580-c520-11ea-9e2a-70d24c2bfc84.png)

	
Browser: Firefox 78.0.1 (64-bit)

**Comment by callmekatootie** [comment]
don't see any reason to select the text
