### ISSUE TITLE
Can make changes to dialog behind

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#456]
## Steps:

	1. Go to https://skill-search.topcoder-dev.com/ and login
	2. Click on Edit button for some user
	3. In left side, click plus button to add groups
	4. New Group Dialog opens
	5. Try click cross for the groups in the dialog behind (the dialog with name and other details)

## Actual Result:

	You can make changes in the dialog behind the current one.

## Expected Result:
	
	Should not be able to make changes to anything else other than the current open top dialog (here, it should be group add dialog)

## Screenshot/Video:
[sc17.zip](https://github.com/topcoder-platform/u-bahn-app/files/4911890/sc17.zip)

	
Browser: Firefox 78.0.1 (64-bit), Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
duplicate #200
