### ISSUE TITLE
[Bug Hunt] Cancel/Save options are not visible after click on edit button of user

### ISSUE THREAD

**Issue by payaljagtap** [topcoder-platform/u-bahn-app#458]
Actual Result -  After click on edit button of user Cancel/Save options are not visible.
Expected Result - Cancel/Save options should be visible without rotating the PC screen.

Steps - 
1. URL : https://skill-search.topcoder-dev.com/
2. Login using tonyj / appirio123
3. Select topcoder .
4. Click on edit button of user

**Comment by callmekatootie** [comment]
duplicate #17
