### ISSUE TITLE
The app crashes when user attempts to create a group with a long name

### ISSUE THREAD

**Issue by MGTHEBOSS** [topcoder-platform/u-bahn-app#459]
**Target URL**

https://skill-search.topcoder-dev.com/

**Reproduction Steps**

1. Please open the target url mentioned above.
2. Click on the add group button under groups section in a profile.
3. In add to group modal, in the textbox, enter a long string, for instance, "Z4lD0cP3QE5xKrkFLJNCJaX5gE9VK5c562yXAVYt9a6P4MwjSs9anc58yxn5PK3JpmkV4V8DfyNMRykmPdsA42W9361JqYe4fzQVz22Mv3xhTF5LHqdUuzCMJfIhxDwFLmAv77F01L8TTJPQ2uKUKnD5KUbe0RSlqj7NXxw4c9bcV53sXElNrglPSBGUpyeb8PH0bYKeE7fgiP2Bn7sT6qLVYkojurzgC40BQTeC5YDVyyJl4fslJ6RXyeH41BOwfiPyMRiymfssxoApsypVUxKKdxZXIpXkvHmvvQykdRlPvPCYyZfuEMOFwMMbwnJyPQfBpAppYxBAuUIOhCjTBiRLPPqkbxAznuNnnghNjsPAEcHhGOfKiOzklkHgxKgswMkNRNPKuucjtBhihRFUNNCKBiykWlwtDfoxFvZmXoDRVepwlORmPjXnLORstjTezhXaSZFeXomVtaOcXWJreFGISCYazuHVbohDeQObkPMBceTSIgTvfpoUrVlIzEAhYsjqXwpTHGORSciwSHvAZzTJQkNmhWrWkXuiJSWTMkRqkzzkNfWmndpWoDbXrBEZyFdxJLZzfsxFLoJWcPjolddgfRQTioUCtvbsQRfiIrrcGKfjYNsnYevudWahFmiILtCvcRLRKLmkfiooNXimhTMAtOfyFnYVKwXMmOEQwIkhuLSUFSakpxLgHbBphCrVwHcLTAEgAuTDArykCocBymrffjMsdBYugMimWPpsIDaJQYoILiOAkxUdMFPPveWmuZMgebWQSHZRaQGSihdNyucrDaxRwOApHhoXnDSdctUWfvSCizexIyEGIzeEBEbJipXYrJYDpyjCnnyKrYPPCNdkCmhOKZYZRUNoaWIVAwizapOhGPNdMKenHQXCOQSBNwFbkNdSYASZBRIaKnADXpixcpzqotdbMWHZvUzSDksznJEBDrwlmqfaVAJRfbVOUAHXsSjqgMEovfMbXvtABlNvTVdpYIPpewyBhGwmJFYBwYIyahWFUSxZRqRYJnQLaVDMvRxUpQRFuzrioYZTwwUBFZXUkPBHAMwojRnpWDyMnYYqBMUUXrDLOZJmHBAxChTEpLeCWoKbrLVsMbAycCJMiWMeKKUJPtsgmUOPiXoOJJwBFLgWeJkjzQrtwCcvVETMRovItPpiMguzORvKVTMtIWdkKXDOQbTlpGRHxAKsKCYBANsxfJYQOZnHpvLGkBJcynVfNxNSltigqkfLegvECBgVkhgPluXbvvvAlkcEkXQreNTGHGoIJxSThKqdXSfolHogqnalQwTmIIbsgdhuzSwnhnkuTLiZMnJIpzTNGsHtUVrsDBIpYjJkoejXENSqOZdAQeitDPsbXPtOgjreifpzuMWPvBItcVMvNvziQhKvPnRyMdeRwwWzmRblaRfyVxAUplpgadCTwmPxtuZjDceGiLzkLUxnfoLXKJnQfRQmotcgkAJUDzfRcaiCWJBMaOeTaVvSUMmQeVdRlCtuiIKM".
4. Click on +create.

**Expected Result**

1. The group with the provided name should get created or an error message should be shown.

**Actual Result**

1. The app crashes.

**Screenshots or screencast**

[The app crashes when user attempts to create a group with a long name.zip](https://github.com/topcoder-platform/u-bahn-app/files/4911978/The.app.crashes.when.user.attempts.to.create.a.group.with.a.long.name.zip)

**OS/Browser Information**

Windows 7 professional 32 bit/chrome version 83.0.4103.116 (official build) (32-bit)

**Comment by callmekatootie** [comment]
duplicate #29

**Comment by callmekatootie** [comment]
not exactly a duplicate - but we need to prevent long group names through the same ticket
