### ISSUE TITLE
[Bug Hunt] Profile Name is going out of bounds and is not having validations 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#460]
<img width="1541" alt="Screen Shot 2020-07-13 at 4 56 26 PM" src="https://user-images.githubusercontent.com/34758872/87302135-73314e00-c52e-11ea-9ab2-e6438d8c9147.png">

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/

Expected Result: Should display profile names within the designated box
Actual Result : Profile names are not having validation and is going out of bounds 

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
duplicate #91
