### ISSUE TITLE
[Bug Hunt] After click on Reset button search box text is displaying previous filter

### ISSUE THREAD

**Issue by payaljagtap** [topcoder-platform/u-bahn-app#461]
Actual Result - After click on Reset button search box text is displaying previous filter
Expected Result - After click on Reset button search box text should not display the previous filter text

Steps -

1. URL : https://skill-search.topcoder-dev.com/
2. Login using tonyj / appirio123
3. Select topcoder .
4. Enter loction London on Search for a location textbox.
4. Click on London button.
5. Click on Reset button.

**Comment by callmekatootie** [comment]
reset will only clear the filters applied. search text for location is not an applied filter and thus remains
