### ISSUE TITLE
[Bug Hunt] General Attributes in Add Filters is showing even when there are filters matching it

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#462]
<img width="1507" alt="Screen Shot 2020-07-13 at 4 37 38 PM" src="https://user-images.githubusercontent.com/34758872/87298606-192d8a00-c528-11ea-92aa-b01140d50638.png">

Reproduction Steps:

Open the Application https://skill-search.topcoder-dev.com/
Search for String "com" in the Add Filters

Expected Result: Should display only filters with values as "com" , and not display heading if its not present
Actual Result : Returns main Heading of "General Attributes" even when there are no filter matching it

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
not a bug - it is indicating there are not results in general attributes section - the section title will not disappear
