### ISSUE TITLE
[Bug Hunt] Unable to search with Skills filter

### ISSUE THREAD

**Issue by payaljagtap** [topcoder-platform/u-bahn-app#463]
Actual Result - Unable to search with Skills filter

Expected Result - As entering the skills in Skills filter after entering unable to view any type of action

Steps -
1. URL : https://skill-search.topcoder-dev.com/
2. Login using tonyj / appirio123
3. Select topcoder .
4. Enter skills in Search skills to filter textbox.

**Comment by callmekatootie** [comment]
the skills should have shown in the dropdown suggestion from which you can select. Cannot reproduce issue.
