### ISSUE TITLE
Right (>) Half Arrow Or Forward Key Is Showing After Clicking On It

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#464]
1. Go To https://skill-search.topcoder-dev.com/

2. Click Icon Next To Filter Icon

3. See Below My Groups

4. See Options & Observe.

5. See Screencast & Screenshot:-
[33.mp4.zip](https://github.com/topcoder-platform/u-bahn-app/files/4912112/33.mp4.zip)
![33](https://user-images.githubusercontent.com/42583358/87299837-6874ba00-c52a-11ea-9d0f-cbe98c4de15c.png)

6. Current Result:- Right (>) Half Arrow Or Forward Key Is Showing After Clicking On It

7. Expected Result:- Right (>) Half Arrow Or Forward Key Should Show Without Clicking On It

8. Browser Version:- Firefox 78.0.2 (64-bit)

9. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
the arrow indicates the current active group along with the blue highlight - as per design
