### ISSUE TITLE
[Bug Hunt] Create Button in Select your Group Tab is status code 500  

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#465]
<img width="1536" alt="Screen Shot 2020-07-13 at 5 35 37 PM" src="https://user-images.githubusercontent.com/34758872/87303001-07e87b80-c530-11ea-8523-70347556ada4.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open Second Tab 
4. Click on Create Button
5. Unable to create Groups with a status of 500 

Expected Result: Should be able to create the group

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
duplicate #60
