### ISSUE TITLE
[Bug Hunt] Users are not getting loaded when searching in groups returning 500 error

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#466]
<img width="1512" alt="Screen Shot 2020-07-13 at 5 43 27 PM" src="https://user-images.githubusercontent.com/34758872/87303325-a379ec00-c530-11ea-90b5-cdffce55a6ea.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open Second Tab 
4. Click on first Group ->"House Stark" 
5. Groups of Profiles are not showing in the screen, with the error loading of user

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
cannot reproduce - probably a network issue
