### ISSUE TITLE
[Bug Hunt] One User is not getting loaded in groups screen , particular Get request is returning 500

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#467]
<img width="1677" alt="Screen Shot 2020-07-13 at 5 47 54 PM" src="https://user-images.githubusercontent.com/34758872/87303672-2a2ec900-c531-11ea-85f1-587d7ff2d3ee.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open Second Tab 
4. Select a particular Group -> "House Stark" 
5. One Users profile is not loaded , as per screenshot attached

Expected Result : All Profiles should be loaded successfully

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
duplicate #453
