### ISSUE TITLE
[Bug Hunt]Able to click on Reset button even when No filters applied

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#468]
**Steps to reproduce:**
1.Launch the url https://skill-search.topcoder-dev.com/
2.Login with credentials: tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87303476-dd4af280-c530-11ea-99ec-05df526597af.png)

3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87303545-feabde80-c530-11ea-8599-c7062611ac7f.png)
4.Verify various profiles displayed
![image](https://user-images.githubusercontent.com/68163678/87303621-197e5300-c531-11ea-8f78-651c3465ca4e.png)

5.Now click on Reset button without selecting any filters.
![image](https://user-images.githubusercontent.com/68163678/87303698-3450c780-c531-11ea-8bfe-62e6d176cc8f.png)

**Actual result:**
User is able to click Reset button without selecting any filter
**Expected result:**
Reset button should be disabled if user have not selected any filters.
**Device\Browser\OS:**
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #227
