### ISSUE TITLE
[Bug Hunt] Blank Excel sheet Uploaded in Tab 3 is not giving Error

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#469]
<img width="1611" alt="Screen Shot 2020-07-13 at 5 53 13 PM" src="https://user-images.githubusercontent.com/34758872/87304292-37988300-c532-11ea-9af6-fcd2e9c86a61.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open Third Tab 
4. Upload a Blank Excel sheet 
5. Shows the response as Success

Expected Result: Should show Error as the excel sheet is not of correct format

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
not a bug - we currently do not perform any validations (or rather we do, but the errors are shown internally only)
