### ISSUE TITLE
first letter should be in capital under company attributes - add filters page

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#47]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2.  scroll down and click on Add filter page, first letter should be in capital under company attributes

Current results
first letter should be in capital under company attributes in location and company 

Expected results

first letter should be in capital under company attributes in location and company similar to General Attributes section

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 6 49 46 PM](https://user-images.githubusercontent.com/57220292/87247296-a44b4900-c470-11ea-8c28-ecee8ceac264.png)

**Comment by callmekatootie** [comment]
not a valid bug. the name of the company attribute matches the one that the user has provided at the time of user creation. General attributes are special - in that, each user must have a value for them (and for some, the internal label is different than the one seen in the UI).
