### ISSUE TITLE
[Bug Hunt] When user have selected all the filters then also Add Filter option is displayed

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#470]
**Steps to reproduce:**
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87304381-5a2a9c00-c532-11ea-821f-be2f1c8fef42.png)

3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87304394-6151aa00-c532-11ea-8205-efb42fcd0821.png)
4.Verify various profile displayed
![image](https://user-images.githubusercontent.com/68163678/87304449-775f6a80-c532-11ea-8f46-174a38016d06.png)

5.Now scroll down and click on Add filters and select all filters from the list
![image](https://user-images.githubusercontent.com/68163678/87304540-9b22b080-c532-11ea-8401-fdfe5ecf6bfd.png)
6.Click on Save.
7.Verify Add Filter option is still displayed to customer
![image](https://user-images.githubusercontent.com/68163678/87305119-96123100-c533-11ea-8a1d-c9d31ac2738e.png)

**Actual result:**
Add Filter is displayed to the customer even when user have selected all filters
**Expected result:**
Button should be renamed as Add\Remove Filter as user does both.
**Device\Browser\OS:**
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
because you can remove any filter through the same option

**Comment by callmekatootie** [comment]
i'll take this as a bug - we can update text to say "manage filters" instead

**Comment by wdprice** [comment]
I was going to decline to fix this one, but I like the proposed language change @callmekatootie. Let's go ahead with it.

**Comment by callmekatootie** [comment]
Resolved
