### ISSUE TITLE
[Bug Hunt]For filters chevron down icon displayed even when user open it

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#471]
**Steps to reproduce:**
1.Launch the url:https://skill-search.topcoder-dev.com/

2.Login with credentials:tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87306045-11c0ad80-c535-11ea-8ec0-f36b6d046e33.png)

3.Select Topcoder
![image](https://user-images.githubusercontent.com/68163678/87306083-1e450600-c535-11ea-81f8-0a929a3f4ca3.png)

4.Verify various profile displayed
![image](https://user-images.githubusercontent.com/68163678/87306130-33219980-c535-11ea-89e4-7cd06f9d61c7.png)

5.Verify in Filters area when accordion is open then also chevron down icon is displayed and when accordion is closed then also chevron down icon is displayed.
![image](https://user-images.githubusercontent.com/68163678/87306306-74b24480-c535-11ea-9a6b-4694502b3901.png)
![image](https://user-images.githubusercontent.com/68163678/87306368-88f64180-c535-11ea-9a83-88020b66afaa.png)

**Actual result:**
Chevron down icon is displayed when filter accordion is open and closed
**Expected result:**
When accordion is open then chevron up icon should be displayed

**Device\Browser\OS:**
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #88
