### ISSUE TITLE
[Bug Hunt] Clicking on reset does not reset the Availability filter in the UI , it shows selected 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#472]
<img width="1637" alt="Screen Shot 2020-07-13 at 6 34 43 PM" src="https://user-images.githubusercontent.com/34758872/87307663-a3311f00-c537-11ea-8cf9-b47ba1d3ec9d.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open First Tab 
4. Select the Availability Filter , Both Available and Unavailable
5. Click on Reset Button
6. The Filter is removed and the data is getting loaded correctly
7. But in the UI the Availability green dots are in selected state

Expected Result:  The Availability UI field should be reset, with grey dots 

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
duplicate #136
