### ISSUE TITLE
[Bug Hunt] The Second Tab [Group Tab] is taking time to load, despite less data

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#474]
Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open Second Tab 
4. The Group Tab is taking time to load 

Expected Result: Should be able to load quickly, especially MY-GROUPS section which is specific to user.

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116) | Firefox | IE

**Comment by callmekatootie** [comment]
not a bug
