### ISSUE TITLE
[Bug Hunt] Performance in Dev tools shows there is chaining of critical requests

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#475]
<img width="1666" alt="Screen Shot 2020-07-13 at 7 14 19 PM" src="https://user-images.githubusercontent.com/34758872/87311736-433d7700-c53d-11ea-99ea-6eefed389bbd.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open LightHouse and explore the results for chaining as attached

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116)

**Comment by callmekatootie** [comment]
not a bug - we are not looking at this for now
