### ISSUE TITLE
[Bug Hunt]  Performance shows that first load of content is taking time 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#476]
<img width="1639" alt="Screen Shot 2020-07-13 at 7 18 19 PM" src="https://user-images.githubusercontent.com/34758872/87312155-d1b1f880-c53d-11ea-8bcb-e29f2b5dadeb.png">

Reproduction Steps:

1. Open the Application https://skill-search.topcoder-dev.com/
2. Select Topcoder
3. Open Lighthouse and run the diagnostics

Expected Result:  Results show that the performance of loading is slow

Device/OS: Laptop | MAC OS (64bit)

Browser Information: Chrome (83.0.4103.116)

**Comment by callmekatootie** [comment]
not a bug - we are not looking at lighthouse for now
