### ISSUE TITLE
[Bug Hunt]Text Difference between title and icon

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/u-bahn-app#477]
Browser : IE 11
Windows -10
Steps to reproduce :-
 1. URL : https://skill-search.topcoder-dev.com/
 2. Login using tonyj / appirio123
 3. Select topcoder .
 4. View the title and Banner

Issue : Difference between title and icon

Expected Result : U-BAHN text should be same title and icon

![image](https://user-images.githubusercontent.com/61318135/87316992-0b85fd80-c544-11ea-86c7-1a54e83a8ad1.png)

**Comment by callmekatootie** [comment]
Not a bug

**Comment by ab668685** [comment]
Can you please explain why this is not a bug?This is UX issue.

**Comment by callmekatootie** [comment]
We don't have a naming convention at the moment - we will also most likely replace it with something specific to the client. That is an internal project name.
