### ISSUE TITLE
Endless loading of home page

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#478]
## Steps:

	1. Go to https://skill-search.topcoder-dev.com/?code=WV3wMGss9t4u6YgS&state=TUZhVG5JQlhfUnZ0emkyNWNZdVJ0ZEhDNEc1S1FuaFp0YWlYbjVzNzNYVw%3D%3D

## Actual Result:

	Endless loading and error message in console

## Expected Result:
	
	Should redirect to home/default state on error.

## Screenshot/Video:
[sc18.zip](https://github.com/topcoder-platform/u-bahn-app/files/4913784/sc18.zip)

	
Browser: Firefox 78.0.1 (64-bit), Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
this happens when you accidentally navigate away / close the page while the app is detecting the authentication after returning from auth0. Usually this gets resolved after you clear cache or close the browser

**Comment by g1tman** [comment]
@callmekatootie so is the issue not related to the main software component? As in, is it an issue with auth0 ?

**Comment by callmekatootie** [comment]
Right - it's more of a glitch that happens and not in our control
