### ISSUE TITLE
Already added Skills should not show up in the Skills dropdown if searched for the same keyword again

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#480]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ app
2. Login with tonyj /appirio123
3. Select organization 'Topcoder'
4. Go to Groups tab
5. Select a group
6. Click on edit profile icon
7. Search for "Java" in the Skills Search
8. Add the first search result
9. Now Search for "Java" in the Skills Search again
10. Notice the search results

### Screenshots or Screen Capture
[Screen Recording 2020-07-14 at 12.51.41 AM.zip](https://github.com/topcoder-platform/u-bahn-app/files/4914639/Screen.Recording.2020-07-14.at.12.51.41.AM.zip)

### Current Results
Already added Skills is showing in the Skills dropdown if searched for the same keyword again

### Expected Results
Already added Skills should not show up in the Skills dropdown if searched for the same keyword again

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
makes sense - but for now, the skill search is free form - you can try adding existing skills and it won't let you so not a bug for now
