### ISSUE TITLE
After adding multiple skills in the Edit profile page modal, there is no padding between the 'Deactivate this User' button and the modal dialog border

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#482]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ app
2. Login with tonyj /appirio123
3. Select organization 'Topcoder'
4. Go to Groups tab
5. Select a group
6. Click on edit profile icon
7. Zoom out the browser window to see the content
8. Add multiple skills and notice the padding between the 'Deactivate this User' button and the modal dialog border

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-14 at 1 03 24 AM" src="https://user-images.githubusercontent.com/5712602/87345839-4ef56180-c56e-11ea-87b4-46a0a1aff958.png">

### Current Results
After adding multiple skills in the Edit profile page modal, there is no padding between the 'Deactivate this User' button and the modal dialog border

### Expected Results
There should be some padding between the 'Deactivate this User' button and the modal dialog border even after adding multiple skills. Footer should be consistent in modal dialog, to show the content scroll should be enabled.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #17

**Comment by rprakash20** [comment]
@callmekatootie I think this bug is different than the one reported at #17 - which is about the over all edit popup, but this bug is to have some padding/margin in the footer of the dialog so that after adding multiple groups/skills.

**Comment by callmekatootie** [comment]
In general - we need to give a scroll to the modal if the content exceeds the height.
