### ISSUE TITLE
Able to scroll the main page when the 'Edit Profile' modal dialog is open

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#483]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ app
2. Login with tonyj /appirio123
3. Select organization 'Topcoder'
4. Go to Groups tab
5. Select a group
6. Click on edit profile icon
7. When the modal is open, scroll the main page
8. Notice the result

### Screenshots or Screen Capture
[Screen Recording 2020-07-14 at 1.10.56 AM.zip](https://github.com/topcoder-platform/u-bahn-app/files/4914735/Screen.Recording.2020-07-14.at.1.10.56.AM.zip)

### Current Results
Able to scroll the main page when the 'Edit Profile' modal dialog is open

### Expected Results
when 'Edit profile' modal is open, main page content should not be scrollable, since there is are multiple scrolls in the edit profile dialog also, it would confusing for the user.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
cannot reproduce
