### ISSUE TITLE
[Common] Duplicate Skills are displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#485]
https://take.ms/yzDGd

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Go to Skills and type: Web Content Management Systems

**Actual Result:** Duplicate Skills are displayed

**Expected Result:** Should remove the duplicates

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
We use a third party provider for the skills suggestions so not the app's fault
