### ISSUE TITLE
[Common] Should remove the profile from search result if the user removes the skill from profile and save

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#486]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Go to Skills and type: Web Content Management Systems
4. Edit the Profile and remove the skill : Web Content Management Systems from the profile
5. click Save
6. Check the List

**Actual Result:** Profile is still listed even thoguh user removes the currently filtered skill

**Expected Result:** Should remove the profile from search result if user removes the skill from profile and save

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/dK2Il

**Comment by callmekatootie** [comment]
the content is not dynamic - you need to manually trigger the search again. There is no detection of change in parameters that match search filters
