### ISSUE TITLE
Search keyword 'Armstrong LLC' won't return the profile name that have 'Armstrong' as the last name

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#487]
https://take.ms/vWng2

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enter 'Armstrong' to the search and ENTER (You can see the profiles that have 'Armstrong')
4. Enter 'Armstrong LLC' to the search and ENTER (You can see the profiles that have 'Armstrong' and 'LLC') But can't see the profile with the last name as 'Armstrong'

**Actual Result:** Search keyword 'Armstrong LLC' won't return the profile name that has 'Armstrong' as the last name

**Expected Result:** Should display that profile as well if both texts are recognized as separate keywords

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
PAID - http://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30134624
