### ISSUE TITLE
Search for 'C++' will display profiles with 'C#' also

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#488]
https://take.ms/7F4Or

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enter 'C++' to the search and ENTER 

**Actual Result:** Search for 'C++' will display profiles with 'C#' also

**Expected Result:** Should display profiles with 'C++' only. Here the search is different because C++ is not two words also. Displaying a profile with 'C#' for C++ is not good

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
this is more of a limitation than a bug right now
