### ISSUE TITLE
When navigates to another page from the pagination; bottom part of the page is displayed

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#489]
https://take.ms/MgI7g

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enter 'C++' to the search and ENTER 
4. Scroll down and click on page 2 from the pagination
5. Observe

**Actual Result:** Search for 'C++' will display profiles with 'C#' also

**Expected Result:** Should focus on the top part of the page If not user needs to scroll the page up every time and then scroll down again and click on the next page from the pagination.

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #66
