### ISSUE TITLE
Can click Done button without selecting anything from the model in Add Filter

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#49]
![image](https://user-images.githubusercontent.com/42398485/87247318-cca75900-c418-11ea-8a32-0cdc5ddff996.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click 'Add Filter' 
4. Search for an item
5. Don't select item
6. Click Done

**Actual Result:** Can click Done button without selecting anything from the model in Add Filter

**Expected Result:** Should disable the button if nothing selected

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/ohYdG

**Comment by callmekatootie** [comment]
not a valid bug. there is no close button and DONE is one of the ways to close it
