### ISSUE TITLE
User can't search for an exact match/item

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#490]
https://take.ms/l8F60

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enter "Watsica, Pouros and Hintz" to search
4. Check the result
5. Enter "Watsica, Pouros and Hintz" with "" to search
6. Check the result

**Actual Result:** User can't search for an exact match/item

**Expected Result:** Should be able to do that because if not lot of unnecessary data displayed on the search result

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a bug... there's no advanced search capabilities in the app right now
