### ISSUE TITLE
Clear the search will navigate the page to the 'Search' page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#491]
https://take.ms/Ksx3A

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enter "Watsica, Pouros and Hintz" to search and press ENTER
4. Go to Group and Upload
5. Click the clear button on the search textbox

**Actual Result:** Clear the search will navigate the page to 'Search' page

**Expected Result:** Should stay on the current selected tab

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
intentional - the top header search is meant for search page only and thus, it loads the search page on clearing the value
