### ISSUE TITLE
'+ Add filter' should be '+ Add filters' because user can add multiple filters

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#492]
https://take.ms/46O6v

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Check the button + Add filter

**Actual Result:** + Add filter

**Expected Result:** + Add filters

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate of #470 - changing name to manage filters makes more sense here
