### ISSUE TITLE
[Common] Previous selected filter is displayed, when user adds the filter from 'Add Filters' popup

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#493]
https://take.ms/ITbzM

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click '+ Add filter' and Billing Account/Experience (in months)/On internship or any
4. Set Experience (in months)=119
5. Go to 'Groups' tab
6. Go to 'Search' tabs and you can see all the custom added filters are gone
7. Click '+ Add filter' and Billing Account/Experience (in months)/On internship or any

**Actual Result:** Previous selected filter is displayed, when user adds the filter from 'Add Filters' popup

**Expected Result:** Should not display old applied filters

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #386
