### ISSUE TITLE
'Add to Group' popup '+ Create' button display as 'Creating...' even after the group is created

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#494]
https://take.ms/j7fop

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Edit a Profile
4. Click 'Add to Group'
5. Enter a name and click '+ Create'
6. After the success popup is displayed check the button

**Actual Result:** 'Add to Group' popup '+ Create' button display as 'Creating...' even after the group is created

**Expected Result:** Should reset to '+ Create' because success message means the group is created

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
after you click on the alert, the button changes back to `+Create` - the alert popup halts execution of the script and that is why the delay

**Comment by callmekatootie** [comment]
*it is how the browser's alert functions - and we are using the browser's own alert() function here
