### ISSUE TITLE
[Bug Hunt] Filtering Groups shows the heading of filter "My Groups" Though there is no matching item

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#495]
<img width="1273" alt="Screenshot 2020-07-14 at 8 40 16 AM" src="https://user-images.githubusercontent.com/34758872/87379487-08bff280-c5ae-11ea-93ca-9aa508f9ed45.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on “My Groups” ,
	4.	Add to Group , Search filter “m” 
	5.	My Groups does not return results, but shows heading as “My Groups”

Expected Result: Should not display heading if there are no results.

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a bug - the section title will not disappear if there are not results for it.
