### ISSUE TITLE
[Bug Hunt] TypeError while Creating Groups, Screen shows "Creating" Group and screen stuck

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#496]
<img width="1269" alt="Screenshot 2020-07-14 at 8 53 30 AM" src="https://user-images.githubusercontent.com/34758872/87380166-87695f80-c5af-11ea-8658-e23abdf4aadd.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on “My Groups” ,
	4.	Add to Group ,
	5.	Create Filter “ds”
	6.	It shows TypeError in console and the console shows “Creating” and is stuck
	
Expected Result: Group should be created 

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #116
