### ISSUE TITLE
Profiles that have 'Achievements' as Topcoder are not populated

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#497]
https://take.ms/7AoSi

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Go to Achievements > Select Topcoder
4. Observe

**Actual Result:** Profiles that have 'Achievements' as Topcoder are not populated

**Expected Result:** Should display all the profiles that have Topcoder as Achievements

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
will take this as a bug - most likely the Capital C is the cause Topcoder v/s TopCoder

**Comment by wdprice** [comment]
@callmekatootie Assuming this is a capitalization issue, I'm not marking this to fix immediately

**Comment by callmekatootie** [comment]
After discussion on Slack - Will not be fixed. Closing
