### ISSUE TITLE
User is able to enter text in the month field

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#50]
**Describe the bug**
User is able to enter text in the month field

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now click on second icon from the top
3. click on any group and click on any user edit option
4. scroll down go to custom attributes and observe you will able to add text in months field

**Actual Behavior**
you will able to add text in months field 

**Expected behavior**
There must be only numbers allowed in month field

**Screenshots**
[2020-07-12 18-48-57.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908556/2020-07-12.18-48-57.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
custom attributes are free text input. not a valid issue.
