### ISSUE TITLE
"Done" button text won't change to the "Save changes made" when user applies a group from Edit profile window

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#500]
https://take.ms/PgxGBX

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Click + and add a group and watch the done button text
4. Click Edit > Click + and add a group and watch the done button text

**Actual Result:** ""Done" button text won't change to the "Save changes made" when user applies a group from Edit profile window

**Expected Result:** Operation and behavior should be the same in both locations

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
That is intentional - the changes are saved only when the user clicks on Save in the edit modal
