### ISSUE TITLE
[Bug Hunt] Able to create groups which are same name but with different case

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#501]
<img width="1234" alt="Screenshot 2020-07-14 at 9 43 03 AM" src="https://user-images.githubusercontent.com/34758872/87383291-8e47a080-c5b6-11ea-8210-92e71c46decd.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on “My Groups” ,
	4.	Create a Group with “House stark” same name with different case
	
Expected Result: Group should not be created as its duplicate

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Not a bug.
