### ISSUE TITLE
[Bug Hunt] Upload Error message is not centered in boundary, spacing issue

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#502]
<img width="1256" alt="Screenshot 2020-07-14 at 9 46 19 AM" src="https://user-images.githubusercontent.com/34758872/87383543-29407a80-c5b7-11ea-9326-b1d656aeb055.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 03 (Upload)
	3.	Upload a wrong format.
        4.     Upload Error UI spacing issue
	
Expected Result: Upload Error Ui should not have spacing issue

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
looks fine to me
