### ISSUE TITLE
No able to filter out via On internship

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#503]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Try to filter via on internship 

**Actual Result:** 
No results reload when try to filter via On internship

**Expected Result:** 
Filter via On internship should working

**Screenshot**
[Bug17.zip](https://github.com/topcoder-platform/u-bahn-app/files/4916508/Bug17.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** Chrome 83.0.4103.106

**Comment by callmekatootie** [comment]
cannot reproduce - can see suggestions in the filter
