### ISSUE TITLE
[Bug Hunt] The Website is not dynamically resizing to fit the browser window

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#504]
Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Update the browser window, 
	3.	The website should dynamically update to fit the browser window
	
Expected Result: Website should dynamically update to browser window so that all features are shown

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a bug - it is not meant to be responsive
