### ISSUE TITLE
[Bug Hunt] Search is not dynamically returning results

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#505]
Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Search Bar
	3.	Type a name
	4.	Results should dynamically populate rather than clicking on enter button
	
Expected Result: Search Results should dynamically populate

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
not a bug. User has to press enter to trigger search
