### ISSUE TITLE
No result showing when try to search vai "Robel - Schamberger" name in company even same text available in member section 

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#506]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Go to topcoder and tap on first tab
3. Enable company via add filter and try to search via "Robel - Schamberger" but no result observe even same time existed in CUSTOM ATTRIBUTES section

**Actual Result:** 
search via "Robel - Schamberger" but no result observe even same thing existed in CUSTOM ATTRIBUTES section

**Expected Result:** 
search via "Robel - Schamberger" so result should observe result  same things existed in CUSTOM ATTRIBUTES section

**Screenshot**
[Bug18.zip](https://github.com/topcoder-platform/u-bahn-app/files/4916562/Bug18.zip)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** Chrome 83.0.4103.106

**Comment by callmekatootie** [comment]
valid bug

**Comment by wdprice** [comment]
@callmekatootie I got search results on this search term. I won't close this issue but am not prioritizing for the upcoming release.

**Comment by callmekatootie** [comment]
After discussion on Slack - Will not be fixed. Closing
