### ISSUE TITLE
[Filter][Common] Filter results are not displayed if user is on the second page while performing the filter

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#508]
https://take.ms/JB7Mt

**Apples to all the filters NOT to the `Title`**

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Search)
3. Enable All the filters via "+ Add filter"
4. Go to the page 01
5. In the filter; Set the Title=Investor Intranet Strategist (Data displayed)
6. Reset the Filter
7. Now go to Go to Page 2
8. In the filter; Set the Title=Investor Intranet Strategist (no Data)

**Actual Result:** Search results are not displayed if user is on the second page while performing the search

**Expected Result:** Should display the results

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
valid bug

**Comment by callmekatootie** [comment]
Actually taking this to be part of #507 instead - although one is the sidebar filter and one is in the header, they both are filters and thus cannot be taken as 2 separate bugs
