### ISSUE TITLE
filter reset Skills  data not cleared 

### ISSUE THREAD

**Issue by karthikbecse** [topcoder-platform/u-bahn-app#51]
Steps to reproduce
• 1. Go to application-https://crm-benefits-prototype.herokuapp.com/pharmacy
• 2. Enter seffsdfsdf sdffffffffffffffffffffffffffff as skill 
  click Reset 

Current results
filter reset Skills  data not cleared 

Expected results
should clear data 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Windows 10 
Screen shots
[bandicam 2020-07-12 18-52-20-106.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908559/bandicam.2020-07-12.18-52-20-106.zip)

**Comment by callmekatootie** [comment]
reset clears the selected filter(s). In your case, you only entered the skill name but did not select it as a filter. There was nothing to reset. not a valid issue
