### ISSUE TITLE
[Bug Hunt] Once clicked Save after editing profile,  it blocks user from progressing to other parts of app 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#510]
<img width="1241" alt="Screenshot 2020-07-14 at 11 43 16 AM" src="https://user-images.githubusercontent.com/34758872/87390998-8c3a0d80-c5c7-11ea-8f2a-18dfc17b5c51.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 01 (Users)
	3.	Edit a User and save
	4.	it shows as "Saving Changes Please wait" and blocks the user from progressing
	
Expected Result:  Once save is clicked it can close the dialog and do the save in background and user can move to other parts of app quickly.

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Intentional - the user cannot use other parts of the app since the data updates could take time and could be lost if user does another action
