### ISSUE TITLE
[Bug Hunt] Once clicked Save after editing user, to add a group, it blocks user from progressing to other parts of app quickly as it wait for response

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#511]
<img width="1184" alt="Screenshot 2020-07-14 at 11 51 07 AM" src="https://user-images.githubusercontent.com/34758872/87393651-20a66f00-c5cc-11ea-989a-9928d55c9e54.png">

Reproduction Steps:
1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Tab 01 (Users)
3. Edit a User, Select Add to Group
4. it shows as "Saving Changes Please wait" and blocks the user from progressing quicky to other parts of app

Expected Result: Once save is clicked it can close the dialog and do the save in background and user can move to other parts of app quickly.

Device/OS: Laptop | MACOS (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Intentional - the changes have to be saved before the user can do any other action
