### ISSUE TITLE
[Bug Hunt] Allows multiple files to be selected / dragged for upload in the tab-03 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#512]
Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 03 (Upload)
	3.	Select Multiple files to Upload
	4.	Though the first file gets uploaded in response , it allows to select multiple files to be dragged
	
Expected Result: User can select multiple files and drag to the upload section , though only the first one gets upload

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116

**Comment by callmekatootie** [comment]
Cannot reproduce - I can select only one file at a time
