### ISSUE TITLE
[Bug Hunt] Users data can be loaded more quickly , if response is optimized for the screen.

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#513]
<img width="1234" alt="Screenshot 2020-07-14 at 2 00 58 PM" src="https://user-images.githubusercontent.com/34758872/87403663-c52fad80-c5da-11ea-9cfc-fb2d9c6d4c9a.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 01 (User)
	3.	The required information on the screen is the user information and the groups
	4.	Response has lot more details which is not required for first screen load for example 
	
<img width="935" alt="Screenshot 2020-07-14 at 2 00 19 PM" src="https://user-images.githubusercontent.com/34758872/87403666-c7920780-c5da-11ea-9233-525fd05be29c.png">

Expected Result: THE response has skills and atributes which are not required in first screen, only in the details, so less data gets transferred in the requests, leading to faster loading

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Your reasoning is valid but for this iteration of the app I cannot take it as a bug.
