### ISSUE TITLE
[Bug Hunt] On First Load of website or refresh of URL , duplicate "user" request are being made 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#514]
<img width="1279" alt="Screenshot 2020-07-14 at 2 25 20 PM" src="https://user-images.githubusercontent.com/34758872/87406958-1e99db80-c5df-11ea-8817-efaafbdc2e01.png">

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Open Network Tab
	3.	There are 2 n/w request for user, with one request is cancelled

Expected Result:  Duplicate Requests should not go through on reloading page

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Check https://github.com/topcoder-platform/u-bahn-app/issues/341#issuecomment-659923348
