### ISSUE TITLE
special characters needs to be handled correctly in skill search API query

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#515]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ app
2. Login with tonyj /appirio123
3. Select organization 'Topcoder'
4. Now in Skills filter, type "a" in the text box, dropdown will show the suggested options 
5. Now, type "a^^^^^" in the search box, notice the dropdown.
6. Do the previous step for special characters !, @,#,$, %, ^, &, *, (, ), _, -, =.

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-14 at 2 35 15 PM" src="https://user-images.githubusercontent.com/5712602/87408031-8ef52c80-c5e0-11ea-82ca-473b5152dbaf.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 35 47 PM" src="https://user-images.githubusercontent.com/5712602/87408046-93b9e080-c5e0-11ea-9ff2-f944067194c5.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 36 55 PM" src="https://user-images.githubusercontent.com/5712602/87408051-9583a400-c5e0-11ea-9509-010e30b7fe60.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 37 31 PM" src="https://user-images.githubusercontent.com/5712602/87408059-974d6780-c5e0-11ea-931a-735ff07f0ec1.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 38 34 PM" src="https://user-images.githubusercontent.com/5712602/87408068-99172b00-c5e0-11ea-858f-92c1476cd465.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 39 18 PM" src="https://user-images.githubusercontent.com/5712602/87408074-9b798500-c5e0-11ea-83d0-a9d9f2f905c2.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 39 55 PM" src="https://user-images.githubusercontent.com/5712602/87408079-9caab200-c5e0-11ea-8049-08f3f442a03e.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 40 44 PM" src="https://user-images.githubusercontent.com/5712602/87408085-9f0d0c00-c5e0-11ea-8a75-af1229a77b51.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 41 21 PM" src="https://user-images.githubusercontent.com/5712602/87408094-a0d6cf80-c5e0-11ea-884d-157dd5a2ad46.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 41 51 PM" src="https://user-images.githubusercontent.com/5712602/87408104-a207fc80-c5e0-11ea-8be7-9dd815ae0f11.png">
<img width="1440" alt="Screenshot 2020-07-14 at 2 42 15 PM" src="https://user-images.githubusercontent.com/5712602/87408110-a3d1c000-c5e0-11ea-9fe7-dfb51a2621e6.png">

### Current Results
special characters are not handled correctly in skill search API query

### Expected Results
special characters needs to be handled correctly in skill search API query, and search results should show only relevant content.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #295
