### ISSUE TITLE
[Bug Hunt] Count of the Groups are not updating on adding and removing groups from user 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#516]
Video 
https://drive.google.com/file/d/1p__oUPtD2tLdZ7Teyl8qOOdvELd5F_3C/view?usp=sharing

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on group , remove the group from a user profile
	4.	The counts are not getting updated

Expected Result:  Counts of the user should get updated 

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
group count is static - it will update if come to the page again from another page
