### ISSUE TITLE
[Bug Hunt] When user selects Avengers groups then a profile with "ERROR LOADING USER" is displayed

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#517]
**Steps to reproduce:**
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
![image](https://user-images.githubusercontent.com/68163678/87411987-13967980-c5e6-11ea-8455-c583a589c8d9.png)
3.Select topcoder
![image](https://user-images.githubusercontent.com/68163678/87412021-1ee9a500-c5e6-11ea-9730-579f93e8c11b.png)
4.Verify various profile displayed
![image](https://user-images.githubusercontent.com/68163678/87412086-31fc7500-c5e6-11ea-9092-382cc53e2f7d.png)
5.Navigate to 2nd tab
![image](https://user-images.githubusercontent.com/68163678/87412132-42aceb00-c5e6-11ea-8281-b554f1481fac.png)

6.Select Avengers Group from the list
![image](https://user-images.githubusercontent.com/68163678/87412226-696b2180-c5e6-11ea-84f5-e13f8586d668.png)

7.Scroll down and verify   a profile with "ERROR LOADING USER" is displayed
![image](https://user-images.githubusercontent.com/68163678/87412302-81db3c00-c5e6-11ea-98ae-d5133ac680f3.png)

**Actual result:**
A profile with "ERROR LOADING USER" is displayed from Avengers group

**Expected result:**
Such profile should not be displayed

**Device\Browser\OS:**
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #453
