### ISSUE TITLE
[Bug Hunt]Alignment issue for TaaS - Front End Developers and TaaS - Back End Developers

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#518]
**Steps to reproduce:**
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profile displayed to the user.
5.Navigate to 2nd tab
6.Select TaaS - Front End Developers  from the list of groups.
![image](https://user-images.githubusercontent.com/68163678/87413325-c9ae9300-c5e7-11ea-859f-8ecef2781f2c.png)

7.Now click on Edit button of any profile (here I have used profile Christopher DeLaurenti's)
![image](https://user-images.githubusercontent.com/68163678/87413757-5c4f3200-c5e8-11ea-8133-5675109b65a3.png)
8.Scroll down and verify alignment for  TaaS - Front End Developers and TaaS - Back End Developers
![image](https://user-images.githubusercontent.com/68163678/87413890-8bfe3a00-c5e8-11ea-87c3-975a17db25dc.png)

**Actual result:**
Alignment for TaaS - Front End Developers and TaaS - Back End Developers group is not correct
**Expected result:**
Alignment should be correct for TaaS - Front End Developers and TaaS - Back End Developers group
**Device\Browser\OS:**
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #29
