### ISSUE TITLE
[Bug Hunt]  Keyboard Tab functionality not enabled to shift across the tabs

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#519]
Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 01 (User)
	3.	Click on Keyboard tab to shift to next Tab 02(Groups)
        4.     Tab functionality is not enabled
	
Expected Result: Tab can be used to moved to next tabs on screen

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #209
