### ISSUE TITLE
[Bug Hunt] Issue when user search for any group which is not available in the list

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#520]
Steps to reproduce:
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profile displayed to the user.
5.Navigate to 2nd tab
6.Now search for group which is not in the list
![image](https://user-images.githubusercontent.com/68163678/87415963-9a9a2080-c5eb-11ea-8778-67e1c0f03f01.png)
7.Verify My groups and Other groups are displayed.

Actual result:
When user search for any group which is not in the list then also My group and Other group are displayed
Expected result:
When user search for any group which is not in the list then appropriate message should be displayed .
Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #315
