### ISSUE TITLE
[Bug Hunt] Two location filter are displayed when user selects All filters

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#521]
Steps to reproduce:
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profile displayed to the user.
![image](https://user-images.githubusercontent.com/68163678/87416887-029d3680-c5ed-11ea-81ce-da2a24854ba3.png)
5.Select all filter by Add filter
![image](https://user-images.githubusercontent.com/68163678/87416982-1f396e80-c5ed-11ea-9053-57b708f1e529.png)
6.Now 2 location filter are displayed
1st
![image](https://user-images.githubusercontent.com/68163678/87417097-4e4fe000-c5ed-11ea-8569-8fdbbfe46609.png)
scroll down and find 2nd location filter
![image](https://user-images.githubusercontent.com/68163678/87417168-6de70880-c5ed-11ea-8270-59201f78057c.png)

Actual result:
Two location filter are displayed
Expected result:
There should be only one location filter
Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #85
