### ISSUE TITLE
[Bug hunt] Two profile filters with same result are present

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#522]
Steps to reproduce:
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profiles are displayed
![image](https://user-images.githubusercontent.com/68163678/87417547-fc5b8a00-c5ed-11ea-8b38-2a09ab04803a.png)
5.Scroll down and click on add filter and select All filters from the list
![image](https://user-images.githubusercontent.com/68163678/87417617-185f2b80-c5ee-11ea-933f-b95ad0f66bfc.png)
6.Now verify two filters 
![image](https://user-images.githubusercontent.com/68163678/87417725-3af14480-c5ee-11ea-8983-eae53d089754.png)
scroll down and find another one
![image](https://user-images.githubusercontent.com/68163678/87417816-552b2280-c5ee-11ea-99b2-d372c5ff370f.png)

Actual result:
 Avaliability and isAvailable two filters are available but both does the same work.
Expected rsult:
Only one filter should be present 

Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #85
