### ISSUE TITLE
[Bug Hunt] When user clicks on Add filter then also background is displayed

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#523]
Steps to reproduce:
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profile displayed to the user.
5.Scroll down and click on Add Filter
![image](https://user-images.githubusercontent.com/68163678/87418313-16e23300-c5ef-11ea-804d-249403a1fd09.png)

Actual result:
In background profile screen is visible which is not good user experience when user tries to search any filter
![image](https://user-images.githubusercontent.com/68163678/87418429-4d1fb280-c5ef-11ea-9afe-7e5503e0a0a8.png)

Expected result:
When user clicks on Add filter then background should not be displayed.

Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
duplicate #39
