### ISSUE TITLE
[Bug Hunt] Issue when user search for filters

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#525]
Steps to reproduce:
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profile displayed to the user.
5.Scroll down and click on Add Filter
![image](https://user-images.githubusercontent.com/68163678/87418748-d7681680-c5ef-11ea-8f3a-cdaeba2de50f.png)

6.Now search for any filter from GENERAL ATTRIBUTES or COMPANY ATTRIBUTES
![image](https://user-images.githubusercontent.com/68163678/87418915-375ebd00-c5f0-11ea-8bc5-abeecfab2af3.png)

Actual result:
When user search filter from GENERAL ATTRIBUTES then also COMPANY ATTRIBUTES is displayed and when user serach filter from COMPANY ATTRIBUTES  then also GENERAL ATTRIBUTES is displayed.
![image](https://user-images.githubusercontent.com/68163678/87419087-80af0c80-c5f0-11ea-8986-ae1acedd4b16.png)
![image](https://user-images.githubusercontent.com/68163678/87419132-958ba000-c5f0-11ea-9763-4b1ea7ecc317.png)

Expected result:
Only the attribute from which user is searching only that should be displayed

Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
not a bug - it is just the section title
