### ISSUE TITLE
[Bug Hunt] Filter icon is not clickable

### ISSUE THREAD

**Issue by komal123s** [topcoder-platform/u-bahn-app#526]
Steps to reproduce:
1.Launch the url:https://skill-search.topcoder-dev.com/
2.Login with credentials:tonyj\appirio123
3.Select topcoder.
4.Verify various profile displayed to the user.
5.Verify filter icon is displayed but it is not clickable
![image](https://user-images.githubusercontent.com/68163678/87419416-1480d880-c5f1-11ea-9098-1dec0b507e73.png)

Actual result:
filter icon is displayed but it is not clickable
Expected result:
If filter icon is displayed it should be clickable

Device\Browser\OS:
Laptop
Google Chrome(Version 83.0.4103.116 (Official Build) (64-bit))
Windows 10

**Comment by callmekatootie** [comment]
not a bug - there's no action with that

**Comment by komal123s** [comment]
@callmekatootie If there's no action with that then it should not be displayed to the user

**Comment by callmekatootie** [comment]
it's part of the design - just a friendly icon I would say
