### ISSUE TITLE
[Bug Hunt] Search Keywords can be saved for the user for easier search

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#528]
Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the  Search Tab
	3.	Last few Search items list can help the user to not retype the search criteria 
Expected Result: Recently Searched Items can help in quicker search

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Not a bug. More like a feature
