### ISSUE TITLE
special characters needs to be handled correctly for COMPANY ATTRIBUTES filters (attributes search API query '/v5/search/userAttributes')

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#529]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ app
2. Login with tonyj /appirio123
3. Select organization 'Topcoder'
4. Click on Add Filter and enable all the 'COMPANY ATTRIBUTES' filter
5. Now type "a" in the company search box
6. Notice the search results
7. Now type "a+++++" or "a*****" or "a@@@@"  in the company search box
8. Notice the search results
9. Try this with other special characters also -  !, @,#,$, %, ^, &, *, _, -, =.
10. Try this with other company attributes filter - company, location, gender, isAvailable, title, Billing Account, Experience (in months), On internship.

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-14 at 5 01 07 PM" src="https://user-images.githubusercontent.com/5712602/87421120-0c766800-c5f4-11ea-9a84-aa7b229ab071.png">
<img width="1440" alt="Screenshot 2020-07-14 at 5 01 57 PM" src="https://user-images.githubusercontent.com/5712602/87421131-1304df80-c5f4-11ea-8ff3-f433c2d3834b.png">
<img width="573" alt="Screenshot 2020-07-14 at 5 03 57 PM" src="https://user-images.githubusercontent.com/5712602/87421134-14360c80-c5f4-11ea-95a6-7b64562572b0.png">

### Current Results
special characters are not handled correctly in attributes search API query '/v5/search/userAttributes'

### Expected Results
special characters needs to be handled correctly in attributes search API query, and search results dropdown should show only relevant content.

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by callmekatootie** [comment]
duplicate #295
