### ISSUE TITLE
[Bug Hunt] Clicking on Reset continuously makes new requests even though there is no filters added

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#530]
Video : https://drive.google.com/file/d/1gG9c9IaPrAEvjeGA-sW65pMmQQjsVboR/view?usp=sharing

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 01 (Users)
	3.	Click on Reset Multiple Times
	4.	The "users" request is occurring multiple times when there is no update to filter
	
Expected Result: Clicking reset without any update to filter should not make user "requests" multiple times 

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #208
