### ISSUE TITLE
attributes search API query '/v5/search/userAttributes' crashes with HTTP status 400 for few special characters

### ISSUE THREAD

**Issue by rprakash20** [topcoder-platform/u-bahn-app#531]
### Steps to Reproduce

1. Open “https://skill-search.topcoder-dev.com/“ app
2. Login with tonyj /appirio123
3. Select organization 'Topcoder'
4. Click on Add Filter and enable all the 'COMPANY ATTRIBUTES' filter
5. Enable browser inspector and click on network tab of inspector
6. Search for either of these characters '(', ')', '[', '{', '<' in the Company search box
7. Notice the request in network tab of inspector.
8. Try this with other company attributes filter - company, location, gender, isAvailable, title, Billing Account, Experience (in months), On internship.
9. Notice the error in browser console and network tab.

<img width="1440" alt="Screenshot 2020-07-14 at 5 13 08 PM" src="https://user-images.githubusercontent.com/5712602/87422197-d76b1500-c5f5-11ea-96d4-3ffa95197cb9.png">

### Screenshots or Screen Capture
<img width="1440" alt="Screenshot 2020-07-14 at 5 13 00 PM" src="https://user-images.githubusercontent.com/5712602/87422183-d1753400-c5f5-11ea-934a-fc15a17ec435.png">

<img width="1440" alt="Screenshot 2020-07-14 at 5 23 54 PM" src="https://user-images.githubusercontent.com/5712602/87422751-d25a9580-c5f6-11ea-8fff-96b9fa562c16.png">

### Current Results
attributes search API query '/v5/search/userAttributes' crashes with HTTP status 400 for few special characters

### Expected Results
API request should not crash for these special characters and API should handle these characters gracefully and search dropdown should show the options matching these characters

### Console Logs
```
xhr.js:178 GET https://api.topcoder-dev.com/v5/search/userAttributes?attributeId=f3fd623f-a613-4e3c-bf2f-9df529ff4317&attributeValue=%7B 400
(anonymous) @ 2.f0003de4.chunk.js:2
e.exports @ 2.f0003de4.chunk.js:2
e.exports @ 2.f0003de4.chunk.js:2
Promise.then (async)
c.request @ 2.f0003de4.chunk.js:2
r.forEach.c.<computed> @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ main.36d99be9.chunk.js:1
c @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
forEach.e.<computed> @ 2.f0003de4.chunk.js:2
r @ 2.f0003de4.chunk.js:2
a @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ main.36d99be9.chunk.js:1
(anonymous) @ main.36d99be9.chunk.js:1
c @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
forEach.e.<computed> @ 2.f0003de4.chunk.js:2
r @ 2.f0003de4.chunk.js:2
a @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
(anonymous) @ main.36d99be9.chunk.js:1
onChange @ 2.f0003de4.chunk.js:2
a @ 2.f0003de4.chunk.js:2
d @ 2.f0003de4.chunk.js:2
(anonymous) @ 2.f0003de4.chunk.js:2
y @ 2.f0003de4.chunk.js:2
ut @ 2.f0003de4.chunk.js:2
ot @ 2.f0003de4.chunk.js:2
at @ 2.f0003de4.chunk.js:2
dt @ 2.f0003de4.chunk.js:2
U @ 2.f0003de4.chunk.js:2
W @ 2.f0003de4.chunk.js:2
$t @ 2.f0003de4.chunk.js:2
Jt @ 2.f0003de4.chunk.js:2
t.unstable_runWithPriority @ 2.f0003de4.chunk.js:2
Vo @ 2.f0003de4.chunk.js:2
L @ 2.f0003de4.chunk.js:2
Ht @ 2.f0003de4.chunk.js:2
Show 11 more frames
createError.js:16 Uncaught (in promise) Error: Request failed with status code 400
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)
```

### Browser version and OS version
- Device: MacBook Pro 13 inch
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- OS Version: macOS Catalina 10.15.4

**Comment by rprakash20** [comment]
```
{"message":"[x_content_parse_exception] [1:251] [terms] failed to parse field [include]"}
```

**Comment by callmekatootie** [comment]
duplicate #295
