### ISSUE TITLE
[Bug Hunt] Clicks on the same user group multiple times, it make fresh requests .

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#532]
Video : https://drive.google.com/file/d/1z7fAa6QUdc9uD2Q6SDpHUSxDkRE58nKi/view?usp=sharing

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 02 (Groups)
	3.	Click on  a group multiple times
	4.	New requests are being made even if its the same group name
	
Expected Result: New Requests should not be made as we are clicking the same group.

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
duplicate #165
