### ISSUE TITLE
[Bug Hunt] Sort by functionality is making new requests even though there is a single user on screen

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#533]
Video  https://drive.google.com/file/d/1u4msK6ZwXBsFd4n8HSzZ_dBK4Ln-iGHH/view?usp=sharing

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 01 (Users)
	3.	Filter such that there is only one user 
	4.	Updating sorting criteria should not make fresh requests 
	
Expected Result: Sorting functionality should work only when there are multiple users results on screen

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Not a bug - more like a feature
