### ISSUE TITLE
[Bug Hunt] Particular Location is showing even when there are no users for it 

### ISSUE THREAD

**Issue by greenmug-md** [topcoder-platform/u-bahn-app#534]
Video : https://drive.google.com/file/d/1qLIgyoVYJyzZp3XNn-mMdAAAHqYahdOB/view?usp=sharing

Reproduction Steps:
	1.	Open the Application https://skill-search.topcoder-dev.com/
	2.	Click Topcoder > Go to the Tab 01 (Users)
	3.	Select a Location "North Raphaelli" , No users are present
	
Expected Result: Only filter was on location , If location does not have users it should not show on the List of Available Locations

Device/OS: Laptop | MACOS  (64bit)
Browser Information: Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
Location filter is static - predefined values exist for it, unlike the custom attributes
