### ISSUE TITLE
[IE11] Missing scroll bar for "Custom attributes"  item

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#535]
**Reproduction Steps:**
1. Open the application 
2. On first tab, Click on any "Edit profile" icon
3. Observe the "Custom attributes"  item

**Screenshot/screencast:**
IE11:

![IE11](https://user-images.githubusercontent.com/26895101/87428254-45bad200-c60c-11ea-9866-09cf95bb3726.png)

Chrome:

![Chrome](https://user-images.githubusercontent.com/26895101/87428272-4d7a7680-c60c-11ea-9d3c-a7e70a350057.png)

**Actual Result:** Missing scroll bar for "Custom attributes"  item

**Expected Result:** Should show scroll bar for "Custom attributes"  item same as browsers chrome and firefox

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11

**Comment by callmekatootie** [comment]
cannot reproduce. I am able to see the scrollbars just fine in IE11
