### ISSUE TITLE
Can click Done button without selecting anything from the model in Add to Group

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#54]
![image](https://user-images.githubusercontent.com/42398485/87247362-0e380400-c419-11ea-9191-146e6d580f88.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to first tab
3. Click 'Add to Group' 
4. Don't select item
5. Click Done

**Actual Result:** Can click Done button without selecting anything from the model in Add to Group

**Expected Result:** Should disable the button if nothing selected

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/QiuSv

**Comment by callmekatootie** [comment]
not a valid issue. DONE is one way of closing the modal. User need not have to click on CANCEL
