### ISSUE TITLE
[$10] tooltips needed for the three tabs

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#55]
### Reproduction Steps ###

1. open the app

2. observe the three tabs, hover on them

### Expected Result ###
Tooltips are needed so that it would be clear for the user what they're about.

### Actual Result ###
See screenshot

### Screenshot and/or screencast ###
![t](https://user-images.githubusercontent.com/4590317/87247364-095d6980-c486-11ea-8aee-16300a182e62.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
I'll take it as a bug. First time user would indeed not know what they represent.

**Comment by wdprice** [comment]
1. Search Profiles
2. Groups
3. Data Import

**Comment by callmekatootie** [comment]
Expected: Set the tooltips for each tab icon as mentioned above

**Comment by callmekatootie** [comment]
Resolved
