### ISSUE TITLE
[$10] Page change buttons not disabled

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/u-bahn-app#56]
## Steps to Reproduce

    1. Open the URL https://skill-search.topcoder-dev.com/ and login
    2. Select some filter and get results
    3. Scroll to bottom
    4. Hover over the arrow buttons

## Screenshots/Video

![Screenshot from 2020-07-12 18-51-45](https://user-images.githubusercontent.com/32861951/87247350-00ae6880-c471-11ea-8f64-681d939d63af.png)

##  Actual Result(s)

Arrow page change buttons not disabled for first, last page. (Cursor converts to hand button)

##  Expected Result(s)

Arrow page change buttons disabled for first, last page. CUrsor should not show as hand icon

##  Environment Details

    Browser(s): Firefox 78.0.1 (64-bit)

**Comment by g1tman** [comment]
By disabled, I mean mouse icon should not be converted to hand icon

**Comment by callmekatootie** [comment]
Not a valid bug. Clicking has no effect.

**Comment by g1tman** [comment]
@callmekatootie Mouse on hover shows hand/pointer icon which denotes clickable content.

**Comment by callmekatootie** [comment]
Makes sense. Will take it as a bug.

**Comment by callmekatootie** [comment]
Expected - in addition to being disabled, the pagination buttons should also NOT show the cursor pointer.

Test it in both Search and Group pages (where pagination is used)

**Comment by callmekatootie** [comment]
Resolved
