### ISSUE TITLE
clicking on enter button doesnt create a group

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#58]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. scroll down and type some text and press enter on keyboard to create group

Current results
scroll down and type some text and press enter on keyboard to create group - doesnt create group

Expected results

clicking on enter should create a new group

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 6 54 24 PM](https://user-images.githubusercontent.com/57220292/87247403-4703c780-c471-11ea-8769-abd84f7221b8.png)

**Comment by callmekatootie** [comment]
I would not take it as a bug - the input serves as both a filter and name for the new group. I would expect the user to explicitly click on CREATE to create the group

**Comment by akultalwar89** [comment]
@callmekatootie  - Hi, Alright, i was assuming if the button is specific for creating a New group so thought if no value is found and on click on Enter should create a group
