### ISSUE TITLE
[$10] User is unable to create a new group.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#60]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
2. Click on the second tab.
3. CLick on the "Create" button.

Actual results:
No response is shown by the application.

Expected results:
User should be allowed to create a new group.	

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![2](https://user-images.githubusercontent.com/57211549/87247406-6ac80d00-c473-11ea-886b-1526ba18a98f.png)

login credential:
tonyj / appirio123

**Comment by callmekatootie** [comment]
Valid bug. Just like #21 - here too, we need to show an alert to user to fill the group name

**Comment by callmekatootie** [comment]
Expected: Use browser's `alert()` feature to alert the user to enter a group name

**Comment by callmekatootie** [comment]
Resolved
