### ISSUE TITLE
[Bug Hunt] "OK" message is seen on logging out of the application.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#63]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
2. Click on the name on right top and click on "logout".

Actual results:
"Ok" message is seen.

Expected results:
User should be redirected back to login page.

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
![1](https://user-images.githubusercontent.com/57211549/87247435-90551680-c473-11ea-87bb-d4f938454da7.png)

login credential:
tonyj / appirio123

**Comment by callmekatootie** [comment]
@wdprice Valid bug? I think this is a config in auth0...

**Comment by devsreekrishna** [comment]
Hi

I Want To Say OK Button Should Not Be In Left Of Screen. It Should Be In Middle Of Screen.

thanks

**Comment by callmekatootie** [comment]
Discussed with PM - Valid bug. We need to take user to login page

**Comment by callmekatootie** [comment]
@wdprice The Auth0 config needs to be updated to white list the redirect urls - [Reference](https://auth0.com/docs/logout/guides/redirect-users-after-logout)

You need to add the following urls:
- http://localhost:3000 (For development)
- https://skill-search.topcoder-dev.com

**Comment by wdprice** [comment]
@cwdcwd - can you help with Auth0 config on this?

**Comment by callmekatootie** [comment]
@cwdcwd Thanks! However, something seems to be wrong.

When we logout out of https://skill-search.topcoder-dev.com/, it takes the user to login page - and after login, the user is taken to localhost:3000 instead of https://skill-search.topcoder-dev.com/ ...

I checked the logout url that we call on logout. It is:

```
https://topcoder-dev.auth0.com/v2/logout?redirect=https%3A%2F%2Fskill-search.topcoder-dev.com.....
```

The redirect url is correct - but even then the actual redirect seems to be localhost....

**Comment by cwdcwd** [comment]
the logout param is `returnTo` not `redirect`. See [docs](https://auth0.com/docs/logout/guides/redirect-users-after-logout)

**Comment by callmekatootie** [comment]
I cannot conclude why we used `redirect` instead of `returnTo` ... changed it now and it's resolve the issue. Sorry for the trouble!
