### ISSUE TITLE
Incorrectly formatted CSV can be uploaded

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#64]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Upload tab
3. Upload an incorrect CVS 

**Actual Result:** Incorrectly formatted CSV can be uploaded

**Expected Result:** Should validate

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/ZL9oA

**Comment by callmekatootie** [comment]
Valid concerns, however, right now, this is intended behaviour.

There's design to handle issues with the uploaded file and in this iteration, it is not in scope.

So - for this iteration of the bug hunt, not a valid issue.
