### ISSUE TITLE
unable to add skills in edit talent screen

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/u-bahn-app#67]
Unable to add skills in edit tal
[unable to add skills.docx](https://github.com/topcoder-platform/u-bahn-app/files/4908569/unable.to.add.skills.docx)
ent screen 
---------------------------------------------------------------------------------------------------------------
Device: Laptop

Operating System: Windows 10

Browser:Chrome

Steps to reproduce :
1.	Log in to the application https://skill-search.topcoder-dev.com/
2.	Select on edit talent 

3.	Unable to add skills 

Actual result:

Unable to add skills 

Expected results: 

skills should be able to add

**Comment by callmekatootie** [comment]
cannot reproduce. on entering skill name, a dropdown appears from which you can select and add the skill to the user
