### ISSUE TITLE
clicking on arrow should be disabled in no next page exist

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#68]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. select avenger group and scroll down and click on arrow - it remains clickable even if no other page exist

Current results
click on arrow - it remains clickable even if no other page exist

Expected results
It should disable clicking on arrow if no other page exist 

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 6 59 06 PM](https://user-images.githubusercontent.com/57220292/87247512-df01b100-c471-11ea-9ccb-5f5acee5e739.png)

**Comment by callmekatootie** [comment]
not a valid bug. clicking on it has no effect - it is disabled.

**Comment by akultalwar89** [comment]
@callmekatootie  - Here i wanted to tell that - If you will hover on the left or right arrow it shows you cursor (clickable) , usually in applications - when no page is available to click then cursor becomes unclickable. 
I couldnt take screen shot of it, can add video.

**Comment by akultalwar89** [comment]
Attaching the video. @callmekatootie 
[Screen Recording 2020-07-15 at 1.22.12 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4923686/Screen.Recording.2020-07-15.at.1.22.12.PM.mov.zip)

**Comment by akultalwar89** [comment]
@callmekatootie  - reference example - how it should be 
[Screen Recording 2020-07-15 at 1.51.45 PM.mov.zip](https://github.com/topcoder-platform/u-bahn-app/files/4924001/Screen.Recording.2020-07-15.at.1.51.45.PM.mov.zip)

**Comment by callmekatootie** [comment]
In which case this would be duplicate of #56

**Comment by akultalwar89** [comment]
Sure @callmekatootie  duplicate is fine :)
