### ISSUE TITLE
Layout getting distorted when user is a part of many groups 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#70]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) Enable all groups for user "Aang Airbender"
3) Observe in home page

Current Result :
Layout getting distorted when user is a part of many groups 

Expected result:
Layout  should not be changed based on  user is a part of how many groups.
Better mechanism should be present 

Latest Firefox
Windows 10

**Comment by coderkid19** [comment]
![5](https://user-images.githubusercontent.com/51490878/87247530-00629d00-c472-11ea-9597-b96df8109b6f.png)

![Firefox_version_77 0 2](https://user-images.githubusercontent.com/51490878/87247534-02c4f700-c472-11ea-8c39-be1e2e09d79a.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87247536-048eba80-c472-11ea-895c-9d6742082f18.png)

**Comment by callmekatootie** [comment]
not a valid bug. no limit at the moment on the number of groups to show
