### ISSUE TITLE
Can Upload the same file multiple times

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/u-bahn-app#71]
## Step To Reproduce
1. https://skill-search.topcoder-dev.com/
2. Login as ToniJ(topcoder)
3. go to upload excel tab

## Expected Result
We can only upload the same excel file for once time

## Actual Result
The current system can accept  multiple times for the same file

## Screenshot
![](https://www.dropbox.com/s/58q2ljn6eez61qx/upload.png?raw=1)

## Video
https://www.dropbox.com/s/6t6fixenedgmt6d/U-Bahn%20employee%20skills%20search%20portal%20-%20Google%20Chrome%202020-07-12%2016-26-41.mp4?dl=0

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 Home Single Language
c. Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by callmekatootie** [comment]
not a valid bug. the upload feature is to add new users or details about existing users. As such, there is no check necessary on whether data uploaded exists already or not
