### ISSUE TITLE
XLSX are also can be uploaded

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#72]
https://take.ms/AvSj3

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to the Upload tab
3. Upload an XLSX

**Actual Result:** XLSX are also can be uploaded

**Expected Result:** Should validate or should add XLSX also 

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
https://take.ms/exvJP

**Comment by callmekatootie** [comment]
Need to update tooltip to indicate that xlsx can also be uploaded

**Comment by callmekatootie** [comment]
Resolved
