### ISSUE TITLE
Getting An error occurred when getting the organization associated with your user

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/u-bahn-app#74]
**Steps to reproduce**

1. Open the application https://skill-search.topcoder-dev.com/ and login
2. Getting An error occurred when getting the organization associated with your user have not data loaded

**Actual Result:** 
No data loaded when login with correct user

**Expected Result:** 
Should be option topcoder loaded when login with id

**Screenshot**
![Bug2](https://user-images.githubusercontent.com/23450398/87247567-26883d00-c472-11ea-9a17-2bb7467b2f80.jpg)

**Device/OS:**  Think-pad | Windows 10 (64bit) 

**Browser Information:** IE11 11.329.19041.0| Chrome 83.0.4103.106 | Edge 83.0.478.54 | Firefox 78.0.2

**Comment by callmekatootie** [comment]
cannot reproduce. invalid.

**Comment by Krishna1507** [comment]
> 
> 
> cannot reproduce. invalid.

I don't know but i am still getting this issue in some of the browsers
[bug.zip](https://github.com/topcoder-platform/u-bahn-app/files/4938137/bug.zip)
