### ISSUE TITLE
Long group names are partially hidden

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#76]
![image](https://user-images.githubusercontent.com/42398485/87247585-4d1a8980-c41a-11ea-9d5a-de76f3e25b02.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to Groups tab
3. Enter 'Long group names are partially hidden' > Create
4. Observe

**Actual Result:** Long group names are partially hidden

**Expected Result:** Should display in two lines or should use ...

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
Step 03: Use "Leverage from the best of the talent from our organization" > Create

**Comment by callmekatootie** [comment]
Cannot reproduce.
