### ISSUE TITLE
"Add to group" popup should close when click outside

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/u-bahn-app#78]
**Reproduction Steps:**
1. Open the application: https://skill-search.topcoder-dev.com/
2. Click on any "+" button -> show "Add to group" popup
3. Click outside "Add to group" popup then observe

**Screenshot/screencast:**
https://drive.google.com/drive/folders/1t8vPk_2HhHY0JID8a3ozo_ngXNUC0A5X

**Actual Result:** "Add to group" popup doesn't close when click outside

**Expected Result:** "Add to group" popup should close when click outside

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** IE11 , Google Chrome 83.0.4103.116, Firefox 78.0.2

**Comment by callmekatootie** [comment]
not a valid bug. intentionally not allowing that (since in some cases, user needs to save the changes made and accidentally closing them will make lose the changes)
