### ISSUE TITLE
Skills are not getting searched  for adding on user details dialog

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/u-bahn-app#79]
**Describe the bug**
Skills are not getting searched  for adding on user details dialog

**To Reproduce**
1. Go to https://skill-search.topcoder-dev.com/
2. Now click on edit icon of any user
3. Now go to skills section and search for any skills to add
4. observe no operation is happening or no skills are getting searched

**Actual Behavior**
 no skills are getting searched in add skill edit field

**Expected behavior**
Skills must be searched

**Screenshots**
[2020-07-12 18-48-57.zip](https://github.com/topcoder-platform/u-bahn-app/files/4908574/2020-07-12.18-48-57.zip)

**OS/Browser:**
  - OS:  Windows 10 (64 Bit)
 - Browser: Chrome
 - Version:  83.0.4103.116

**Comment by callmekatootie** [comment]
cannot reproduce
