### ISSUE TITLE
Search results not reflecting search value

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/u-bahn-app#8]
**Steps to reproduce:**
1. Navigate to search bar and enter value `Python` then press enter to search
![image](https://user-images.githubusercontent.com/6014049/84279319-dc730b00-ab03-11ea-8499-b34c6b0b8efc.png)

2. Review resulting resources:
![image](https://user-images.githubusercontent.com/6014049/84279376-edbc1780-ab03-11ea-99e7-87cf02d74b61.png)

**Expected Result**
Only resources with a mention of "Python" in their skills, achievements, or custom attributes would be displayed.

**Actual Result**
All users in the system are displayed in results. See below for an example of a returned resource in a python search:
![image](https://user-images.githubusercontent.com/6014049/84279578-307def80-ab04-11ea-9ddd-8a1618420782.png)

**Comment by callmekatootie** [comment]
@wdprice 

How would this filter work with the filters in the sidebar:

**Comment by wdprice** [comment]
Filters I would think only affect the currently displayed search results.

For example:

1. User searches "Python"
2. All users who match the search "Python" are displayed in results.
3. User clicks Skill filter "API"
4. The results of the search (Python) is then filtered to only show search results who also possess "API" skill.

**Comment by callmekatootie** [comment]
Not sure if we can support both keyword filter and sidebar filter. Would need to check with the ES developer... Will get back here...

**Comment by callmekatootie** [comment]
This is now resolved. Keyword search also works
