### ISSUE TITLE
[Common] Group counts are incorrect

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#80]
**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to Groups tab
3. Select 'Night Owls' > items 
4. Observe. but 3 items are there

**Actual Result:** Group counts are incorrect

**Expected Result:** Should display the proper count

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by codejamtc** [comment]
I have used `Tony Group 1` group to create the video (5) items but 4 displayed - https://take.ms/KFYEx

**Comment by callmekatootie** [comment]
We display the count based on an external api - so not an issue with our app basically. The user returned for a group are also returns by same api...
