### ISSUE TITLE
[Availability] filter is not working properly when both the options are not selected it is retrieving all records

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/u-bahn-app#84]
Steps:
1)Login to portal https://skill-search.topcoder-dev.com/ with tonyj/appirio123  ( selected Org topcoder)
2) From Availability filter disable both the filter.
Observe retrieved result.

Current Result :
[Availability] filter is not working properly when both the options are not selected it is retrieving all records

Expected result:
In Availability filter when both the options are not selected it should not retrieve any record.

Latest Chrome
Windows 10

**Comment by coderkid19** [comment]
![6](https://user-images.githubusercontent.com/51490878/87247688-f1c8b580-c472-11ea-9edd-c2b13c0bbc9b.png)

![Chrome_Version_83 0 4103 116](https://user-images.githubusercontent.com/51490878/87247689-f3927900-c472-11ea-9d7d-bade3dac1723.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/87247693-f55c3c80-c472-11ea-9fcb-223a6e095da0.png)

**Comment by callmekatootie** [comment]
Not taking this as a valid bug.

If I take the approach of having both of them active by default, then when the user has to filter only users that are available, then they need to click on Unavailable to turn it off. Now, if they want to see users that are unavailable, they would have to first click on Unavailable to toggle it on and then Available to toggle it off - not a good UX. So keeping current behaviour
