### ISSUE TITLE
Logout Having UI Issue

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/u-bahn-app#86]
1. Go To https://skill-search.topcoder-dev.com/

2. Select Topcoder

3. Click Near TonyJ (Topcoder) Drop down & See Logout Button Then Observe

4. See Screenshot:-
![4](https://user-images.githubusercontent.com/42583358/87247660-d3fb5080-c472-11ea-9b1f-73488cf00753.png)

5. Current Result:- Logout Having UI Issue

6. Expected Result:- Logout Should Not Having UI Issue

7. Browser Version:- Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

8. OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

**Comment by callmekatootie** [comment]
"Having UI issue" is not a valid description.

**Comment by devsreekrishna** [comment]
Hi
Logout Is Not Aligned Centrally
Thanks

**Comment by callmekatootie** [comment]
Gotcha. That is intentional - the right align
