### ISSUE TITLE
Long Group Tag goes out of the section

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/u-bahn-app#87]
![image](https://user-images.githubusercontent.com/42398485/87247694-f3668f00-c41a-11ea-875f-45945ebee28a.png)

**Reproduction Steps:**

1. Open the Application https://skill-search.topcoder-dev.com/
2. Click Topcoder > Go to Groups tab
3. Create a group with "Leverage_from_the_best_of_saasdsadasd_sadadasda_sadasdsad_sdasdsad"
4. Observe

**Actual Result:** Long Group Tag goes out of the section

**Expected Result:** Should trim the group name

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Chrome 83.0.4103.116 | Firefox 78.0.2 | IE11

**Comment by callmekatootie** [comment]
cannot reproduce - it word wraps
