### ISSUE TITLE
Skills in sidebar skill filter not reflective of values in system

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/u-bahn-app#9]
**Steps to reproduce**
1. Review pills/tags in the sidebar, and the values available when using type-ahead search.
![image](https://user-images.githubusercontent.com/6014049/84280297-1c86bd80-ab05-11ea-83f6-168845388d0b.png)
![image](https://user-images.githubusercontent.com/6014049/84280342-29a3ac80-ab05-11ea-840d-4c0fad92745f.png)

2. Review Skills associated to resources in the application (appear to be all EMSI)
![image](https://user-images.githubusercontent.com/6014049/84280422-45a74e00-ab05-11ea-96ec-dd3e62d01482.png)

3. Attempt to filter in sidebar by skill which roughly matches (use Angular in this example)

**Expected Result**
Search results would show matches with the "Angular (Web Framework)" skill.

**Actual Result**
Stuck on loading screen. Presumably because there is no match.
![image](https://user-images.githubusercontent.com/6014049/84280633-90c16100-ab05-11ea-9476-1b5ccff3be56.png)

**Additional Notes**
- If no users match the filter criteria the message should read "No resources match current filters"
- Filters displayed in pills or type-ahead should match values present on resources in the system.

**Comment by callmekatootie** [comment]
@wdprice This is now resolved. Please check and let me know if you find issues with it.
