### ISSUE TITLE
there should be some some message shown if there are no results found when filtering the groups

### ISSUE THREAD

**Issue by winterflame** [topcoder-platform/u-bahn-app#92]
### Reproduction Steps ###

1. login to the app, click the 2nd tab

2. enter some text to filter groups, like "fdsafsadfads"

3. observe

### Expected Result ###
There should be some some message shown if there are no results found when filtering the groups.

### Actual Result ###
See screenshot

### Screenshot and/or screencast ###

![no](https://user-images.githubusercontent.com/4590317/87247731-22671a00-c488-11ea-9d08-fe836769a69e.jpg)

### Issue Information ###

Device/OS: *Mac Book Pro, macOS Catalina Version 10.15.5*

Browser Version: *Firefox 78.0.2 (64-bit)*

**Comment by callmekatootie** [comment]
not a valid bug.
