### ISSUE TITLE
sort by option should be left aligned, 

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/u-bahn-app#96]
Steps to reproduce
• 1. Go to application-https://skill-search.topcoder-dev.com/
• 2. sort by options should be left aligned

Current results
sort by options should be left aligned

Expected results
sort by options should be left aligned

• Browser version: Chrome: Version 83.0.4103.116
• OS version : Macbook Air , Catalina 10.15.2
Screen shots
![Screen Shot 2020-07-12 at 7 09 51 PM](https://user-images.githubusercontent.com/57220292/87247769-5dab1e00-c473-11ea-9698-59fd6fa52eeb.png)

**Comment by callmekatootie** [comment]
not a valid bug

**Comment by akultalwar89** [comment]
@callmekatootie  - hi, Usually Text start from left on all the picklists selections - It is looking little different out of sync.
just adding a random screen shot.,
![Screen Shot 2020-07-15 at 4 46 06 PM](https://user-images.githubusercontent.com/57220292/87538961-b4eeff80-c6ba-11ea-8c14-97b95280ebcf.png)

**Comment by callmekatootie** [comment]
I am saying that I see the developer has it explicitly right aligned. And thus I am not taking it as a bug.

**Comment by akultalwar89** [comment]
@callmekatootie - Sure Thanks Mithun - client might have asked it this way
