### ISSUE TITLE
[Bug Hunt] An Error message occurred while going to cool party.

### ISSUE THREAD

**Issue by CreeyaSean** [topcoder-platform/u-bahn-app#98]
Steps to reproduce:
1. Go to URL https://skill-search.topcoder-dev.com/ and login with valid credentials.
2. Navigate to the second tab.
3. Go to the Cool Party tab.
4. Observe the result shown.

Actual results:
User should be redirected to the cool party page

Expected results:
The error message pops up which reads like " An error occurred when getting company attributes for the custom filter. ""

Browser version: Chrome: Version 83.0.4103.116

Screen shots:
<img width="1392" alt="4" src="https://user-images.githubusercontent.com/57211549/87247776-8207fa00-c475-11ea-9423-839244318e33.png">

login credential:
tonyj / appirio123

**Comment by callmekatootie** [comment]
valid error. you were instructed to use Topcoder as your org.
